### ISSUE TITLE
Gos Server doesn't start

### ISSUE THREAD

**Issue by gittix09** [GeniusesOfSymfony/WebSocketBundle#1]
At Step 4:

[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]

 Unrecognized option "web_socket_server" under "gos_web_socket"

Note: In the same Symfon2 project I tried removing Gos Bundle and installing Clank Bundle..... Clank bundle works. The server was launched successfully.

**Comment by ProPheT777** [comment]
Can you past the configuration you used please ? I think the issue come from the documentation itself

**Comment by gittix09** [comment]
I did a copy paste from your documentation.. everything else is Symfony2 standard edition

# Web Socket Configuration
gos_web_socket:
    web_socket_server:
        port: 8080        #The port the socket server will listen on
        host: 127.0.0.1   #The host ip to bind to

**Comment by ProPheT777** [comment]
Indeed the docs is wrong, I made refactoring since I wrote it. 

```yaml
gos_web_socket:
    server:
        port: 8080
        host: 127.0.0.1
```

I will fix it tonight.

**Comment by gittix09** [comment]
Even with that configuration, I get an error (at leas a different one ;) )

InvalidConfigurationException: The child node "origin_check" at path "gos_web_socket.server" must be configured.

**Comment by gittix09** [comment]
And one more question: 

After doing the 4 steps here 
https://github.com/GeniusesOfSymfony/WebSocketBundle
and the first 2 steps here https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/ClientSetup.md

the following code for pubsub (step 3 of the page above) should work out of the box? I think so (since the documentation says that it's not mandatory to create a custom topic handler... so it should work even without the custom topic handler).
BUT for me it's not working... I don't see in the console a "Received message: ......"!!

'''javascript
  myWebSocket.on("socket/connect", function(session){

    //the callback function in "subscribe" is called everytime an event is published in that channel.
    session.subscribe("acme/channel", function(uri, payload){
        console.log("Received message", payload.msg);
    });

    session.publish("acme/channel", {msg: "This is a message!"});

    session.unsubscribe("acme/channel");

    session.publish("acme/channel", {msg: "I won't see this"});
  })

'''

**Comment by ProPheT777** [comment]
By following the steps on Readme, you just can start the websocket server. Here it's can be an error like you said because you MUST create a topic handler (at least one) to subscribe on channel from client side.

**Comment by ProPheT777** [comment]
I will start a new install of the bundle from scratch to raise and resolve all problems.

**Comment by gittix09** [comment]
Thanks!! I'm sorry to bother you... it's only that I would like to practice with the concepts/methods that are already present in the documentation.
Once that it's up and running, I'll patiently wait for future updates.
Thank you for everything

**Comment by ProPheT777** [comment]
I have improve docs, and fix all things who block to kickstart the bundle usage. Let's take a look of my last commits.

**Comment by gittix09** [comment]
I have:
- Updated the bundle via Composer
- Checked the documentation to make sure that I've followed every step

Result:
- The gos server works
- BUT step 1 of client setup fails

"The function "clank_client" does not exist ......"

(Note: I'm testing in dev environment)

**Comment by gittix09** [comment]
Also:
- In the Client Setup documentation, the link to Autobhan doc about PubSub is broken.
- In order to have the demo pubsub code working, after "Client Setup step 2", we follow the steps in the Topic Handler Setup right?

And then we paste the following code in the right position:

      myWebSocket.on("socket/connect", function(session){
         //the callback function in "subscribe" is called everytime an event is published in that channel.
        session.subscribe("acme/channel", function(uri, payload){
            console.log("Received message", payload.msg);
        });

        session.publish("acme/channel", {msg: "This is a message!"});
        session.unsubscribe("acme/channel");
        session.publish("acme/channel", {msg: "I won't see this"});
      })

Are there any other steps? 
Or it should work at this point?

- In ClankBundle documentation ther was one more step (missing in your documentation)
Look at step 3 in this page https://github.com/JDare/ClankBundle
    # Assetic Configuration
    assetic:
         ...
        bundles:        [ JDareClankBundle ]

**Comment by ProPheT777** [comment]
Ok I'll dig intoat lunch break for the JS Client. The step3 about configuring assetic bundle is useless. It's automatically done. Look at https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/DependencyInjection/GosWebSocketExtension.php#L141

**Comment by ProPheT777** [comment]
"The function "clank_client" does not exist ......"

Yes, this function is replaced by `ws_client` See https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Twig/GosWebSocketServerExtension.php#L24

I fixed the broken link. 

After Client Setup, follow the next step "topic handler" and after that, it should work yes. May be the sentence between step2 who send on step3 is not enough explicit ? 

> If your application requires more complexity than just repeating messages in channels, please see custom server side topic handlers

May be must I rewrite this ?

**Comment by gittix09** [comment]
First of all thank you very much... I can't wait to test it.
About the documentation, in my opinion you should change some things:
- in the client setup page - step 3: it should be more clear that for both RPC and PUBSUB it is NECESSARY (and not optional) to also configure the server side.
- in the "topic handler setup" page
https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/TopicSetup.md
from this sentence
"Although the standard Gos WebSocket PubSub can be useful as a simple channel for allowing messages to be pushed to users, anymore advanced functionality will require custom Topic Handlers"
I understood this...
"PubSub is working out-of-the-box after installing the bundle, but if you want to customize its functions you need to create a custom topic handler".
As you said in a previous message, it's not true... you always need to create at least one topic handler to use pubsub. In other words, it's not an option.

**Comment by ProPheT777** [comment]
Ok I change this part, I will also add a summary on README.md to show an fast overview of what must be done before start using it. 

Currently only the topic handler is mandatory in fact. It's an error of example, you don't RPC to use PubSub, RPC Handler is adding  capabilities to call procedure through the websocket. I must fixed it too because RPC is absolutely not related to PubSub, whereas the example show the inverse. That's problematic for newcomer, who believe it's linked.

**Comment by gittix09** [comment]
Good idea!! (I'm testing the PubSub right now)

In the meantime, I noticed that after launching the server I got some errors about the firewall. Is it normal?

    C:\xampp\htdocs\myproject>php app/console gos:server
[2015-03-11 14:48:24] websocket.INFO: Starting web socket [] []
[2015-03-11 14:48:25] websocket.INFO: Launching Ratchet on 127.0.0.1:8080 [] []
[2015-03-11 14:51:00] websocket.WARNING: User firewall is not configured, we hav
e set ws_firewall by default [] []
[2015-03-11 14:51:00] websocket.WARNING: User firewall is not configured, we hav
e set ws_firewall by default [] []
[2015-03-11 14:51:00] websocket.INFO: anon-5500484401d35 connected [ {"connectio
n_id":xxx,"session_id":"xxxxxxxxxxxxxxx","storage_id":xxx} []

**Comment by ProPheT777** [comment]
Yes and No, that depend if you want authenticate the client through websocket. 

Look at https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/SessionSetup.md for more details

**Comment by gittix09** [comment]
Ok, so for now it's ok... right now I'm trying to create the most basic demo of pubsub: one room with two users.

Another thing: in the topic handler documentation what should be the filename of the new topic class? AcmeTopic.php? I ask this because sometimes in Symfony there are some rules about naming (like Controllers that need to be like xxxxController.php)

**Comment by ProPheT777** [comment]
I have no rules about naming topic class, symfony controller have rules because they represent the fully qualified namespace with an alias to be more friendly. Here we don't have this, you can name it as you wish. In other hand, they are registered under service name through Symfony DIC, so I don't care about the class name. 

But {Prefix}Topic (e.g AcmeTopic) is a good name convention (I also used it).

**Comment by gittix09** [comment]
Ok, almost there. I can see the finish line. Here is the new error:

InvalidConfigurationException: Unrecognized option "topic" under "gos_web_socket"

I followed the steps in the topic handler page, but I skipped the "Retrieve the current user" part. It should work even without it, right? Just as anonymous user.

This is my configuration:
- I created src/Acme/DemoBundle/Topic/AcmeTopic.php (and updated the namespace inside the file)
- in config/services.xml

     <service id="acme_demo.topic_sample_service" class="Acme\DemoBundle\Topic\AcmeTopic"></service>

- in config.yml

    gos_web_socket:
        server:
            port: 8080
        host: 127.0.0.1

        topic:
            - @acme_demo.topic_sample_service

Also, PHPStorm says that there are a lot of errors in AcmeTopic.php (the methods onSubscribe, etc etc are not declared properly). I don't know... maybe it's just nonsense from the software.

**Comment by ProPheT777** [comment]
It's seems the documentation is wrong again :(

it's not `topic` but `topics` like it's show here : https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/DependencyInjection/Configuration.php#L67

> I followed the steps in the topic handler page, but I skipped the "Retrieve the current user" part. It should work even without it, right? Just as anonymous user.

Yes, it's work with anonymous user without any configurations.

Can you screenshot me your phpstorm, it's weird. Only variable through $conn cannot be reconized by phpStorm

 On my side it's looks like 

![capture du 2015-03-11 16 23 12](https://cloud.githubusercontent.com/assets/1763341/6599583/f6d0a44e-c80a-11e4-9fc9-57b0768df7b3.png)

**Comment by gittix09** [comment]
I fixed "topic" to "topics": now is ok.
But the other problem is still there. Here are more info (screenshot is coming soon):

// Windows console
    C:\xampp\htdocs\myproject>php app/console gos:server
    Fatal error: Declaration of Acme\DemoBundle\Topic\AcmeTopic::onSubscribe() must
    be compatible with Gos\Bundle\WebSocketBundle\Topic\TopicInterface::onSubscribe(
    Ratchet\ConnectionInterface $connection, Ratchet\Wamp\Topic $topic) in C:\xampp\
    htdocs\myproject\src\Acme\DemoBundle\Topic\AcmeTopic.php on line 15

**Comment by gittix09** [comment]
![acmetopic_error](https://cloud.githubusercontent.com/assets/4339303/6600169/57a8075a-c80e-11e4-8eb6-9aeafbe5b958.jpg)

Same error is displayed in PHPStorm as you can see.

**Comment by ProPheT777** [comment]
Yes, documentation again :(

In the documentation, type hint against $topic is missing. According to the interface `Gos\Bundle\WebSocketBundle\Topic\TopicInterface` you must implement method like this : 

```php
 use Ratchet\Wamp\Topic;

 public function onSubscribe(ConnectionInterface $connection, Topic $topic);

 public function onUnSubscribe(ConnectionInterface $connection, Topic $topic);

public function onPublish(ConnectionInterface $connection, Topic $topic, $event, array $exclude, array $eligible);
```

**Comment by gittix09** [comment]
Still the same problem.... sending you screenshot again in a second

**Comment by gittix09** [comment]
![acmetopic_error2](https://cloud.githubusercontent.com/assets/4339303/6600383/91cfd95c-c80f-11e4-833d-2f5511d8571e.jpg)

**Comment by ProPheT777** [comment]
Look at my last commit 85b75302bbd6fbd134f6dcfb8d8679434f495e55, I fixed topic -> topics and TopicHandler, it's because you `ConnectionInterface` when the example show  `Ratchet\ConnectionInterface as Conn`, remove `as Conn` and it will work.

**Comment by gittix09** [comment]
Now gos:server starts.
But there is another error. Here is the windows prompt report


    C:\xampp\htdocs\myproject>php app/console gos:server
    [2015-03-11 17:10:53] websocket.INFO: Starting web socket [] []
    [2015-03-11 17:10:53] websocket.INFO: Launching Ratchet on 127.0.0.1:8080 [] []
    [2015-03-11 17:11:07] websocket.WARNING: User firewall is not configured, we hav
    e set ws_firewall by default [] []
    [2015-03-11 17:11:07] websocket.WARNING: User firewall is not configured, we hav
    e set ws_firewall by default [] []
    [2015-03-11 17:11:07] websocket.INFO: anon-5500691b18f04 connected [ {"connectio
    n_id":336,"session_id":"5500691b18f04","storage_id":336} []
    [2015-03-11 17:11:07] websocket.INFO: anon-5500691b18f04 subscribe to acme/chann
    el [] []
    [2015-03-11 17:11:07] websocket.INFO: anon-5500691b18f04 publish to acme/channel
    [] []
    [2015-03-11 17:11:07] websocket.ERROR: Connection error occurred Notice: Undefin
    ed variable: conn in C:\xampp\htdocs\myproject\src\Acme\DemoBundle\Topic\AcmeTop
    ic.php line 68 in C:\xampp\htdocs\myproject\src\Acme\DemoBundle\Topic\AcmeTopic.
    php line 68 {"connection_id":336,"session_id":"5500691b18f04","client":"anon-550
    0691b18f04"} []
    [2015-03-11 17:11:07] websocket.ERROR: Connection error occurred Notice: Undefin
    ed variable: conn in C:\xampp\htdocs\myproject\src\Acme\DemoBundle\Topic\AcmeTop
    ic.php line 68 in C:\xampp\htdocs\myproject\src\Acme\DemoBundle\Topic\AcmeTopic.
    php line 68 {"connection_id":336,"session_id":"5500691b18f04","client":"anon-550
    0691b18f04"} []

**Comment by gittix09** [comment]
In the browser console I don't see "Message Received: etc etc......."

Moreover in PHPStorm "AcmeTopic.php" there are still 2 type of errors:
1) $conn: undefined variable 'conn'
2) resourceId: Field not found in class \Ratchet\ConnectionInterface

**Comment by ProPheT777** [comment]
Yes, regarding to the demo, $conn doesn't exists, it's a reliquat. I will fix it. 

Look at ec670ab3c09982dabe30574a7e0f0ff349a57b6b to adapt :)

**Comment by gittix09** [comment]
Ok, I copy-pasted the new AcmeTopic.php and now there are no more red-flagged errors. 
In windows terminal there are no more errors (apart the one of the firewall... but that is not a problem).

The only bug is that I don't still see the "Message Received: ....." in the browser console.

I've opened the webpage in two different browsers but in the console of each windows I only see "Successfully Connected!"

**Comment by gittix09** [comment]
This is the windows prompt report:

    [2015-03-11 17:31:50] websocket.INFO: anon-55006df6e0261 connected [ {"connectio
    n_id":559,"session_id":"55006df6e0261","storage_id":559} []
    [2015-03-11 17:31:50] websocket.INFO: anon-55006df6e0261 subscribe to acme/chann
    el [] []
    [2015-03-11 17:31:50] websocket.INFO: anon-55006df6e0261 publish to acme/channel
     [] []
    [2015-03-11 17:31:50] websocket.INFO: User anon-55006df6e0261 unsubscribed to ac
    me/channel [] []
    [2015-03-11 17:31:50] websocket.INFO: anon-55006df6e0261 publish to acme/channel
     [] []

**Comment by ProPheT777** [comment]
Yes ! It working, so.

What looks like your javascrit ?

**Comment by gittix09** [comment]
![gos_javascript](https://cloud.githubusercontent.com/assets/4339303/6601652/24b2d22c-c817-11e4-82a1-e877dee5956d.jpg)
![gos_console](https://cloud.githubusercontent.com/assets/4339303/6601656/2e52d0ca-c817-11e4-8d0d-06f22d9b55b8.jpg)

**Comment by ProPheT777** [comment]
When you refresh multiple time user2 when user1 stay on the web page with log console open, do you see the publish log ?

**Comment by gittix09** [comment]
No, I tried again just now but nothing.
Basically the users don't receive the messages.

**Comment by gittix09** [comment]
But the server seems to work, right?
The windows prompt log seems ok.

**Comment by ProPheT777** [comment]
Yes the server work, if you see "anon-xxxx published to acme/channel". IMO it's a client problem.

**Comment by ProPheT777** [comment]
Can you publish your demo project to dig into this issue ?

**Comment by gittix09** [comment]
Sure... but I'm not sure what to publish and how to do that. 
"myproject" is only the default Symfony standard edition + FosUserbundle + GosWebSocketBundle
There is no content (apart from two test twig files).
No configuration apart from the steps in the your guide and FosUserBundle.

**Comment by gittix09** [comment]
Which files would you need? The whole folder (including /app, /vendor ... etc) or only the AcmeDemoBundle?

**Comment by ProPheT777** [comment]
Everythings expect vendor folder, you can publish it on github or give me a zip. 

That will save me a lot of time if you do it :)

**Comment by gittix09** [comment]
Ok, I'll try.

**Comment by gittix09** [comment]
Done
https://github.com/gittix09/TestingGosWebSocket

**Comment by ProPheT777** [comment]
Thank you very much ! No problem for other part.

**Comment by ProPheT777** [comment]
I have update the docs, The problem come from the unsubscribe, calling publish then directly unsubscribe make the client bug.

https://github.com/gittix09/TestingGosWebSocket/blob/master/myproject/src/Acme/DemoBundle/Resources/views/Anntest/sock.html.twig#L37

The explication it's we unsubscribe while publish action is not ended. To fix this, client JS must be a bit rework to return a promise and execute unsubscribe only after publish action is finished.

**Comment by gittix09** [comment]
Great!! It seems to be working... almost.

    var myWebSocket = WS.connect("ws://localhost:8080");

         myWebSocket.on("socket/connect", function(session){
         //session is an Autobahn JS WAMP session.

            console.log("Successfully Connected!");

             //the callback function in "subscribe" is called everytime an event is published in that channel.
             session.subscribe("acme/channel", function(uri, payload){
                 console.log("Received message", payload.msg);
             });

             session.publish("acme/channel", {msg: "This is a message!"});

         });

         myWebSocket.on("socket/disconnect", function(error){
         //error provides us with some insight into the disconnection: error.reason and error.code

            console.log("Disconnected for " + error.reason + " with code " + error.code);

         });


This is wat I see in the browser console:
`2 Received message undefined`

The  `2` comes from the fact that each time a page is loaded `console.log("Received message", payload.msg);` is called two times (after subscribe action, and after publish action)

The problem is that I DON'T see the content of the message. From the code above, after the publish action I should see `Received message This is a message!`. But I get `undefined`

**Comment by ProPheT777** [comment]
I will take a look this evening

**Comment by gittix09** [comment]
Ok, thank you. Can't wait to see the complete bundle working. It's awesome ;)

**Comment by ProPheT777** [comment]
I fix and add come Q/A basic user can have about `Topic`

The error was the argument given to `broadcast()`, now he is compliant with client JS.

I hope my little Q/A will be usefull.

**Comment by gittix09** [comment]
Great!! These are really useful infos. Nice job ;)

I've created a pull request with some small bugfix

**Comment by gittix09** [comment]
With the changes in my pull request, I got it working. Here's an image of my own fully functional gos-chat app:
![gos_working_chat](https://cloud.githubusercontent.com/assets/4339303/6637066/2f815f2e-c976-11e4-962d-0bc76cc94dbc.jpg)
Of course it's just a demo =)

**Comment by ProPheT777** [comment]
Awesome :)

**Comment by gittix09** [comment]
Next step will be troubleshooting the "Session" part as in the documentation.
I'm closing this issue (it has become way too long and we have reached a working installation)

**Comment by ProPheT777** [comment]
I'm ready ! :)
