### ISSUE TITLE
Issue Symfony 2.8

### ISSUE THREAD

**Issue by dmorsoleto** [GeniusesOfSymfony/WebSocketBundle#100]
Hi.

I am trying to connect and send a message. But not works. In the terminal give me the error:

 websocket.ERROR: Connection error occurred Websocket router is not configured
 
what is it? 
Thanks

**Comment by CoalaJoe** [comment]
+1

**Comment by ProPheT777** [comment]
Hey, can you confirm that happened only for 2.8 version ?

**Comment by CoalaJoe** [comment]
Yes. But I got it to work. I forgot to make the routing.yml
