### ISSUE TITLE
99% CPU usage in Prod

### ISSUE THREAD

**Issue by Blacknet-es** [GeniusesOfSymfony/WebSocketBundle#102]
Good afternoon,

In the system we have generated two topics. One for notifications of messages and one for real-time auctions.

The operation is really good considering the topic of auctions performed very complex requests.

However, in many cases regardless of the work you are performing the overall cpu socket is at 100%.

any ideas to solve or optimize the operation?

Thank you!

**Comment by ProPheT777** [comment]
I have no idea, how many rpm on this action? It's very hard to say because it can from the traffic, the code in the process etc etc ... 

Are you using child process to delegate operation in another thread than the main loop?

**Comment by Blacknet-es** [comment]
This function executes every 15 seconds.

```
public function onUpdateNotifications(ConnectionInterface $connection, Topic $topic, WampRequest $request, $event, array $exclude, array $eligible)
    {
        $this->changeEnvironment($connection);

        $idDestinatario = $event['destinatario'];
        $destinatario = $this->em
            ->getRepository('AdministracionBundle:User')
            ->findBy(array('id' => $idDestinatario));

        // Obtenemos el número de mensajes y notificaciones nuevas
        $datos = $this->em
            ->getRepository('ItbidMensajesBundle:Mensaje')
            ->NotificationsData($destinatario[0]);

        $parameters = array(
            "messageCount" => $datos['count_messages'],
            "notificationCount" => $datos['count_notifications'],
        );
        $this->sendToAll($topic, "updateCounters", $parameters);
    }

```

**Comment by ProPheT777** [comment]
If the process take a lot of time it's problematic, React is non blocking and async but the doctrine is not, this is blocking the loop. 

If your script is taking something like 10sec you are processing all the time and blocking the rest of execution. You should delegate the task with react child process or async mysql client
