### ISSUE TITLE
Doctrine queries persistence

### ISSUE THREAD

**Issue by Blacknet-es** [GeniusesOfSymfony/WebSocketBundle#103]
Hello again,

Within a topic we have configured multiple queries through doctrine, consultations are always the same, however, should not always return the same data as these have changed in every request that is made to the topic.

I tried to use $ em->refresh($ entity) and works as long as the object is MANAGED but if I have an association MANY TO ONE these objects are not updated and are not MANAGED.

I also tried the $ em->clear() but this makes it all let work.

I do not know if the problem of doctrine or socket.

any ideas?

**Comment by ProPheT777** [comment]
Have you try to manually track object thought the relation instead of
letting doctrine doing internally? I'm not really able to answer your
question because I avoid to use doctrine in event loop :(
