### ISSUE TITLE
error when connecting to socket

### ISSUE THREAD

**Issue by fdydk** [GeniusesOfSymfony/WebSocketBundle#106]
when i run gos from command line successfully, then try to connect to channel from the browser the connection is terminated, and i get this exception in the terminal, any idea ?

 [Gos\Bundle\WebSocketBundle\Client\Exception\StorageException]  
  Driver Gos\Bundle\WebSocketBundle\Client\ClientStorage failed   
                                                                  
                                             
  [Predis\Connection\ConnectionException]    
  Connection refused [tcp://127.0.0.1:6379]

**Comment by ProPheT777** [comment]
connection refused means the address is not reachable nor the server reject you. Have you try to connect to your redis server from outside the websocket context (like in a conttroller, just hardcode the connection to try)

**Comment by fdydk** [comment]
thanks ,, it was because of redis, solved now

**Comment by ProPheT777** [comment]
no problem :)
