### ISSUE TITLE
TCP 80 port + Apache 80 port for gos:websocket:server

### ISSUE THREAD

**Issue by eduardo5000** [GeniusesOfSymfony/WebSocketBundle#108]
I'm working in a Company that there are users in a closed network and other users in others buildings that access that network with routers, firewalls, ....

I have launched the gos:websocket:server in port 8090 and for the users inside that network works perfectly.

The problem comes when a user in other building try to connect at 8090 port. They can't connect.

Is there the posibility to use and udp port? They have opened the 80 port. Although we don't know if they have the 80 udp port opened.

The best solution would be using tcp 80 port, but apache server is listening in that port.

Is there the posibility to share tcp 80 port with apache and gos:websocket:server command?

Thank you !

Sorry for my english ;-)

**Comment by ProPheT777** [comment]
Depend of your company, but may be firwall block 8090. UDP is not possible, because of Javascript via the browser, the alternative is webRTC but it's another thing completely different and not adapted for this need. 

> Is there the posibility to share tcp 80 port with apache and gos:websocket:server command?

Yes it's possible but not at application level. You should use proxy pass to achieve that. 

```conf
<VirtualHost *:80>
  ServerName domain.com

  <Location "/ws">
    ProxyPass "ws://localhost:8090/"
  </Location>
</VirtualHost>
```

**Comment by eduardo5000** [comment]
I'll try and tell you !

Thx !

**Comment by eduardo5000** [comment]
In dev env it works. I just need try it in prod, but I think it'll work.

It's necessary enable **mod_proxy_wstunnel.so** and **mod_proxy.so** in **httpd.conf**:

**LoadModule proxy_module modules/mod_proxy.so**
**LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so**

In **virtualhost**:

   **<Location "/wsauthoban">
            ProxyPass "ws://localhost:8090/"
   </Location>**

In client **js **connection to** ws (handshake)**:

**WS.connect("ws://{{ gos_web_socket_server_host }}/wsauthoban"**

That is to say you could use **wsauthoban or any other** what you want.

That's all folks ! ;-)

**Comment by eduardo5000** [comment]
Ok. Yes !!

It works ! 

Thank you !
