### ISSUE TITLE
change received message format on connect

### ISSUE THREAD

**Issue by fdydk** [GeniusesOfSymfony/WebSocketBundle#110]
Hello, on connect this message is received [0,"158085103156d3f61a412dd975365278",1,"Ratchet\/0.3.3"]

can I change its format to json?

**Comment by ProPheT777** [comment]
On wich side you receive that?

**Comment by CoalaJoe** [comment]
This is the connection header when connecting to the websocketserver. You can then just send a JSON formated string from your server and then parse it.
