### ISSUE TITLE
Catch error connection

### ISSUE THREAD

**Issue by matthieuy** [GeniusesOfSymfony/WebSocketBundle#117]
Hi,

How to catch error connection on the client side if the websocket server don't run ?
I try this but don't work :
```javascript
try {
    var socket = WS.connect(WS_URI);
    // socket.on[...]
} catch (e) {
    console.log('Error', e);
}
```

**Comment by arckdash** [comment]
Hi, I hope help you.

I can see this:
var websocket = WS.connect("ws://127.0.0.1:8080");
websocket.on("socket/connect", function(session){
   console.log("Successfully Connected!");
})

websocket.on("socket/disconnect", function(error){
        //error provides us with some insight into the disconnection: error.reason and error.code

        console.log("Disconnected for " + error.reason + " with code " + error.code);
    })


When you try to connect to the off server , "socket/disconnect" is executed and it's callback function the error.code is **3**

So... I think you can do something like this:

websocket.on("socket/disconnect", function(error){
        //error provides us with some insight into the disconnection: error.reason and error.code
       if(error.code === 3) {
           alert("The server is not running");
           console.log("Disconnected for " + error.reason + " with code " + error.code);
       }
    })

**Comment by matthieuy** [comment]
@arckdash : Thanks, it work
