### ISSUE TITLE
Connection error occurred Websocket router is not configured

### ISSUE THREAD

**Issue by arckdash** [GeniusesOfSymfony/WebSocketBundle#118]
Hi, I try to implement this in a project, but I've the console error:
**Connection error occurred Websocket router is not configured**

this is my configuration:

// **app/config/config.yml**
`
// Web Socket Configuration
gos_web_socket:
    server:
        port: 8080        
        host: 127.0.0.1
        router:
            resources:
                - @AutogestionBundle/Resources/config/pubsub/routing.yml
`
// **AutogestionBundle/Resources/config/pubsub/routing.yml**
`
connections_topic:
    channel: class/connections/channel
    handler:
        callback: 'autogestion.class.students.connection'
`
// **AutogestionBundle/Topic/ConnectionTopic.php**
`
    public function getName()
    {
        return 'autogestion.class.students.connection';
    }
`

// **file.html.twig**
`
var channel = "class/connections/channel";
console.log("Successfully Connected!"); // This work fine.

// In this Line occurred the error mentioned
session.subscribe(channel, function(uri, payload){ 
            console.log("Received message", payload.msg);
        });

        session.publish(channel, {msg: "This is a message!"});

        session.unsubscribe(channel);

        session.publish(channel, {msg: "I won't see this"});
`
can someone help me?

I sorry for the unIdented code, but I don't know how do it! :S

Thanks! :)

**Comment by ProPheT777** [comment]
A bit of search 

- https://github.com/GeniusesOfSymfony/WebSocketBundle/issues/100
- https://github.com/GeniusesOfSymfony/WebSocketBundle/issues/88
- https://github.com/GeniusesOfSymfony/WebSocketBundle/issues/13

There are solved btw but if your problem persist, ask me again

**Comment by arckdash** [comment]
I think the problem was I forget clean the cache, because now it seems work, but I had other problem now! 
Also I add ' ' to the rout for the routing like this:
**'@AutogestionBundle/Resources/config/pubsub/routing.yml'**

In the command console throw:

- Matched route "connections_topics"
- Get Client 504
- Connection error occurred Topic **autogestion.class.students.connection** does'nt exist in [ ]

I think it means that I don't add the topic in the config.yml file ?

**Comment by ProPheT777** [comment]
you must add a tag on your topic service in the definition or manually in the config

https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/TopicSetup.md#step-2-register-your-service-with-symfony

**Comment by arckdash** [comment]
I'm doing this:

//AutogestionBundle/Resources/config/services.yml

services:
    autogestion.students_connections:
        class: AutogestionBundle\Topic\ConnectionTopic
        tags:
            - { name: gos_web_socket.topics }

And in the file: **config.yml**
gos_web_socket:
    server:
        port: 8080        #The port the socket server will listen on
        host: 127.0.0.1   #The host ip to bind to
        router:
            resources:
                - '@AutogestionBundle/Resources/config/pubsub/routing.yml'
    topics:
        - @autogestion.students_connections

There is something wrong ?
I can't see the error :S

In the services file the tag name is: 
- **gos_web_socket.topics**
and in the config.yml file is:
- topics

This is right ?

**Comment by ProPheT777** [comment]
Choose one solution not both ;) Use tag declaration or in config.yml declaration. I suggest you tag, it's more simple and need less refactoring in case of you change something.

**Comment by arckdash** [comment]
YES!!!! Thanks so much!!! :D

the solution was use only a declaration and clean the cache and stop and run again the server! :D

But ... xD

I've other question.

in the twig file I've this:

websocket.on("socket/connect", function(session){
        //session is an Autobahn JS WAMP session.
        var channel = "class/connections/channel";

        console.log("Successfully Connected!");
        session.subscribe(channel, function(uri, payload){
            console.log("Received message", payload.msg);
        });

        session.publish(channel, {msg: "This is a message!"});

        session.unsubscribe(channel);

        session.publish(channel, {msg: "I won't see this"});
    })

but in the javascript console, only I see the "Successfully Connected!" message, I don't should saw:
"This is a message!" message too ?

**Comment by ProPheT777** [comment]
when you publish, you publish on server side, so yeah it's normal. Bug if you echo the message in the topic you'll see it appear in the server console

**Comment by ProPheT777** [comment]
And you'll have to restart the server each time you done something in the server side code to take effect.

**Comment by arckdash** [comment]
Great! :D Thanks so much for your help, and thanks for be patient with me! :)
