### ISSUE TITLE
how to send message/notification from any controller

### ISSUE THREAD

**Issue by arckdash** [GeniusesOfSymfony/WebSocketBundle#119]
Hi again! :P

I've a question may be I don't undestand so much how this work, but is possible send notification from any controller to the client side ?

If the answer is yes, how I can do it ?

I did a little search for this, but i can't find just I think I need.

I mean I've this:

class ApiController extends Controller
{

public function testAction(Request $request)
{
        $connectionTopic = $this->get("autogestion.students_connections");
        $connectionTopic->onPublish(ConnectionInterface $connection, Topic $topic, WampRequest $request, $event, array $exclude, array $eligible)
}

      $response = new Response( json_encode(array( "result"=> 200, "message" => "success"  )) );
      $response->headers->set('Content-Type', 'application/json');
      return $response;

} // end controller

From a Controller, how I can get:
- ConnectionInterface $connection
- Topic $topic
- WampRequest $request
- $event
- array $exclude
- array $eligible

I hope you can help me! :)

**Comment by ProPheT777** [comment]
everything is documented : https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/Pusher.md

**Comment by arckdash** [comment]
great thanks! now i going to see

**Comment by arckdash** [comment]
Ok, I reed all the document, and I've a question :P

Is need to have installed all of them (zmq, AMQP) ?

Because, I only have installed and configurated zmq and when i try to send a push message in the command console I get:
- websocket.DEBUG: Matched route "connection_topic"
- websocket.INFO: Pusher zmq has pushed {"provider":"zmq", "topic":"class/connection/channel"}
- websocket.ERROR: AMQP handler failed to ack message {"exception_message:" "Topic autogestion.class.students.connection doesn't suppor push feature", "file":"........\gos\......App\Dispatcher\TopicDispatcher.php", "line":152, .....}

This is my code:
controller class:
try {
            $pusher = $this->container->get('gos_web_socket.zmq.pusher');
            //push(data, route_name, route_arguments)
            $pusher->push(['my_data' => 'data'], 'connections_topic', array());
            
            $result = array( "result" => 200, "msj"=> "success" );
        }catch(Exception $e) {
            $result = array( "result" => 400, "msj"=> "fail . \n" . $e->getMessage() );
        }

        $response = new Response(json_encode($result));
        $response->headers->set('Content-Type', 'application/json');
        return $response;

Thanks for help me! :)

**Comment by matthieuy** [comment]
Do you use ZMQ or AMQP ?
The "`ConnectionInterface`", "`Topic`",... objects aren't be in the Controller but in the Topic service !

- Topic service receive data from client or controller.
- Controller can push data to topic !

So if you want send notification from controller to client side, you must use this way : controller => topic service => client

**Comment by arckdash** [comment]
Only I've installed ZMQ.

I thought that I can do this:
$pusher = $this->container->get('gos_web_socket.zmq.pusher');
$pusher->push($data, $route_name, $route_arguments);

When $route_name is the route where is my topic class (ConnectionTopic).

But when I do push, I get the error mentioned above! :S

**Comment by matthieuy** [comment]
Your `ConnectionTopic` class must implements `TopicInterface` **AND** `PushableTopicInterface` !

After that, use "`onPush`" method in your topic class to receive data from your controller and send it to client : 
```php
public function onPush(Topic $topic, WampRequest $request, $data, $provider)
{
    // Send to all clients in this topic
    $topic->broadcast($data);
}
```

**Comment by arckdash** [comment]
xD

It's work!!! :D

Thanks a lot man!!!

**Comment by ProPheT777** [comment]
ty @matthieuy :)
