### ISSUE TITLE
Rename Bundle

### ISSUE THREAD

**Issue by YuriyKvit** [GeniusesOfSymfony/WebSocketBundle#120]
Can not use socket in bundle where name different from **'AppBundle**'. Why this may happend?

**Comment by ProPheT777** [comment]
What? The bundle name is "GosWebSocketBundle" https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/GosWebSocketBundle.php#L19

So there is no conflict with other bundle name. I'm not sure to really understand you but it's weird. 

Have you follow the installation process here : https://github.com/GeniusesOfSymfony/WebSocketBundle#step-2-add-to-your-app-kernel

**Comment by YuriyKvit** [comment]
With **GosWebSocketBundle** all okay, I mean my bundle name for example **ChatBundle** Server starting ok, but when i connect to server i got error like "topic not found". But when i rename bundle to **AppBundle** All work good. 

Here some link to project [https://bitbucket.org/asmoria/symfony-2/src/1d24001134f3ed52f9ce8b7099e4ec1dbb156fae/src/ChatBundle/?at=socket](url)

**Comment by ProPheT777** [comment]
Yes if you rename AppBundle you have to refator many things like the configuration, namespace, routing,  and resources.

Things like that :

**Comment by YuriyKvit** [comment]
I remember about this things im looking for what i missed but cant find

Thanks for responce :)

**Comment by YuriyKvit** [comment]
Yeah, but bundle wich use sockets named ChatBundle, and all configs: routing, namespaces configured.

Sorry if annoying.

**Comment by rvanlaak** [comment]
This is no bug/issue related to this bundle, maybe StackOverflow can help you a bit faster.

**Comment by YuriyKvit** [comment]
Yes, you right, close this one. Thanks for responce.
