### ISSUE TITLE
Guzzle dependencies abandoned?

### ISSUE THREAD

**Issue by Lube** [GeniusesOfSymfony/WebSocketBundle#121]
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.

**Comment by ProPheT777** [comment]
yeah, that just mean it's not maintained anymore but still available.

When ratchet release v0.4 that will be fixed.
