### ISSUE TITLE
PHP7 Compliant?

### ISSUE THREAD

**Issue by janek2012** [GeniusesOfSymfony/WebSocketBundle#124]
Is this bundle 100% PHP7-compliant? It would be nice to mention it if it is :)

**Comment by ProPheT777** [comment]
I don't know, but I think, ratchet work under PHP7 without trouble, and all potential code that can be not compatible are here, so I think

**Comment by Venzon** [comment]
@janek2012 we are atm testing bundle and application which is using it under php7 - works fine for now

**Comment by Venzon** [comment]
I can confirm that all works fine under php7

**Comment by CoalaJoe** [comment]
Works aswell for me.

I think we can close this issue.
