### ISSUE TITLE
pcntl_sigtimedwait function cannot callable in macos

### ISSUE THREAD

**Issue by lamjack** [GeniusesOfSymfony/WebSocketBundle#125]
:) could u add a callable checker in Gos\Bundle\WebSocketBundle\Event\StartServerListener line 95?

**Comment by lamjack** [comment]
```bash
php -r 'var_dump(PHP_VERSION,is_callable('pcntl_sigtimedwait'),is_callable('pcntl_signal'));'
```

string(5) "7.0.4"
bool(false)
bool(true)

**Comment by ProPheT777** [comment]
Ok why not, I just need to figure out the problem. Following the official docs http://php.net/manual/fr/function.pcntl-sigtimedwait.php is working on PHP7. May be it's a problem with pcntl extension under PHP7

**Comment by lamjack** [comment]
got it.
pcntl_sigtimedwait() is unavailable (under Mac OS, under PHP < 5.3), so could you pick up this code on the workaround,
```php
if (!function_exists('pcntl_sigtimedwait')) {
    function pcntl_sigtimedwait($signals, $siginfo, $sec, $nano)
    {
        pcntl_signal_dispatch();
        if (time_nanosleep($sec, $nano) === true) {
            return false;
        }
        pcntl_signal_dispatch();
        return true;
    }
}
```

**Comment by ProPheT777** [comment]
yes, I'm going to add this polyfill. Thank you @lamjack

**Comment by lamjack** [comment]
@ProPheT777 welcome

**Comment by ProPheT777** [comment]
Polyfill was added https://github.com/GeniusesOfSymfony/PNCTLEventLoopEmitter/commit/ac341050dd26bd920047609126f8f62cc4098323

You can update via composer :)
