### ISSUE TITLE
Bundle not working with doctrine-migration

### ISSUE THREAD

**Issue by sgorshkov** [GeniusesOfSymfony/WebSocketBundle#126]
If add doctrine-migration and websocketbundle to the same project everything broke with error
`Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to GosBundleWebSocketBundleServerTypeWebSocketServer_000000000638351a0000000029ad6f0fb4098278b46fb6638ff99d1352b3ce13::__construct() must be an instance of React\EventLoop\LoopInterface, instance of Closure given, called in /Users/project/app/cache/dev/appDevDebugProjectContainer.php on line 8577 in /Users/project/app/cache/dev/appDevDebugProjectContainer.php:10482
`

It can be tested with adding doctrine-migration to composer.json of WebsocketAppDemo:
 
```
"doctrine/migrations": "1.4.1",
"doctrine/doctrine-migrations-bundle": "1.1.1"
```

**Comment by matthieuy** [comment]
I use doctrine-migrations-bundle (v1.1.1) and WebSocketBundle (v1.7.0) without problem !

What do you do exactly ?
I try this :
```
git clone https://github.com/GeniusesOfSymfony/WebsocketAppDemo.git demo
cd demo
composer install
composer require doctrine/migrations  1.4.1
composer require doctrine/doctrine-migrations-bundle 1.1.1
php app/console server:start
php app/console gos:websocket:server
```
And I open http://127.0.0.1:8000/app/example with success

Maybe [open a issue on WebsocketAppDemo](https://github.com/GeniusesOfSymfony/WebsocketAppDemo/issues)

**Comment by CoalaJoe** [comment]
I think this issue can be closed aswell.
