### ISSUE TITLE
how to install zmq in Centos 

### ISSUE THREAD

**Issue by arckdash** [GeniusesOfSymfony/WebSocketBundle#128]
Hi everyone, I'm trying to install my system with this bundle in a linux centos 7 server, but I've problems with the zmq extension, I don't know how i can install it in the OS.

I did saw many tutorials that explain how to install it, but when i want to run the command: composer update over my directory project I get the following:

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/zmq.so' - /usr/lib64/php/modules/zmq.so: cannot open shared object file: No such file or directory in Unknown on line 0

Can someone help me please ? :(

Thanks!

**Comment by ProPheT777** [comment]
zmq php extension is just a binding between c lib and php so you need to install this package http://zeromq.org/distro:centos and let him installed on server. So if you compile php by your own, you must keep this dependency even after compiled php.

**Comment by arckdash** [comment]
Thank you!! :D
