### ISSUE TITLE
FatalErrorException in PdoSessionHandler.php line 513

### ISSUE THREAD

**Issue by hermandinho** [GeniusesOfSymfony/WebSocketBundle#138]
Hello,

please i have trouble with this bundle. In configured everything well, when user logs in all whenever i reload the page, i alwas have 

`FatalErrorException in PdoSessionHandler.php line 513:
Error: Maximum execution time of 30 seconds exceeded`.

can anyone figure out what's wrong? 

regards.

**Comment by hermandinho** [comment]
@ProPheT777 please can you help me figure out this issue?

**Comment by hermandinho** [comment]
figured it out. clossing.

**Comment by ProPheT777** [comment]
Sorry for the delay I was in holiday :/ happy to see that you solved it :)
