### ISSUE TITLE
Invoke service in PeriodicInterface

### ISSUE THREAD

**Issue by hermandinho** [GeniusesOfSymfony/WebSocketBundle#139]
Please is it possible to access services form a Periodic Service Class? I tried :

`
class ChatPeriodic extends Controller implements PeriodicInterface
{
    /**
     \* Function excecuted n timeout.
     */
    public function tick()
    {
        $topic = $this->get("application_forms.services.chat_topic");
        //$topic->broadcast(['msg' => "form tick"]);
        echo "Run after : ".$this->getTimeout()." seconds ".PHP_EOL;
    }

```
/**
 * @return int (in second)
 */
public function getTimeout()
{
    // TODO: Implement getTimeout() method.
    return 5;
}
```

}
`
but seems not to work. any ideas?
Regards

**Comment by hermandinho** [comment]
@ProPheT777 and for this issue, is there a way to manage out?

Regards

**Comment by ProPheT777** [comment]
Yes you can, just inject your services via the symfony DI and retrieve it trought $this directly in your function

**Comment by hermandinho** [comment]
ok. thanks. Will try that

**Comment by hermandinho** [comment]
i will be happy if you could provide me a quick configuration for achieving this :(
