### ISSUE TITLE
Unrecognized option "router" under "gos_web_socket.server"

### ISSUE THREAD

**Issue by KrissMcCone** [GeniusesOfSymfony/WebSocketBundle#14]
Hello. I've tried to add RPC(https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/RPCSetup.md) and I had error: Unrecognized option "router" under "gos_web_socket.server"

My config:

# Web Socket Configuration
gos_web_socket:
    server:
        port: 8080        #The port the socket server will listen on
        host: 127.0.0.1   #The host ip to bind to
        router:
            resources:
                - @AppChatBundle/Resources/config/pubsub/routing.yml

**Comment by ProPheT777** [comment]
Check your composer.json to be sure to have the lastest version.

You should have something like this :  ` "gos/web-socket-bundle": "~1.0"` then composer update. 

You also can refer to the demo app https://github.com/GeniusesOfSymfony/WebsocketAppDemo but it work so I thing you haven't the lastest version ;)

**Comment by KrissMcCone** [comment]
Hello. Thanks for help!

I removed @dev before ~1.0 and it removed my error.

Now i have the same error as our friend:

https://github.com/GeniusesOfSymfony/WebSocketBundle/issues/13

Unfortunately, updates didn't help me. 

Thanks once again!

**Comment by ProPheT777** [comment]
Have your register PubSubRouter in your appKernel ? 

```yaml
<?php
// app/AppKernel.php

public function registerBundles()
{
    $bundles = array(
        // ...
        new Gos\Bundle\WebSocketBundle\GosWebSocketBundle(),
        new Gos\Bundle\PubSubRouterBundle\GosPubSubRouterBundle(),
    );
}
```

If you come from **@dev** have you follow upgrade guide from **@dev** to stable version ? If no look at "Upgrade guide" post in  https://github.com/GeniusesOfSymfony/WebSocketBundle/pull/6

**Comment by KrissMcCone** [comment]
Yes, I forgot about PubSubRouterBundle, thank you! :)
