### ISSUE TITLE
dynamic routes

### ISSUE THREAD

**Issue by techsot** [GeniusesOfSymfony/WebSocketBundle#142]
i want to render a var into to twig to push it in channel 
my controller
 `$pusher = $this->container->get('gos_web_socket.zmq.pusher');
            $pusher->push(['my_data' => 'data'], 'notification_topic', ['id' => $notify->getId()]);`

pubsub routing.yml 
`notification_topic:
    channel: notif/{id}
    handler:
        callback: 'Notification.topic' #related to the getName() of your topic
    requirements:
        id:
            pattern: "\d+"
            wildcard: true
`
my topic : 
`class NotificationTopic implements TopicInterface, PushableTopicInterface
{

```
/**
 * @param Topic        $topic
 * @param WampRequest  $request
 * @param array|string $data
 * @param string       $provider The name of pusher who push the data
 */
public function onPush(Topic $topic, WampRequest $request, $data, $provider)
{
    $topic->broadcast($data);
}....
```

`
cote client : 
`                var websocket = WS.connect("ws://127.0.0.1:8080");
                websocket.on("socket/connect", function(session){
                    console.log('socket connected');
var channel ="notif/"+ id ;
console.log(channel);
                    session.subscribe(channel, function(uri, data){
                        console.log("Received message");
                    });
`
in my console i got 
`socket connected 
Uncaught ReferenceError: id is not defined`

**Comment by matthieuy** [comment]
In the client side, where do you declare the variable `id` ?
Try that : 
```javascript
//...
var id = '1';
var channel ="notif/"+ id ;
console.log(channel);
//...
```

**Comment by techsot** [comment]
` var websocket = WS.connect("ws://127.0.0.1:8080");
                websocket.on("socket/connect", function(session){
                    console.log('socket connected');
                    var channel ="notif/"+ id ;
                    console.log(channel);
                    session.subscribe(channel, function(uri, data){
                        console.log("Received message"); `
her is my client side

**Comment by matthieuy** [comment]
The error `Uncaught ReferenceError: id is not defined` said you don't declare your `id` variable and i don't see the declaration in your code ! Something like : 
```javascript 
var id = "1" // Declare ID var
```

**Comment by techsot** [comment]
what i'm trying to is a notification system like facebook system but i really find many difficult , any help ? i get an entity notification and publication , when a user create publication , i create a new object of my entity notification where the sender is the curent user and the reciever is others user ( not all users some specific ones , i want to use websocket where the atribut reciever is the same id as the curent user i call notify plugin to show notification to my user ? any help how to create that ?
