### ISSUE TITLE
Is it possible to not use gos_web_socket_client.js and autobahn.min.js ?

### ISSUE THREAD

**Issue by mrbinr** [GeniusesOfSymfony/WebSocketBundle#144]
Hi,
I've tried to use https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/ClientSetup.md + Push Notification and it work fine, but now i would like to know if it's possible to use Native Javascript WebSocket instead Javascript in this example ?

When i try, i can connect to websocket server, but cannot have push notification ...

Any idea ?

Thanks for your help

Best Regards

Pascall

**Comment by ProPheT777** [comment]
hello, yes, you can use all lib or create your own but you have to follow the wamp v1 protocol to make it work together. 

Here is the spec : https://tools.ietf.org/html/draft-oberstet-hybi-tavendo-wamp-01

**Comment by mrbinr** [comment]
@ProPheT777 Thanks for your answer and the spec, i will explore this solution :)

Best Regards
Pascall

**Comment by ProPheT777** [comment]
You can use this kind of library for example https://github.com/KSDaemon/wampy.js

**Comment by ivanstan** [comment]
I'm trying to use a new version of autobahn.js? What should be my realm?

**Comment by Sybio** [comment]
Could be great to explain how to configure the realm ! I can't find a solution :s

**Comment by fnash** [comment]
@ivanstan @Sybio realm is for WAMP v2
