### ISSUE TITLE
SIGTERM isn't being processed correctly

### ISSUE THREAD

**Issue by mbabker** [GeniusesOfSymfony/WebSocketBundle#146]
Trying to kill the websocket server via `CTRL-C` isn't correctly shutting things down, I'm having to give a `kill -9` on my local system.

Sysinfo:
OS X 10.10.5
PHP 7.0.6 installed via Homebrew with pcntl support
```sh
Configure Command =>  './configure'  '--prefix=/usr/local/Cellar/php70/7.0.6' '--localstatedir=/usr/local/var' '--sysconfdir=/usr/local/etc/php/7.0' '--with-config-file-path=/usr/local/etc/php/7.0' '--with-config-file-scan-dir=/usr/local/etc/php/7.0/conf.d' '--mandir=/usr/local/Cellar/php70/7.0.6/share/man' '--enable-bcmath' '--enable-calendar' '--enable-dba' '--enable-exif' '--enable-ftp' '--enable-gd-native-ttf' '--enable-mbregex' '--enable-mbstring' '--enable-shmop' '--enable-soap' '--enable-sockets' '--enable-sysvmsg' '--enable-sysvsem' '--enable-sysvshm' '--enable-wddx' '--enable-zip' '--with-freetype-dir=/usr/local/opt/freetype' '--with-gd' '--with-gettext=/usr/local/opt/gettext' '--with-iconv-dir=/usr' '--with-icu-dir=/usr/local/opt/icu4c' '--with-jpeg-dir=/usr/local/opt/jpeg' '--with-kerberos=/usr' '--with-libedit' '--with-mhash' '--with-ndbm=/usr' '--with-pdo-odbc=unixODBC,/usr/local/opt/unixodbc' '--with-png-dir=/usr/local/opt/libpng' '--with-unixODBC=/usr/local/opt/unixodbc' '--with-xmlrpc' '--with-zlib=/usr' '--with-readline=/usr/local/opt/readline' '--without-gmp' '--without-snmp' '--with-apxs2=/usr/sbin/apxs' '--libexecdir=/usr/local/Cellar/php70/7.0.6/libexec' '--with-bz2=/usr' '--disable-debug' '--with-openssl=/usr/local/opt/openssl' '--enable-fpm' '--with-fpm-user=_www' '--with-fpm-group=_www' '--with-curl' '--with-xsl=/usr' '--with-mysql-sock=/tmp/mysql.sock' '--with-mysqli=mysqlnd' '--with-mysql=mysqlnd' '--with-pdo-mysql=mysqlnd' '--disable-opcache' '--enable-pcntl' '--without-pear' '--enable-dtrace' '--disable-phpdbg' '--enable-zend-signals' 'CC=clang' 'CXX=clang++'
```

![screen shot 2016-05-06 at 10 36 21 am](https://cloud.githubusercontent.com/assets/368545/15077947/7afad0d4-1376-11e6-9e2d-568bc16bc173.png)

**Comment by ProPheT777** [comment]
Have you something blocking the I/O loop? 

It show the pcntl dispatch take a long time to be call.

**Comment by mbabker** [comment]
Not that I know of.  Everything else with the socket server works just fine, it's just issuing SIGTERM that acts up.

**Comment by ProPheT777** [comment]
To be honest I have no clue, on my linux I don't have this problem, I don't know if it's related to the host (I pretty sure that not) or pcntl event binding. 

The weird things, why he can catch the first occurrence and block after ... If it's problematic.

Have try 2 constitutive kill in command line?

**Comment by ProPheT777** [comment]
We can delete the "double tocuh" if it's problematic, I don't see any benefit on that feature so ...

**Comment by mbabker** [comment]
I haven't the slightest clue either, I just know for whatever reason it's acting funny.  Could be the Homebrew PHP install, could be me missing something obvious, could be my system using the `pcntl_sigtimedwait()` polyfill and it not matching the `SIGINT === pcntl_sigtimedwait([SIGINT], $siginfo, 5)` check since the polyfill is returning boolean values.

**Comment by ProPheT777** [comment]
The polyfill return is not good you are true, from the official doc 

> On success, pcntl_sigtimedwait() returns a signal number.

**Comment by mbabker** [comment]
At a glance I'd say there's an issue with the polyfill needing some improvements and the source install for Homebrew PHP not adding all the expected functions (below is a dump of everything PHP has defined in the pcntl namespace, notice missing is `pcntl_sigtimedwait()`).

![screen shot 2016-05-06 at 11 21 04 am](https://cloud.githubusercontent.com/assets/368545/15079198/af2b0846-137c-11e6-84a1-a67839941782.png)

**Comment by mbabker** [comment]
Either way at this point I think this can be closed as a non-issue in the websocket bundle.  Seems there are environmental factors at play here beyond what can be controlled here.  At best, improvements in the polyfill might address some of those.

**Comment by ProPheT777** [comment]
I think the more simple way is to remove this feature, there is no benefit to implement that at library level (and , let the user protect this method on the top of the lib is a better option (and in 99% I think this protection is useless)
