### ISSUE TITLE
WebSocket connection randomly fails in browser

### ISSUE THREAD

**Issue by mwsv** [GeniusesOfSymfony/WebSocketBundle#148]
I use this great bundle in the project, which I'm currently working on and I spent the whole day on trying to resolve a weird issue. I have this project deployed on some accessible web server and I tried to run it on about 15 workstations - on the most of them (different browsers, mostly in the newest versions) it works absolutely fine, I have no problem with connecting to the WS server, while in three cases I see in browser console below message:

`console.log: WebSocket connection to 'ws://someproject.com:12345/' failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1`

And it appears in all browsers on these three machines, while at the same time there's no such message in any browser on the other computers, even in cases when the computer has the same operating system and the same browser versions as the "failing" machine. When I open "Network" tab in Chrome developer tools and I click on the web socket connection, I see in "Frames" tab also message "(Opcode -1)" in data column. From the WS backend point of view there's new message: 

`websocket.DEBUG: GET CLIENT 1940`

...however automatically for some reason something also disconnects this user: 

`websocket.DEBUG: REMOVE CLIENT 1940`

It seems also, that onSubscribe method does not fire in this case. I would appreciate any help and tips how can I debug or resolve this problem or which are the possible reasons of such error appearing in random cases, it was really dificult to find any useful informations in other sources.

**Comment by ProPheT777** [comment]
Are you on windows?

**Comment by mwsv** [comment]
Yes, the problem was caused by some ESET NOD32 update, adding IP addresses to exclude list worked.
