### ISSUE TITLE
Functional Testing

### ISSUE THREAD

**Issue by novacp** [GeniusesOfSymfony/WebSocketBundle#152]
How is it possible to functional test the websocket?
Assuming the following scenarios:

**First Test:** Check, if user could connect successfully to websocket server. Therefore, I only allow authenticated users to do so, if not, I disconnect them the following way in EventListener:
`
public function onClientConnect(ClientEvent $event)`
    `{`
        `$connection = $event->getConnection();`
        `$user = $this->clientManipulator->getClient($connection);`

```
    if(is_string($user) || !$user)
    {
        $connection->close();
    }
`}`
```

I've tried to write a test for getting blocked and getting access to the websocket. Thereforce, I found the "Gos\Component\WebSocketClient\Wamp\Client" class:

`$client = new Client('127.0.0.1', 80);`
`$client->connect();`

How can I check now, if the connection was successful or if the user s connection got closed? How can I authenticate a user in this scenario? I tried by sending a cookie with the session id of an authenticated user, but client connect will always return null.

**Second Test:** Check, if user has permission to access a channel. Therefore, I allow every user to access only his own channel with name "/notification/{userid}. Then in onsubscribe method, I check if the user has access and if not, I remove his connection from the topic immediatly. When it comes to writing the test, I don't know how to subscribe a user in a test to a topic and check if he got removed or not.

-- I think these tests are very important, but I couldn't find anything on the internet about it.

**Comment by ProPheT777** [comment]
You can test in that way for example :

```php
public function testCanConnect()
    {
        \Ratchet\Client\connect('ws://127.0.0.1:8080')->then(function($conn) {
            $conn->on('message', function($msg) use ($conn) {
                print $msg."\n";
                $this->assertEquals('true',true);
                $this->assertEquals("Hello World",$msg);
                $conn->close();
            });
            $conn->send('Hello World!');
        }, function ($e) {
            echo "Could not connect: {$e->getMessage()}\n";
        });
    }
```

**Comment by novacp** [comment]
No, I already tried. This is asynchronous and I cannot cover the scenarios. What if the user should get logged out ("on close event"), but the event is never hit? Then the assert in it will also never been hit, and the whole test is nonsene.

**Comment by novacp** [comment]
I still could not find a solution for 1) and 2). Any news?

**Comment by welcoMattic** [comment]
I'm interested in too. Is there any "best" way to do functional testing of the websocket?

**Comment by novacp** [comment]
As I could inform now in the internet, no one knew how to authenticate a user within a functional test and or subscribe a user then to a topic. Any idea of the bundle collaborators? This is really blocking TDD / BDD when it comes to Websockets .
