### ISSUE TITLE
How to start the server in background and stop/restart when needed ?

### ISSUE THREAD

**Issue by alok0590** [GeniusesOfSymfony/WebSocketBundle#153]
I'm able to start the server using
**php app/console gos:websocket:server**

But it prints the output on console, how can we run this in background ? And Is there any way to start/stop the server when needed?

**Comment by matthieuy** [comment]
`php app/console gos:websocket:server &`
or see #129 (use `disown` command)

**Comment by alok0590** [comment]
I know we can do that using **&**, but how can I stop/restart the server after exiting from the terminal? I want to deploy it in production.

**Comment by byhoratiss** [comment]
Maybe you can think in something like [supervisord](http://supervisord.org/) in production.

Look [this](http://jmsyst.com/bundles/JMSJobQueueBundle/master/installation#setting-up-supervisord), will give you the idea.

**Comment by CoalaJoe** [comment]
This issue can be closed
