### ISSUE TITLE
WebSocket push, stop broadcasting

### ISSUE THREAD

**Issue by valcloup** [GeniusesOfSymfony/WebSocketBundle#156]
I tried to send data to user by using WebSocket push.
The fact is, if at any moment, the onPublish did'nt work well, the websocket server automatically send the push data to all the user connected.

Moreover, I tried to just remove the line (OnPublish method)

`$topic->broadcast($dataPush,[],[]);`

Also try to add
`return;`

But in any case, all user connected get the data push by the method 

`this->pusher->push([$data],"NotificationCenter_topic", []);`

So, how can i stop the server to send any data after a push in certain case ?

**Comment by novacp** [comment]
You're in the wrong method, use onPush -method of you pusher and just call return; ..

**Comment by valcloup** [comment]
Thanks for the answer.

When using Websocket push, the OnPush is'nt called.

see Note 2 : 
https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/Pusher.md#websocket-pusher

**Comment by novacp** [comment]
Okay, as mentioned in the docs, you should use another pusher than Websocket pusher because it has a lot of overhead - or choose another way of using them.

**Comment by ProPheT777** [comment]
When you use the websocket pusher we rely directly on wamp protocol so
onPublish is call. All other pusher use onPush method. And yes websocket
pusher have a high cost due to handshake when we connect.
