### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by abner01061998** [GeniusesOfSymfony/WebSocketBundle#157]
i need an example of chat and notification with gos , some one ?

**Comment by CoalaJoe** [comment]
Are you still in need?

**Comment by abner01061998** [comment]
I dont know how to make a notification sistem with database , so you have an example ?

Obtener Outlook para Android<https://aka.ms/ghei36>



On Thu, Sep 15, 2016 at 8:35 AM -0600, "Ashura" <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you still in need?

-

**Comment by CoalaJoe** [comment]
Do you mean push notifications or notifications on a website?

**Comment by abner01061998** [comment]
I mean push notifications and ... show to users.

Obtener Outlook para Android<https://aka.ms/ghei36>



On Thu, Sep 15, 2016 at 11:31 PM -0600, "Ashura" <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you mean push notifications or notifications on a website?

-

**Comment by CoalaJoe** [comment]
How are your Symfony and PHP skills? I only see some rather empty repositories on your account.

**Comment by abner01061998** [comment]
80% of skills in each one i have no repos in this accoun only in the work account

Obtener Outlook para Android<https://aka.ms/ghei36>



On Thu, Sep 15, 2016 at 11:39 PM -0600, "Ashura" <notifications@github.com<mailto:notifications@github.com>> wrote:


How are your Symfony and PHP skills? I only see some rather empty repositories on your account.

-

**Comment by CoalaJoe** [comment]
Do have the WebSocketsBundle installed and the client configured?

**Comment by abner01061998** [comment]
Yeah i have both configured my question is how to use the topic

Obtener Outlook para Android<https://aka.ms/ghei36>



On Fri, Sep 16, 2016 at 1:20 AM -0600, "Ashura" <notifications@github.com<mailto:notifications@github.com>> wrote:


Do have the WebSocketsBundle installed and the client configured?

-

**Comment by CoalaJoe** [comment]
I made an eventlistener with this:

```
    /**
     * ObservationListener constructor.
     *
     * @param PusherInterface $pusher
     * @param CommandsHandler $handler
     * @param EntityManager   $em
     */
    public function __construct(PusherInterface $pusher, CommandsHandler $handler, EntityManager $em)
    {
        $this->pusher  = $pusher;
        $this->handler = $handler;
        $this->em      = $em;
    }
```

And this will send it then:

```
    /**
     * @param CommandEvent $event
     */
    public function onCommandEvent(CommandEvent $event)
    {
        /** @var Zulu $zulu */
        $zulu = $this->em->getRepository('AppBundle:User')->getLockedZulu($event->getUser()->getUsername());
        $this->pusher->push([
            'action' => 'moveMouse',
            'data'   => [
                'id'      => $event->getUser()->getId(),
                'command' => $event->getCommand(),
                'status'  => "You shouldn't care'"
            ]
        ], 'command_topic'
        );
    }
```


If you want more you have to show me what you programmed.

**Comment by CoalaJoe** [comment]
Is this ok for you?

**Comment by CoalaJoe** [comment]
I think this issue can be closed.
