### ISSUE TITLE
How to call session.publish from the drop function?

### ISSUE THREAD

**Issue by wizkoder** [GeniusesOfSymfony/WebSocketBundle#161]
I try around with the bundle but can't wrap my head around it yet.
I want to publish an event in the case that the drop function is called.

The drop function is called from the ondrop function. But  it seems that to publish I need the session object which I do not have in that function.
How would one do that?

Here is my code (its short):
https://0bin.net/paste/o9nUZU4fRFUi7oQK#R9ONvSEy3JDxW0I7SGNhtniZa3jInzSeGnx0EQ0H+At

**Comment by farizyoga** [comment]
i got the same problem,  i need the answer too

**Comment by ProPheT777** [comment]
What do your fonction drop do? There no code about it. HTML doesn't not
help me so much to provide you à support :/ show me the JavaScript code
without websocket action please
