### ISSUE TITLE
Push broadcast to logged in eligible user or not broadcast at all

### ISSUE THREAD

**Issue by jaimesangcap** [GeniusesOfSymfony/WebSocketBundle#164]
On our system, someone will create a Task, we want to notify ONLY the user who was assigned on that particular Task.

I have a channel `notification/channel`, basically all users are connected on it.
I want to send a push notification ONLY to logged in user (assignee of the task), otherwise DONT broadcast to anyone. But of course if the user is not logged I wont get valid sessionId when calling `findByUsername` on the ClientManipulator. Then I dont have anything to pass on `eligible`

If I dont pass valid sessionId to `excluded` or `eligible` then `broadcast()` will push it to all connected clients.

Any suggestion?

**Comment by CoalaJoe** [comment]
You should make a dynamic channel seen here: https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/TopicSetup.md#advanced-example
