### ISSUE TITLE
[BC] The bundle doesn't work anymore on Symfony2.3

### ISSUE THREAD

**Issue by moroine** [GeniusesOfSymfony/WebSocketBundle#166]
I'm still on Symfony2.3 and when I run `app/console cache:clear` I have the following error:

Call to undefined method Symfony\Component\DependencyInjection\Definition::setDecoratedService() in vendor/gos/web-socket-bundle/DependencyInjection/CompilerPass/DataCollectorCompilerPass.php on line 32

From what I found, the `setDecoratedService` is available from v2.5.0. [DependencyInjection Changelog](https://github.com/symfony/dependency-injection/blob/master/CHANGELOG.md)

**Comment by CoalaJoe** [comment]
Symfony 2.3 is out of maintenance since 05/2016. So I think we can close this issue.
