### ISSUE TITLE
Anyone deploy the bundle to an NGINX server?

### ISSUE THREAD

**Issue by jhkerschner** [GeniusesOfSymfony/WebSocketBundle#167]
I'm trying to deploy to an NGINX server. The server has a dedicated IP address, and I trie during that, but keep running in to handshake or connection refused errors. Can anyone provide to configuration they used to get this working?

**Comment by cristhianfernandez01** [comment]
Hi @jhkerschner , I have seen on StackOverflow (http://stackoverflow.com/questions/36104221/websocket-work-locally-but-not-on-heroku-php-application) this configuration:
```
location /wss {
    proxy_pass http://localhost:'your_port';
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
```

 I hope that configuration can help you. regards

**Comment by jhkerschner** [comment]
Thanks, this pointed me in the right direction.
