### ISSUE TITLE
How to avoid flushing entities in Topics?

### ISSUE THREAD

**Issue by mwsv** [GeniusesOfSymfony/WebSocketBundle#168]
I need to update the application data state in database through Doctrine right after the user publish some message into Topic and I wonder what's the best way to delegate such activities somewhere else in aim to avoid blocking things like e.g. entity manager flush method? I want to use the Doctrine in Topics as little as possible.

**Comment by mwsv** [comment]
React child processes is the solution of my problem:

[https://blog.wyrihaximus.net/2015/03/reactphp-child-processes/](ReactPHP: Child Processes)

**Comment by mwsv** [comment]
I wonder what's the best way to get event loop in topic? How to use these child processes in Topics?

**Comment by ProPheT777** [comment]
You can get the event loop everywhere, she is registered as service, look yml definition; moreover you add a periodic timer dedicated to the topic like following : https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/TopicSetup.md#periodic-timer-topic--connection.

Using ORM in this context is not recommended, but with symfony framework lot of developer coupled their DB persistence to the logic and you can't get out of this with a huge refacto. So if you can't delete doctrine, the best choice is to delegate to another worker. 

Choose the best transport layer for your need (I don't no the traffic that you deal) you can use (ipc, file descriptor, tcp, amqp, http whatever). React php child process is one of them (he communicate via file descriptor), but you can choose others also (depend of your need also). 
React child process is limited at scale, a lot of memory copy is done during data piping between layer and let a high footprint and php is running a command through another via bash, which is problematic at scale to properly manage processes on host machine (you lost signal between bash and php, unable to retrieve exit code etc .... when unexpected error is coming from somewhere, you know nothing, just restart the command and prey :D) 
So react child process is cool for small project or personal project. If it's not I suggest you to use a better transport layer like ipc, tcp, amqp or http with a broker who dispatch to worker, handle network error properly.

**Comment by mwsv** [comment]
Huge thanks for your detailed insight, now it's much easier for me to delve into this subject. I'm going to make some tests and decide which solution should be sufficient for me. Generally I wonder is it a bad idea to prepare some Symfony commands with DB persistence (Doctrine) code, fire these commands through the child process and push the result of command to WS server via zmq pusher? Other thing, in case of use child process, should I use service "gos_web_socket.server.event_loop" to create event loop in such way:

```

// $loop ---> gos_web_socket.server.event_loop
$loop = $this->gosWebSocketServerEventLoop;
$process = new React\ChildProcess\Process('php some command');

$loop->addTimer(0.001, function($timer) use ($process) {
    $loop = $timer->getLoop();

    $process->on('exit', function($output) use ($loop) {
        $loop->stop();
    });

    $process->start($loop);

    $process->stdout->on('data', function($output) {
        echo $output, PHP_EOL;
    });

    $i = 0;
    $loop->addPeriodicTimer(1, function ($timer) use (&$i, $process) {
        $process->stdin->write($i++);
    });
});

$loop->run(); 

```

...or in case of Topics it should work rather like this one:

```

	/** @var ConnectionPeriodicTimer $timer */
	$timer = $connection->PeriodicTimer;
	$process = new React\ChildProcess\Process('php some command');

	$timer->addPeriodicTimer('someTimerName', 0.01, function($timer) use ($process) {
		/* @var EventLoop\Timer\Timer $timer */
		$process->start($timer->getLoop());
		
		(...)
	});
	
```

Also I have redis in my stack, therefore I'm also really interested in these your words:

```
In really easy way, if you have redis in your stack, you can use the redis pub/sub mode.
```

Are there some PHP libraries etc. to make this in such way, or it's rather question of my own implementation of such a functionality? Agan, thank you for your help and insight!

**Comment by ProPheT777** [comment]
So in the order : 

> fire these commands through the child process and push the result of command to WS server via zmq pusher?

If you attempt a returned value, yes (It's also called Remote Procedure Call (RPC), lot of broker support that) and use a deferred to handle the response in the future. 

@WyriHaximus write a bunch of lib arround child-process with rpc system and (pseudo) threading : https://github.com/WyriHaximus/reactphp-child-process-pool https://github.com/WyriHaximus/php-cpu-core-detector https://github.com/WyriHaximus/reactphp-child-process-promise https://github.com/WyriHaximus/reactphp-child-process-messenger you can also check is blog, he blogged a lot about reactphp -> https://blog.wyrihaximus.net/

Take a look of example folder in repository to have an idea.

To this part of code :

```php
// $loop ---> gos_web_socket.server.event_loop
$loop = $this->gosWebSocketServerEventLoop->create();
$process = new React\ChildProcess\Process('php some command');

$loop->addTimer(0.001, function($timer) use ($process) {
    $loop = $timer->getLoop();

    $process->on('exit', function($output) use ($loop) {
        $loop->stop();
    });

    $process->start($loop);

    $process->stdout->on('data', function($output) {
        echo $output, PHP_EOL;
    });

    $i = 0;
    $loop->addPeriodicTimer(1, function ($timer) use (&$i, $process) {
        $process->stdin->write($i++);
    });
});

$loop->run(); 
```

You don't need to reuse to websocket loop service, you should use a loop dedicated to this command. Websocket server register a loop as service to let the user add some binding to the server loop (like timer etc) and this loop is pre configured with ratchet and stuff. So when you are not in websocket server context, you don't need that loop, create one from `Factory` of reactphp.

> For redis in pub/sub mode is so simple (But you don't have any data back) 

First of all, it's supported by php client, so you don't need specific lib. 

Here an example that I done for real time notification system : https://github.com/GeniusesOfSymfony/NotificationBundle/blob/master/Server/PubSubServer.php#L124

I use async predis client (checkout the composer.json if you want use it). There is a lot of resources on that, for example :

https://xmeng.wordpress.com/2011/11/14/pubsub-in-redis-using-php/ 

you can type `redis pubsub php` in google and read about that subject.

**Comment by mwsv** [comment]
Indeed, Redis Pub/Sub (along with ZMQ pusher) server turned out to be absolutely the best solution in this case, your example made for notification system was very inspiring for me - thank you very much for taking the time to explain me all these things :+1:
