### ISSUE TITLE
webscoketbundle ssl connections

### ISSUE THREAD

**Issue by ebcamps** [GeniusesOfSymfony/WebSocketBundle#169]
I use a server with nginx and when I try to configure it to work websocket for ssl installing and using stunnel documentation of the bundle gives me this error 'wss: //127.0.0.1: 8443 /' failed: WebSocket opening handshake was any help Canceled favor!!!!

**Comment by QuozPowa** [comment]
Same problem :
WebSocket connection to 'wss://NDD:8443/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
(index):70 Disconnected for Connection could not be established. with code 3
stunnel is correctly configured and gos websocket server is running...

**Comment by QuozPowa** [comment]
And with -- env = prod option, the server port is not correct.

**Comment by CoalaJoe** [comment]
I updated the SSL config. Try it and give me feedback.
