### ISSUE TITLE
Username of Wamp Pusher

### ISSUE THREAD

**Issue by layanto** [GeniusesOfSymfony/WebSocketBundle#173]
Since Wamp Pusher is using onPublish like browser client, is there a way in the onPublish method of TopicHandler to find out that it is the server who is sending the message? With sharing session, I find that anon-xxx user is the user pushing from server; basically I can't differentiate whether the user is the server or browser client. 

Example use case where it is useful to find out if the user is the server:
- All browser clients subscribe to server_notification channel. But only the server is allowed to message (push) on that channel to all subscribe clients. If a browser client publish on that channel, the server will simply ignore.

How to do this with this bundle?

**Comment by ProPheT777** [comment]
You can create an identity for the server (a secret, a jwt that say 'hey 'im the server) and filter all incoming message to let only your server broadcast messages.
