### ISSUE TITLE
how to turn WebSocketBundle as daemon ?

### ISSUE THREAD

**Issue by Jaggle** [GeniusesOfSymfony/WebSocketBundle#175]
I'm now using 
nohup php  app/console gos:websocket:server &
to run as a daemon in ubuntu ,but what if I will stop,restart WebSocketBundle ?
I'm not very familiar with linux commands,thanks for your help!

**Comment by ProPheT777** [comment]
It's already a daemon, I think you would detach it from your tty to have it in background ? 

If it's the case, you can use supervisord, well documented and simple. Just do a google search with "supervisor php command" and you will find all the stuff that you need :)

**Comment by Jaggle** [comment]
@ProPheT777 ,thank you ,you solved my problem, my application works fine with supervisor!

**Comment by CoalaJoe** [comment]
This ticket can be closed.
