### ISSUE TITLE
Bug PingableDriverCompilerPass?

### ISSUE THREAD

**Issue by koenjonker** [GeniusesOfSymfony/WebSocketBundle#176]
I have an issue in the PingableDriverCompilerPass.php.

The PdoPeriodicPing service is not working on 1.8.3, yet we have working code on 1.8.1.

On line 25 to 30 the following code is executed:
`  
$sessionHandler = $container->getAlias('gos_web_socket.session_handler');

if (false === $sessionHandler instanceof PdoSessionHandler) {
    return;
}
`

As you can see the if statement will always return false because $sessionHandler will be an instance of Alias instead of PdoSessionHandler.

If i change $container->getAlias to $container->get (as it was in 1.8.1) i receive the proper instance and my code will execute the PdoPeriodicPing.

**Comment by ProPheT777** [comment]
Can you try with `$sessionHandler = $container->get($container->getAlias('gos_web_socket.session_handler')->getId());`

And said me if that solve your problem? I'll push the fix if it's the case. Thank you for reporting it @koenjonker

**Comment by koenjonker** [comment]
Thanks for the quick reply!!

There is no getId function on Alias, but when you parse it as string the above method works!

$sessionHandler = $container->get((string)$container->getAlias('gos_web_socket.session_handler'));

**Comment by ProPheT777** [comment]
You can run composer update, it's fixed in 1.8.4. Give me feedback if any problem. Thank you!
