### ISSUE TITLE
 Access denied for user 'root'@'localhost'

### ISSUE THREAD

**Issue by TheFamousPG** [GeniusesOfSymfony/WebSocketBundle#177]
Hi

I've installed websocketbundle and it works fine on dev environnement but when I launch the command :  `php app/console gos:websocket:server --profile --env=prod`
I have the following error : 
 An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES

No lines number, I don't know where the server search the wrong parameters....
Have you an idea ?

**Comment by ProPheT777** [comment]
Your credentials to connect to your db are wrong. may your prod env is not well configured

**Comment by TheFamousPG** [comment]
Where can I found the prod env conf for websocket (Can I launch websocket in prod env if symfony is on dev ?)

**Comment by ProPheT777** [comment]
It's relying on your global configuration of symfony, not of this this bundle. You can refer to production configuration to symfony docs. The file who defined parameters for production environment is located in `app/config/app_prod.yml`

**Comment by TheFamousPG** [comment]
Ok, the problem was my cache..........
Thanks for the help.
