### ISSUE TITLE
Try to connect from WampSharp.

### ISSUE THREAD

**Issue by KrissMcCone** [GeniusesOfSymfony/WebSocketBundle#18]
Hello. I want to connect to serwer from this bundle through WampSharp.

const string serverAddress = "ws://domaincoml:8080/";
            DefaultWampChannelFactory channelFactory =
                new DefaultWampChannelFactory();

            IWampChannel wampChannel =
                channelFactory.CreateJsonChannel(serverAddress, "realm1");

            wampChannel.Open().Wait();

I can connect, and I see it in GOS console. However, i have exception {"subprotocol doesn't match"}.

Any ideas?

thanks!

**Comment by ProPheT777** [comment]
It's because you use the WampV2 protocol, We are using WampV1 protocol, according to the docs your lib support v1.

On my side WebsocketBundle will not support wampV2 protocol because it bring nothing more valuable (just more complexity for nothing).

**Comment by darkl** [comment]
You use WAMP1 protocol in WampSharp instead of WAMP2, just use the WampSharp.V1 namespace. See this [tutorial](https://github.com/Code-Sharp/WampSharp/wiki/Getting-started-with-WAMPv1-client).

Note that WAMP1 is deprecated, so its unlikely I'll fix WampSharp issues to that protocol version.

**Comment by KrissMcCone** [comment]
Helpful as always. Thank you :)
