### ISSUE TITLE
How to broadcast a message to a specific channel or room ?

### ISSUE THREAD

**Issue by QuozPowa** [GeniusesOfSymfony/WebSocketBundle#180]
Do I need to iterate over subscribers and make an array of them if they meet criteria or is there a proper way to do it ?

**Comment by CoalaJoe** [comment]
Just make different Topics for every room.

**Comment by QuozPowa** [comment]
And if I have to send a message from a room to another in the server side, do you advise a push ?

**Comment by CoalaJoe** [comment]
@QuozPowa Sure. Have you tried?

**Comment by QuozPowa** [comment]
Yes thank you ! And do you know a way to check if the client is authenticated before letting him to join the topic ? Maybe with the events ?

**Comment by CoalaJoe** [comment]
@QuozPowa I'd use the SecurityContext and then if the requirements don't match, cut the connection from Serverside.

**Comment by QuozPowa** [comment]
How do you cut the connection ? I try unset $connection during the onSubscribe function...
I have another strange problem, when the user is unSubscribing, his userId doesn't exist (based on clientManipulator).

**Comment by CoalaJoe** [comment]
Phew. That is an old issue. I don't currently know.

**Comment by QuozPowa** [comment]
😰
