### ISSUE TITLE
SSL config is wrong?

### ISSUE THREAD

**Issue by CoalaJoe** [GeniusesOfSymfony/WebSocketBundle#182]
I had to change the webserver to use https and now I have to configure the websocket for ssl aswell. But somehow it is not working.

config.yml
![image](https://cloud.githubusercontent.com/assets/5689499/18468610/f8324778-79a4-11e6-8a61-26481e3c67c9.png)

Javascript:
![image](https://cloud.githubusercontent.com/assets/5689499/18468636/14bd93c0-79a5-11e6-9e35-180b1b7ffbf1.png)

Stunnel:
![image](https://cloud.githubusercontent.com/assets/5689499/18468774/b9981a00-79a5-11e6-9448-070ba36bc19a.png)

-- EDIT

I think I got the right configs now for stunnel. I will update the documentation and make a pull request.

But the connection is still not working correctly. When I want to connect with the domainname, stunnel won't react. And if i connect with the IP I get this error: (Connection refused)
![image](https://cloud.githubusercontent.com/assets/5689499/18472603/c21959ba-79b8-11e6-9bc6-bccc0de88c58.png)

Thanks in advance.

**Comment by ProPheT777** [comment]
I can't really help you with apache2, I'm using stunnel + nginx so ... :s I think there are some thread about apache2 with ssl with websocket or stream module but they have been solved by switching on stunnel and nginx. 

If you get it work with apache2 feel free to open a pull request and complete the docs, it could be super nice for others apache2 users! Thank you

**Comment by CoalaJoe** [comment]
I got it working. I'll update the docs.

**Comment by CoalaJoe** [comment]
#183
