### ISSUE TITLE
How can i use with anguar js.?

### ISSUE THREAD

**Issue by miljojohn** [GeniusesOfSymfony/WebSocketBundle#189]
How can i use WebSocketBundle with AngularJS.While searching i got 
"AngularWAMP is an AngularJS wrapper for Autobahn|JS that provides deeper integration for AngularJS apps".How can i use the gos_web_socket_client.js file in angular js. Please help

**Comment by ProPheT777** [comment]
https://github.com/GeniusesOfSymfony/WebsocketAngularJsClient/blob/master/src/gos-websocket.js

**Comment by miljojohn** [comment]
Thank you for your prompt response (y).

**Comment by ProPheT777** [comment]
You can look on notification bundle where it's used : https://github.com/GeniusesOfSymfony/NotificationBundle/blob/master/Resources/public/js/notification/src/service/WebsocketService.coffee 

I'm sorry there no docs, but it's really simple

**Comment by miljojohn** [comment]
I am new to symfony and angular js.Am using symfony restfull web services and angular js as clent side.I need to send messages from mserver to client.In gos socket i created the topic handler and registered  periodic timer. all working fine with me.next step is need to connect web socket from angular side ..ProPheT777  pls help me

**Comment by miljojohn** [comment]
dear ProPheT777,
i tried WebsocketAngularJsClient/blob/master/src/gos-websocket.js but i got the error stating that ws is not found

**Comment by miljojohn** [comment]
How can i remove the periodic timer after receiving 1st message ?
