### ISSUE TITLE
iOS supporting

### ISSUE THREAD

**Issue by dizialina** [GeniusesOfSymfony/WebSocketBundle#193]
Hi! I'm iOS developer and my web side uses your api for working with web sockets. Do you know of any iOS libraries that support your APIs? All libraries that I found can't do action like this for subscribing to rooms:
```
webSocket.on("socket/connect", function(session){

                session.subscribe("conversation_realtime/sportspace581a1541590b21.14581077", function(uri, payload){
                    console.log(payload.message.text);
}
```

**Comment by ProPheT777** [comment]
You can use any WAMP v1 client compliant and it will work fine

**Comment by dizialina** [comment]
Thanx for help :)
