### ISSUE TITLE
broadcast to topic from controller.

### ISSUE THREAD

**Issue by JeetChaudhari** [GeniusesOfSymfony/WebSocketBundle#194]
I set up WebSocketBundle correctly in my project and it is working great, however there is one functionality I need to implement which requires me to broadcast message to all clients connected.
Basically I am adding new record for my entity in POST call in controller and I want to send that newly added record to all connected clients, however i do not find any information about how do I broadcast from controller. Can you guys please provide one example for this? It would be very appreciated.

**Comment by mwsv** [comment]
You can use one of pushers:

https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/Pusher.md

I recommend you to use ZMQ pusher. It allows you to send something from Symfony app into running WS process. As described above, you can push from controller action by:

` $pusher = $this->container->get('gos_web_socket.wamp.pusher');
//push(data, route_name, route_arguments)
$pusher->push(['my_data' => 'data'], 'user_notification', ['username' => 'user1']);  `

...and then broadcast received data through:

` $topic->broadcast($data) `

...in _onPush_ method included in your topic handler.

**Comment by JeetChaudhari** [comment]
@mwsv Thank you for letting me know this, I thought Push is something different and has to do with push notifications instead of broadcasting to the topic so I did not use pusher.

I got it working without integrating pusher. I realized that WebSocketBundle comes with the PHP Client for websocket so I added two fields for port and host in parameters, Created one service as follows.

```
<?php

namespace COREBundle\Service;

use Doctrine\ORM\EntityManager;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use FOS\UserBundle\Doctrine\AbstractUserListener;
use FOS\UserBundle\Doctrine\UserManager;
use Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface;
use FOS\UserBundle\Util\CanonicalizerInterface;
use FOS\UserBundle\Model\UserInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Doctrine\Common\Persistence\ObjectManager;

use Gos\Component\WebSocketClient\Wamp\Client;

class BroadcastService
{
    /**
     * @var EntityManager
     */
    protected $em;

    /**
     *@var Client
     */
    protected $client;

    /**
     *@var SessionId
     */
    protected $sessionId;

    /**
     * BroadcastService constructor.
     * @param EntityManager $em
     */
    public function __construct(EntityManager $em, $host, $port)
    {
        $this->em = $em;
        $this->client = new Client($host, $port);
        $this->sessionId = $this->client->connect();
    }

    /**
     * BroadcastService destructor.
     */
    public function __destruct()
    {
        if ($this->client) {
            $this->client->disconnect();
        }
    }

    public function publish($topic, $payload, $exclude = array(), $eligible = array())
    {
        $this->client->publish($topic, $payload, $exclude, $eligible);
    }

    public function event($topic, $payload)
    {
        $this->client->publish($topic, $payload);
    }
}
```

Now in controller i use following code to broadcast.
```
$payload = array('msg'=>'some message');
$this->get->('core.broadcast_service')->event('user_notification', $payload);
```
I have used this method and it works. I don't know if it is according to Symfony Standards or not and if something is wrong with this implementation but it gets my work done and i am not required to install zmq or amqp pusher on server as well as require any extra composer packages.

**Comment by mwsv** [comment]
> @mwsv Thank you for letting me know this, I thought Push is something different and has to do with push notifications instead of broadcasting to the topic so I did not use pusher.

It allows you to distribute messages between different workers like standard Symfony application, Ratchet server stack and so on, therefore you can use it to push something into topic and broadcast this message then. However you solved your problem in also quite interesting way, thanks for sharing :+1:

**Comment by ProPheT777** [comment]
@JeetChaudhari Your broadcast service is the same as Websocket Pusher (aka wamp pusher) and relying on  `onPublish` method of your targetted topic 

https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Pusher/Wamp/WampPusher.php

**Comment by ProPheT777** [comment]
Hey,

FWI using websocket client to push the server is the same as using the
built in websocket pusher provided in the bundle. It works fine however you
might consider the following spec :
- compare to other pusher, the connection is very slow. (For performance
first application it might be an issue)
- the handshake have an I cost on websocket server side. It's an issue if
your front application handle a very hight traffic and connect via
websocket protocol, it use a lot of ressources for nothing.

If you are not impacted by those points, keep it, it works fine.

Le sam. 10 déc. 2016 04:50, Jeet Chaudhari <notifications@github.com> a
écrit :
