### ISSUE TITLE
Composer - Minimum Stability error

### ISSUE THREAD

**Issue by gittix09** [GeniusesOfSymfony/WebSocketBundle#2]
Also, please note that (in Composer) using this line
"gos/web-socket-bundle": "~0.1"
i got an error about minimun-stability restriction.

I solved using
"gos/web-socket-bundle": "@dev"

**Comment by ProPheT777** [comment]
Yes, currently he is not tagged, so I use a branch alias through composer. 

`"gos/web-socket-bundle": "~0.1@dev"` will work :)
