### ISSUE TITLE
Launch websocket server from controller

### ISSUE THREAD

**Issue by Leggy7** [GeniusesOfSymfony/WebSocketBundle#204]
I'm struggling to launch the server from the controller.

I noticed I could proceed this way:

```
$server = $this->container->get('gos_web_socket.ws.server');
$server->launch('localhost', '8080', null);
```

but after several seconds I get 

> 504 gateway timeout

 from nginx proxy

in the launch method I don't know what to give as profile parameter. Also tried to pass true, same result.

Is there any kind of configuration info I should provide? 

Any help would be appreciated.

**Comment by ProPheT777** [comment]
Why run the websocket server inside a controller? 

You must start it from command line via the symfony console. Start a cli server in fastcgi mode will bring lot of weird things.

Follow the documention and start it from your shell

**Comment by Leggy7** [comment]
I know, and I would have it done that way. Unfortunately our host has not a shell prompt so I cannot run anything by the command line.

Which weird thing are you refering to? Is it viable to launch from the controller or not? In the doc I saw the WebSocketServer class in which that public launch method inspired me..

So you say it is complicated, not possible or not yet sound?

**Comment by ProPheT777** [comment]
It's sound really complicated (and impossible for a professional production usage) but fascgi with nginx proxy is not designed for long process running, moreover when you will shutdown your browser which hiting the controller, that will stop the websocket server. 

The better option is to find another host provider with remote shell acess for doing this kind of stuff

**Comment by Leggy7** [comment]
hmm, and what if I run the controller action from the server itself?
In that case is there any recomendation on the parameters to call the interface method with?

**Comment by Leggy7** [comment]
By the way I got your point and moved to another provider. See #205
