### ISSUE TITLE
SSL with stunnel

### ISSUE THREAD

**Issue by AntoineTesson** [GeniusesOfSymfony/WebSocketBundle#209]
Hi,

In local no problem, but in production on my server with https 
Firefox ne peut établir de connexion avec le serveur à l’adresse wss://kergafa.com:8081/.
I try i try i try and i try ...... Where is the problem ?

in my conf.yml 
gos_web_socket:
    server:
        port: 8081       #The port the socket server will listen on
        host: kergafa.com   #The host ip to bind to
        router:
            resources:
                - '@SkiesAdherentBundle/Resources/config/pubsub/routing.yml
    client:
        firewall: main
        session_handler: '@session.handler.pdo'
    pushers:
        wamp:
            host:  kergafa.com
            port: 8081`

when i start the server:
`[2017-01-06 04:33:12] websocket.INFO: Starting web socket  
[2017-01-06 04:33:12] websocket.INFO: Register periodic callback Gos\Bundle\WebSocketBundle\Periodic\PdoPeriodicPing, executed each 20 seconds  
[2017-01-06 04:33:12] websocket.INFO: Launching Ratchet on kergafa.com:8081 PID: 7698  `

so its work

in ctunnel conf

[websockets]

accept = 8080
connect = kergafa.com:8081

[Started: /etc/stunnel/stunnel.conf] stunnel.

the grep 8080 result
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      7694/stunnel4

**Comment by CoalaJoe** [comment]
How do you start the websocket server in production?

**Comment by AntoineTesson** [comment]
i start like this 

app/console gos:websocket:server -a kergafa.com 

and he starts with this notice : 
[2017-01-06 04:33:12] websocket.INFO: Launching Ratchet on kergafa.com:8081 PID: 7698

**Comment by CoalaJoe** [comment]
I updated https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/1d560deb0779007f6fc452b1819ea92348f4d4ad/Resources/docs/Ssl.md a while ago and improved the stunnel config. I have no access to a running system with websockets and stunnel the next 4-5 days. 
If you can wait, I'll send you some of my config.

**Comment by AntoineTesson** [comment]
Its ok. Thanks for ur help. I can wait. 
On the md text  u said : 

Launch your websocket server in the connectport.
Connect the client on wss://my.domainname.com:acceptport

So we are agree, the line of JS it's var webSocket = WS.connect("wss://kergafa.com:8080")
because 
[websockets]
accept = 8080
connect = kergafa.com:8081

its right ? Have a good week-end.

**Comment by AntoineTesson** [comment]
Amazing its ok, when i answered i understood my mistake. i' mistook the port with acceptport and connectport. U are doing  a great job with this bundle, keep going !

**Comment by CoalaJoe** [comment]
Thanks alot! I wish you a good week-end too.
I know, it is a little confusing. Stunnel does the following:
- It provides 1 Port for the client which is encrypted.
- It forwards it localy to a not, encrypted port.

So you have to connect to the encrypted port and the forward port is the port that your websocket server listens to.
