### ISSUE TITLE
Send message to specific user.

### ISSUE THREAD

**Issue by KrissMcCone** [GeniusesOfSymfony/WebSocketBundle#21]
Hello. I'm really sor for a lot of question, but i promise it's last this week. Friday today, yes <3

I can send message to user who publish sth, by $connection->event($topic->getId(), ['msg' => 'lol']);
How can I publish his message only for some session iD not for all topic. Is it possible?

**Comment by ProPheT777** [comment]
Haha you don't bother me :D 

I think it's possible, I'll try to do it and add the docs about it. (maybe tomorrow).

If you want investigate you can try this way  :

inside a topic do

```php
foreach($this as $client){
    var_dump($client); //to reveal the content and play with it 
exit;
}
```
