### ISSUE TITLE
Can't install on symfony 3.2

### ISSUE THREAD

**Issue by videni** [GeniusesOfSymfony/WebSocketBundle#213]
Problem 1
    - Conclusion: remove cboden/ratchet v0.3.6
    - Conclusion: don't install cboden/ratchet v0.3.6
    - don't install gos/web-socket-bundle 1.8.x-dev|don't install cboden/ratchet v0.3.6
    - don't install gos/web-socket-bundle v1.8.0|don't install cboden/ratchet v0.3.6
    - don't install gos/web-socket-bundle v1.8.1|don't install cboden/ratchet v0.3.6
    - don't install gos/web-socket-bundle v1.8.2|don't install cboden/ratchet v0.3.6
    - don't install gos/web-socket-bundle v1.8.3|don't install cboden/ratchet v0.3.6
    - don't install gos/web-socket-bundle v1.8.4|don't install cboden/ratchet v0.3.6
    - don't install gos/web-socket-bundle v1.8.5|don't install cboden/ratchet v0.3.6
    - Installation request for cboden/ratchet ^0.3.6 -> satisfiable by cboden/ratchet[v0.3.6].
    - Installation request for gos/web-socket-bundle ^1.8 -> satisfiable by gos/web-socket-bundle[1.8.x-dev, v1.8.0, v1.8.1, v1.8.2, v1.8.3, v1.8.4, v1.8.5].

**Comment by AntoineTesson** [comment]
Hi,

Show me your composer file

**Comment by videni** [comment]
@AntoineTesson ,thank you ,  I am using [sylius](https://github.com/Sylius/Sylius/blob/master/composer.json) composer file?

**Comment by ProPheT777** [comment]
Hey, 

It's not related to symfony 3.2 specially. You can't use cboden/ratchet as websocket register a fork of this repository with the same namespace. 

https://github.com/GeniusesOfSymfony/Ratchet

It's the same as the original (same namespace, a BC on internal class only), plus tweaks to make it work properly with this bundle. 

Remove cboden/ratchet from your composer file, this bundle will install ratchet for gos.

**Comment by videni** [comment]
@ProPheT777 ,  thank  for your help ,  it works now.
