### ISSUE TITLE
Setting-up goswebsocket in AWS

### ISSUE THREAD

**Issue by robinkoikkara** [GeniusesOfSymfony/WebSocketBundle#215]
Dear Team,

My production server is hosted in AWS and the simple architecture of the server is, AWS Load balancer->Autoscaling Group->EC2 Instance (with Apache). My prod server is configured for SSL communication and LB is also configured with SSL certificate. I am trying to deploy the websocket code in this server and its not working.I get the below error 

> WebSocket connection to 'wss://ec2-bl-bl-bla-bl.ap-south-1.compute.amazonaws.com:9090/' failed: WebSocket opening handshake timed out

In fact I have opened the inbound traffic for LB, AS Group and EC2 to accept all TCP traffic.   

My application works fine in AWS (my staging instance) in which SSL is not configured. Also there is an architectural difference. AWS LB talks to EC2 instance directly. Also its not secured. 

Please help to resolve the prod issue. I am not trying to get a load balanced web socket implementation. If at least it can work for one specific instance that would be great.

**Comment by ProPheT777** [comment]
Hey,

It's look like you have an issue your SSL configuration. Not related to the
infrastructure. You should try to enable SSL in, dev, staging then prod. I
think you you will find the issue by getting it working in dev and then
apply the SSL configure on your prod.

All SSL related stuff is now documented. Try it and come here again if the
problem persist.

Le jeu. 26 janv. 2017 09:30, robinkoikkara <notifications@github.com> a
écrit :

**Comment by robinkoikkara** [comment]
Thank you For the help. 
I am able to resolve the issue and I have added one wiki page here with all the steps https://github.com/GeniusesOfSymfony/WebSocketBundle/wiki/Set-up-Gos-Web-Socket-Bundle-in-AWS-(Production)-with-SSL 
Please let me know whether I can improve on any aspect.
