### ISSUE TITLE
Latest AutobahnJS

### ISSUE THREAD

**Issue by akadlec** [GeniusesOfSymfony/WebSocketBundle#223]
Does this bunde works with latest autobahnJS? I'm not able to establish connection.

**Comment by omarsoufiane** [comment]
no this bundle implements wamp v1 if you want wamp v2 support check thruway
https://github.com/voryx/Thruway
and https://github.com/voryx/ThruwayBundle

**Comment by frankadrian** [comment]
Would be great to have this as a notice on the landing page! Thanks 💪
