### ISSUE TITLE
failed: Broken pipe

### ISSUE THREAD

**Issue by miljotechcthree** [GeniusesOfSymfony/WebSocketBundle#241]
Websocket was running successfully in my server and suddenly i got "Failed: Broken pipe" error message.
Please suggest any solution

**Comment by miljotechcthree** [comment]
fixed

**Comment by elpoutro** [comment]
I get the same error.
Changing the "wait_timeout" (28800 seconds by default) to other value (31536000 is the max value) resolves the issue but I don't want to change this value in production.
Have you found another solution?
