### ISSUE TITLE
Port 80 Apache WebSockets

### ISSUE THREAD

**Issue by eduardo5000** [GeniusesOfSymfony/WebSocketBundle#248]
Suddenly our apache does not respond in port 80.

In port 443 looks good. 

It is like there is some type of limitation for the 80 port. But we don't know what is it. We have tweak:

<IfModule mpm_prefork_module>
        StartServers            5
        MinSpareServers         15
        MaxSpareServers         20
        ServerLimit             1000
        MaxRequestWorkers       1000
        MaxConnectionsPerChild  10000
</IfModule>

But, when connections in port 80 arise many connections apache does not responde at that port. In port 443 looks good.

Please, let me know.

Thank you !

**Comment by CoalaJoe** [comment]
We really need more context.
- VHost entry
- What Pusher do you use
- Did it work previously
etc.

**Comment by eduardo5000** [comment]
It's a phisical server.

The vhost has:

<Location "/wsauthoban">
                ProxyPass "ws://server.intra:8090/"
        </Location>

        <Directory /var/www/>
         Options -Indexes

         AuthType Basic
         AuthName "...."
         AuthBasicProvider file ldap
         AuthUserFile "/var/www/.htpasswd"
         AuthLDAPInitialBindAsUser on
         AuthLDAPInitialBindPattern (.+) tesa\\\$1
         AuthLDAPBindAuthoritative on
         AuthLDAPDereferenceAliases never
         LDAPReferrals off
         AuthLDAPURL ldap://...............................


We use zmq pusher.

It seems never has gone well.

Our mpm_prefork.conf:

<IfModule mpm_prefork_module>
        StartServers            5
        MinSpareServers         15
        MaxSpareServers         20
        ServerLimit             800
        MaxRequestWorkers       800
        MaxConnectionsPerChild  1000
</IfModule>






Sorry for my english

Thx!

**Comment by CoalaJoe** [comment]
I guess you did a restart of the apache2 service?
What does the log output?
what ports are open? `netstat -tulpn`

**Comment by eduardo5000** [comment]
Yes when we do a apache2 service restart all starts going well.

Error.log:

[Mon Jul 03 09:25:48.058578 2017] [ssl:info] [pid 18468] (70014)End of file found: [client 10.33.28.104:53797] AH01991: SSL input filter rea$
[Mon Jul 03 09:25:48.060561 2017] [ssl:info] [pid 18465] (70014)End of file found: [client 10.33.28.104:53796] AH01991: SSL input filter rea$
[Mon Jul 03 09:25:48.064278 2017] [ssl:info] [pid 18467] (70014)End of file found: [client 10.33.28.104:53793] AH01991: SSL input filter rea$
[Mon Jul 03 09:25:48.066923 2017] [ssl:info] [pid 18466] (70014)End of file found: [client 10.33.28.104:53798] AH01991: SSL input filter rea$
[Mon Jul 03 09:25:48.089159 2017] [ssl:info] [pid 18483] [client 10.33.28.104:53799] AH01964: Connection to child 61 established (server ind$
[Mon Jul 03 09:25:50.159297 2017] [ssl:info] [pid 18483] (70007)The timeout specified has expired: [client 10.33.28.104:53799] AH01991: SSL $
[Mon Jul 03 09:25:56.047815 2017] [mpm_prefork:info] [pid 18415] AH00162: server seems busy, (you may need to increase StartServers, or Min/$
[Mon Jul 03 09:26:16.096784 2017] [mpm_prefork:info] [pid 18415] AH00162: server seems busy, (you may need to increase StartServers, or Min/$
[Mon Jul 03 09:26:52.359727 2017] [authnz_ldap:info] [pid 18477] [client 10.51.14.12:61764] AH01695: auth_ldap authenticate: user AE4610983B$
[Mon Jul 03 09:26:52.792691 2017] [authnz_ldap:info] [pid 18529] [client 10.51.14.12:6408] AH01695: auth_ldap authenticate: user  authentica$
[Mon Jul 03 09:26:52.906982 2017] [authnz_ldap:info] [pid 18534] [client 10.51.14.12:10108] AH01695: auth_ldap authenticate: user  authentic$
[Mon Jul 03 09:26:55.696973 2017] [authnz_ldap:info] [pid 18526] [client 10.51.14.12:6423] AH01695: auth_ldap authenticate: user  authentica$
[Mon Jul 03 09:26:55.810447 2017] [authnz_ldap:info] [pid 18501] [client 10.51.14.12:61782] AH01695: auth_ldap authenticate: user  authentic$
[Mon Jul 03 09:27:02.515822 2017] [authnz_ldap:info] [pid 18482] [client 10.51.14.12:10119] AH01695: auth_ldap authenticate: user  authentic$
[Mon Jul 03 09:27:02.660920 2017] [authnz_ldap:info] [pid 18463] [client 10.51.14.12:61814] AH01695: auth_ldap authenticate: user  authentic$
[Mon Jul 03 09:28:30.521414 2017] [authnz_ldap:info] [pid 18660] [client 10.51.14.12:13794] AH01695: auth_ldap authenticate: user AE4610983B$
[Mon Jul 03 09:28:52.412110 2017] [mpm_prefork:info] [pid 18415] AH00162: server seems busy, (you may need to increase StartServers, or Min/$
[Mon Jul 03 09:30:48.629850 2017] [mpm_prefork:info] [pid 18415] AH00162: server seems busy, (you may need to increase StartServers, or Min/$
[Mon Jul 03 09:34:13.970020 2017] [mpm_prefork:info] [pid 18415] AH00162: server seems busy, (you may need to increase StartServers, or Min/$
[Mon Jul 03 09:34:42.964559 2017] [core:info] [pid 18757] [client 10.51.14.12:8773] AH00128: File does not exist: /var/www/js/cal2.js, refer$
[Mon Jul 03 09:34:42.977428 2017] [core:info] [pid 18742] [client 10.51.14.12:64342] AH00128: File does not exist: /var/www/js/cal_conf2.js,$
[Mon Jul 03 09:35:57.130270 2017] [authnz_ldap:info] [pid 19066] [client 10.51.14.12:64768] AH01695: auth_ldap authenticate: user  authentic$
[Mon Jul 03 09:35:57.252555 2017] [authnz_ldap:info] [pid 19058] [client 10.51.14.12:16198] AH01695: auth_ldap authenticate: user  authentic$
[Mon Jul 03 09:36:39.743111 2017] [authnz_ldap:info] [pid 18453] [client 10.16.37.170:51224] AH01695: auth_ldap authenticate: user dnx3868 a$
[Mon Jul 03 09:36:39.743174 2017] [auth_basic:error] [pid 18453] [client 10.16.37.170:51224] AH01617: user dnx3868: authentication failure f$
[Mon Jul 03 09:36:41.052959 2017] [authnz_ldap:info] [pid 18453] [client 10.16.37.170:51224] AH01695: auth_ldap authenticate: user dnx3868 a$
[Mon Jul 03 09:36:41.052993 2017] [auth_basic:error] [pid 18453] [client 10.16.37.170:51224] AH01617: user dnx3868: authentication failure f$
[Mon Jul 03 09:36:42.415663 2017] [authnz_ldap:info] [pid 18453] [client 10.16.37.170:51224] AH01695: auth_ldap authenticate: user dnx3868 a$
[Mon Jul 03 09:36:42.415728 2017] [auth_basic:error] [pid 18453] [client 10.16.37.170:51224] AH01617: user dnx3868: authentication failure f$
[Mon Jul 03 09:37:28.299343 2017] [mpm_prefork:info] [pid 18415] AH00162: server seems busy, (you may need to increase StartServers, or Min/$
[Mon Jul 03 09:39:38.501543 2017] [authnz_ldap:info] [pid 19126] [client 10.51.14.12:17254] AH01695: auth_ldap authenticate: user  authentic$
[Mon Jul 03 09:39:38.647361 2017] [authnz_ldap:info] [pid 19179] [client 10.51.14.12:10298] AH01695: auth_ldap authenticate: user  authentic$
[Mon Jul 03 09:39:43.409695 2017] [authnz_ldap:info] [pid 19135] [client 10.51.14.12:1334] AH01695: auth_ldap authenticate: user  authentica$
[Mon Jul 03 09:39:43.564145 2017] [authnz_ldap:info] [pid 19057] [client 10.51.14.12:17282] AH01695: auth_ldap authenticate: user  authentic


netstat -tulpn:

tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1781/sshd       
tcp        0      0 127.0.0.1:3128          0.0.0.0:*               LISTEN      1853/cntlm      
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      2016/master     
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      12921/1         
tcp        0      0 127.0.0.1:8090          0.0.0.0:*               LISTEN      7736/php        
tcp        0      0 127.0.0.1:6011          0.0.0.0:*               LISTEN      16973/4         
tcp        0      0 xx.xx.xx.xx:8091      0.0.0.0:*               LISTEN      7736/php        
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      1409/smbd       
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN      1994/mysqld     
tcp        0      0 0.0.0.0:843             0.0.0.0:*               LISTEN      2089/perl       
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      1409/smbd       
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      18415/apache2   
tcp6       0      0 :::22                   :::*                    LISTEN      1781/sshd       
tcp6       0      0 :::25                   :::*                    LISTEN      2016/master     
tcp6       0      0 ::1:6010                :::*                    LISTEN      12921/1         
tcp6       0      0 :::443                  :::*                    LISTEN      18415/apache2   
tcp6       0      0 ::1:6011                :::*                    LISTEN      16973/4         
tcp6       0      0 :::445                  :::*                    LISTEN      1409/smbd       
tcp6       0      0 :::139                  :::*                    LISTEN      1409/smbd       
udp        0      0 xx.xx.xx.xx:123       0.0.0.0:*                           2355/ntpd       
udp        0      0 127.0.0.1:123           0.0.0.0:*                           2355/ntpd       
udp        0      0 0.0.0.0:123             0.0.0.0:*                           2355/ntpd       
udp        0      0 10.47.105.255:137       0.0.0.0:*                           1895/nmbd       
udp        0      0 xx.xx.xx.xx:137       0.0.0.0:*                           1895/nmbd       
udp        0      0 0.0.0.0:137             0.0.0.0:*                           1895/nmbd       
udp        0      0 10.47.105.255:138       0.0.0.0:*                           1895/nmbd       
udp        0      0 xx.xx.xx.xx:138       0.0.0.0:*                           1895/nmbd       
udp        0      0 0.0.0.0:138             0.0.0.0:*                           1895/nmbd       
udp        0      0 0.0.0.0:161             0.0.0.0:*                           2049/snmpd      
udp        0      0 0.0.0.0:39786           0.0.0.0:*                           2049/snmpd      
udp6       0      0 fe80::4603:a7ff:fe6:123 :::*                                2355/ntpd       
udp6       0      0 ::1:123                 :::*                                2355/ntpd       
udp6       0      0 :::123                  :::*                                2355/ntpd       
udp6       0      0 ::1:161                 :::*                                2049/snmpd  



Thank you.

**Comment by CoalaJoe** [comment]
Hm... Can you serve a simple html site through your `ProxyPass`?

**Comment by eduardo5000** [comment]
Websocket comunicate through port 80, and when arrive to the server the proxy redirects their petitions to 8090 port. All of that with the apache proxy module:

<Location "/wsauthoban">
ProxyPass "ws://server.intra:8090/"

We are going to try than and I'll tell you.

**Comment by eduardo5000** [comment]
I have tried.

I have changed location proxy by:

<Location "/pruebaredireccion123">
                ProxyPass "http://www.spanishdict.com/translate/prueba"
        </Location>

And we have received:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.


Then it's nos possible.

Thank you

**Comment by eduardo5000** [comment]
In error.log:


Mon Jul 03 12:04:40.277296 2017] [proxy:warn] [pid 28814] [client 10.33.29.42:30908] AH01144: No protocol handler was valid for the URL /pruebaredireccion123.
 If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule.

**Comment by CoalaJoe** [comment]
Maybe the Proxy Module has problems with websockets???
Did you try this module: https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html

**Comment by eduardo5000** [comment]
For websockets works is necessary have mod_proxy and mod_proxy_wstunnel. In apache documentation says: This module requires the service of mod_proxy. Or ¿can we use only one of these? ¿can we disable mod_proxy and only have mod_proxy_wstunnel and it works?

**Comment by CoalaJoe** [comment]
I think you need both.
What version of apache do you use?

**Comment by eduardo5000** [comment]
Apache 2.4.7

**Comment by CoalaJoe** [comment]
Try adding the `ProxyPassReverse`

**Comment by eduardo5000** [comment]
We have tried and with same results. :-(

**Comment by CoalaJoe** [comment]
Did you try the `DSO version of mod_proxy`?

**Comment by eduardo5000** [comment]
It seem that it is not websocket, mod_proxy,... 

We are disabled mod_proxy, proxy_tunnel, websocket,... and keep doing the same.

We are investigating why apache stop responding randomly.

If you have some idea... thxs !

**Comment by CoalaJoe** [comment]
Do other connections work fine?

**Comment by eduardo5000** [comment]
All the cores raise 100% when apache is hanging...

**Comment by CoalaJoe** [comment]
Hm... Circular reference?

**Comment by eduardo5000** [comment]
We put this in virtual host:

# Redirection Loop Protection
        RewriteEngine on
        RewriteCond %{ENV:REDIRECT_STATUS} 200
        RewriteRule .* - [L]

Now we're expectating to next hang.

**Comment by CoalaJoe** [comment]
Did it change anything?

**Comment by eduardo5000** [comment]
No. 

We want make a script that restart server when it hangs, but wget, curl, etc... command line works when apache not serving.

**Comment by CoalaJoe** [comment]
And you want to redirect the websocket-request from the apache2 server to another server, right?
