### ISSUE TITLE
List subscribers

### ISSUE THREAD

**Issue by ewertoncode** [GeniusesOfSymfony/WebSocketBundle#25]
Hi!

How can I return to my view (client side) all clients subscribeds in my topic?

Can you help me @ProPheT777 ?

Thank you!

**Comment by ProPheT777** [comment]
This is in the docs https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/TopicSetup.md

#### How iterate over my subscribers ?

`Topic` implements `IteratorAggregate`, you can iterate over subscribers present in your topic. Client are reprensented by `ConnectionInterface`

```php
/** @var ConnectionInterface $client **/
foreach($topic as $client){
    //Do stuff ...
}
```

And advanced example with auth user here : https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/SessionSetup.md#retrieve-current-user

**Comment by ewertoncode** [comment]
Sorry, 
but I get the current user such: $this->getCurrentUser($connection), works fine.

However, I try:

```javascript
/** @var ConnectionInterface $client **/
foreach($topic as $client){
       $clients[] = $this->getCurrentUser($client);
}
```
and dont return the current user.

**Comment by ProPheT777** [comment]
Yes it's normal with this line :

```php
$clients[] = $this->getCurrentUser($client);
```

You retrieve subsribers of your channel

**Comment by ewertoncode** [comment]
Yes, is this that I want, receive all subscribers! But this is not what is happening.

Return this (console.log(payload)):

>
Object {msg: "ewerton is conected.", qtd_subs: 1, clients: Array[1]}
clients: Array[1]
0: Object
__proto__: Object
msg: "ewerton is conected."
qtd_subs: 1

view better: https://db.tt/Z72gAiDw
my code:
```

public function onSubscribe(ConnectionInterface $connection, Topic $topic, WampRequest $request)
    {

        $clients = array();

        /** @var ConnectionInterface $client **/
        foreach($topic as $client){
            $clients[] = $this->getCurrentUser($client);
        }


        $this->currentuser = $this->getCurrentUser($connection);

        $topic->broadcast([
            'msg' => '<div class="alert alert-info" role="alert"><b>'.$this->currentuser . "</b> entrou no chat.</div>",
            'qtd_subs' => $topic->count(),
            'clients' => $clients
        ]);
    }

**Comment by ProPheT777** [comment]
Yep, that work as expected.

> qtd_subs: 1 
You have one subscriber

And in your json object you have 
> clients: Array[1]

if you do something like :

```js
for(i in object.clients) {
    var user = object.clients[i];
    console.log(user, user.username); //here is your user
}
```

**Comment by ewertoncode** [comment]
Thank you for your attention! 
But my result is 'strange':

```
session.subscribe("chat/channel", function(uri, payload){
                    $('#mensagens').append("<p>"+payload.msg+"</p>");
                    for(i in payload.clients) {
                        var user = payload.clients[i];
                        console.log(user, user.username); //here is your user|subscriber
                    }
                });
```

There are two users logged:

```
Object {} undefined
chat:149 Object {} undefined

**Comment by ProPheT777** [comment]
Can you var_dump() directly from your topic when you retrieve your authenticated user and exit() after the foreach. Then restart your websocket server and paste the console output here please (when var_dump() is reached).
Thanks 
Le 30 juin 2015 02:36, Éwerton Cardoso <notifications@github.com> a écrit :Thank you for your attention! 
But my result is 'strange':

session.subscribe("chat/channel", function(uri, payload){
                    $('#mensagens').append("<p>"+payload.msg+"</p>");
                    for(i in payload.clients) {
                        var user = payload.clients[i];
                        console.log(user, user.username); //here is your user|subscriber
                    }
                });


There are two users logged:

Object {} undefined
chat:149 Object {} undefined

**Comment by ewertoncode** [comment]
Ok! Thaks!

I can see now, I should have called the method getUsername():
```php
/** @var ConnectionInterface $client **/
        foreach($topic as $client){
            $clients[] = $this->getCurrentUser($client)->getUsername();
        }
```

Thanks a lot man!

(you can close)
