### ISSUE TITLE
How to block connections from other domains

### ISSUE THREAD

**Issue by anacona16** [GeniusesOfSymfony/WebSocketBundle#256]
I was looking for a way to prevent connections to my websocket endpoint, but I didn't find a solution.

What is the recommended way to prevent connections from other domains?

I'm using the basic configuration as bundle mention.

**Comment by BunnyHolder** [comment]
At the end of the day you can not block access from other domains. You only can make it harder. For example, check if session exists. Or add login system.

**Comment by ProPheT777** [comment]
https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/OriginCheck.md

**Comment by BunnyHolder** [comment]
> https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/OriginCheck.md

Only if browser supports it. You can disable it from browser too.

**Comment by ProPheT777** [comment]
I'm not sure to understand. The browser sends the "origin" header which can be checked by the application. But there is no support problem or "disability" is a part of http protocol. 

I think you are speaking about the "same-origin" policy ? Wich is  very different.  websockets can cross domain communication, and they are not limited by the SOP (Same Origin Policy). Also CORS does not apply.

**Comment by BunnyHolder** [comment]
Application sends origin headers, and browser checks it. You can send I think anywhere those headers I think.

**Comment by anacona16** [comment]
Thanks @ProPheT777 it works.
