### ISSUE TITLE
Custom Assetic path

### ISSUE THREAD

**Issue by agemmell** [GeniusesOfSymfony/WebSocketBundle#26]
I like Assetic to dump files in a custom path (i.e. js/compiled/ - like in the Symfony docs) but I have a problem with the WebSocketBundle.  I am overriding your GosWebSocketBundle::client.html.twig with my own that includes the "output" option, like this:

```
{% javascripts
    '@GosWebSocketBundle/Resources/public/js/vendor/autobahn.min.js'
    '@GosWebSocketBundle/Resources/public/js/gos_web_socket_client.js'
    output='js/compiled/gos_websockets.js'
%}
    <script type="text/javascript" src="{{ asset_url }}"></script>
{% endjavascripts %}
```

However, now when I run assetic:dump the files are placed in TWO directories:

```
$ php app/console assetic:dump --env=prod --no-debug
Dumping all prod assets.
Debug mode is off.

14:18:06 [file+] /var/www/site/server/app/../web/js/6eb8fb0.js
14:18:06 [file+] /var/www/site/server/app/../web/js/compiled/gos_websockets.js
```

How do I stop your bundle from writing its javascript to my js/ folder?

**Comment by ProPheT777** [comment]
I'll look into this problem this week-end
 to allow that ;) 
Le 30 juin 2015 23:19, Alex Gemmell <notifications@github.com> a écrit :I like Assetic to dump files in a custom path (i.e. js/compiled/ - like in the Symfony docs) but I have a problem with the WebSocketBundle.  I am overriding your GosWebSocketBundle::client.html.twig with my own that includes the "output" option, like this:

{% javascripts
    '@GosWebSocketBundle/Resources/public/js/vendor/autobahn.min.js'
    '@GosWebSocketBundle/Resources/public/js/gos_web_socket_client.js'
    output='js/compiled/gos_websockets.js'
%}
    <script type="text/javascript" src="{{ asset_url }}"></script>
{% endjavascripts %}


However, now when I run assetic:dump the files are placed in TWO directories:

$ php app/console assetic:dump --env=prod --no-debug
Dumping all prod assets.
Debug mode is off.

14:18:06 [file+] /var/www/site/server/app/../web/js/6eb8fb0.js
14:18:06 [file+] /var/www/site/server/app/../web/js/compiled/gos_websockets.js


How do I stop your bundle from writing its javascript to my js/ folder?

**Comment by ProPheT777** [comment]
Done ;) look at #32

**Comment by agemmell** [comment]
Great!  Thank you!
