### ISSUE TITLE
websocket.ERROR: Connection error occurred Warning: SessionHandler::read(): Session is not active

### ISSUE THREAD

**Issue by JsonGuy** [GeniusesOfSymfony/WebSocketBundle#264]
Hello, issue described here.

https://stackoverflow.com/questions/47280411/websocket-error-connection-error-occurred-warning-sessionhandlerread-sess

**Comment by JsonGuy** [comment]
Okey, finally figured it out, as in documentation (took time to find it), you cannot use native session handlers with ratchet, all i had to do, was:

`session_handler: "@session.handler.pdo"`

and everything works as expected.

**Comment by kat15** [comment]
Hi,
Could u show all config? what did u changed?
I have framework session set to session.handler.native_file.
