### ISSUE TITLE
Send message to a client using PeriodicFunctionService

### ISSUE THREAD

**Issue by cristhianfernandez01** [GeniusesOfSymfony/WebSocketBundle#27]
Hi, how are you. I wanted to ask how I can send messages from the server to a specific client using PeriodicFunctionsService. I need to send to the client monitoring in real time. The documentation explains that the injection of a TopicService be performed.But I do not understand how I can do it. Please could you show me some example of this? Thank you very much.

**Comment by ProPheT777** [comment]
Hey,  
Currently periodic timer is only for internal work. But it's an interesting feature to plug a periodic timer inside topic. I'll look into this feature this week-end.
At the moment you can achieve that by publishing each x second from the client side.

**Comment by cristhianfernandez01** [comment]
Thanks for your prompt response. I would be very grateful that you could add that functionality. I'll be waiting for it! Regards.

**Comment by ProPheT777** [comment]
It's now available on dev-master ! 

Check the docs here : https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/TopicSetup.md#periodic-timer-topic--connection 

Feel free to contribute on docs if something is not clear !

**Comment by cristhianfernandez01** [comment]
Genius! Thank you very much for adding this functionality. I'll try everything to see how I can use it. The documentation seems very good, questions or improvement'll make you a consultation. Greetings and thanks again.
