### ISSUE TITLE
Symfony4 support and fix issues

### ISSUE THREAD

**Issue by Kronhyx** [GeniusesOfSymfony/WebSocketBundle#270]
Symfony 4 has been released and the WebSocket package has many obsolete calls and dependency injection has changed. When are you going to do something about it?

**Comment by ProPheT777** [comment]
Hey, 

Symfony has been released yesterday night, master should work on. If any issue comes up, send a pull request to fix. As soon as the bundle work good on sf4, I'll tag it

**Comment by darthf1** [comment]
When i run `composer require "gos/pubsub-router-bundle":"master@dev"`

I get:
```

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for gos/pubsub-router-bundle master@dev -> satisfiable by gos/pubsub-router-bundle[dev-master].
    - gos/pubsub-router-bundle dev-master requires symfony/framework-bundle ~2.3|~3.0 -> satisfiable by symfony/framework-bundle[2.3.x-dev........
etc,
```

Does this mean the pubsub-router-bundle needs to be updates as well?

**Comment by darthf1** [comment]
Great. I just installed the dev-master version and got the following notice on `composer update`:

```
Script cache:clear returned with error code 1
!!
!!  In GosWebSocketExtension.php line 210:
!!
!!    Notice: Undefined index: server
!!
!!
!!
```

**Comment by neandher** [comment]
Hi, i installed the de-master version:

<pre>
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing gos/pubsub-router-bundle (dev-master 9ab694a): Downloading (100%)
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Symfony operations: 1 recipe (c7fc82baa4a12c006ca1fdd2f681e4db)
  - Configuring gos/pubsub-router-bundle (>=dev-master): From auto-generated recipe
Executing script cache:clear [OK]
Executing script assets:install --symlink --relative public [OK]
</pre>

Everything is fine, but the config file was not created. I think a contrib entry must be create in symfony recipes, just like stof doctrine extension have done for exmple: https://github.com/symfony/recipes-contrib/blob/master/stof/doctrine-extensions-bundle/1.2/config/packages/stof_doctrine_extensions.yaml

**Comment by sercul** [comment]
Hi, I have problem with Symfony 4 integration, routing file is pubsub is not loading.
Installed everything
```
'gos/web-socket-bundle                    dev-master '
'gos/pubsub-router-bundle                 v0.3.2'
```

Created file _/config/packages/gos_web_socket.yaml_ with content
```
gos_web_socket:
    server:
        port: 1337        #The port the socket server will listen on
        host: 127.0.0.1   #The host ip to bind to
        router:
           resources:
               - '%kernel.project_dir%/config/pubsub.yaml'
    topics:
        - "@app.topic.chat"
```
And file _'/config/pubsub.yaml'_ with content
`app_topic_chat:
    channel: 'app/chat/{first_user}/{second_user}'
    handler:
        callback: 'chat.topic' #related to the getName() of your topic
    requirements:
        first_user:
            pattern: '\d+' #accept all valid regex, don't put delimiters !
        second_user:
            pattern: '\d+'`

Getting always error 
`
!!  In DelegatingLoader.php line 37:
!!                                                                               
!!    Cannot load resource "/var/www/html/iumob-dating-cms/config/pubsub.yaml".  
`

**Comment by sercul** [comment]
Eh, problem was in naming. It was

        '%kernel.project_dir%/config/pubsub.yaml'

but need to be

        '%kernel.project_dir%/config/pubsub.yml'

so yml not yaml

**Comment by ProPheT777** [comment]
hey, I have released 1.8.12-rc1, now available, this also include the remove custom gos/ratchet to rely on the official one.

**Comment by darthf1** [comment]
Thanks! I just installed v1.8.12-rc1, got the following error message:

> λ composer require gos/web-socket-bundle:v1.8.12-rc1
> ./composer.json has been updated
> Loading composer repositories with package information                                                                                                                                  Updating dependencies (including require-dev)
> Package operations: 4 installs, 0 updates, 0 removals
>   - Installing gos/pnctl-event-loop-emitter (v0.1.5): Loading from cache
>   - Installing gos/websocket-client (v0.1.2): Loading from cache
>   - Installing gos/pubsub-router-bundle (v0.3.2): Loading from cache
>   - Installing gos/web-socket-bundle (v1.8.12-rc1): Loading from cache
> Writing lock file
> Generating autoload files
> ocramius/package-versions:  Generating version class...
> ocramius/package-versions: ...done generating version class
> Symfony operations: 2 recipes (48d730473f0188c7e4b94b8e1eee104e)
>   - Configuring gos/pubsub-router-bundle (>=v0.3.2): From auto-generated recipe
>   - Configuring gos/web-socket-bundle (>=v1.8.12-rc1): From auto-generated recipe
> Executing script cache:clear [KO]
>  [KO]
> Script cache:clear returned with error code 1
> !!
> !!  In GosWebSocketExtension.php line 210:
> !!
> !!    Notice: Undefined index: server
> !!
> !!
> !!

**Comment by darthf1** [comment]
When I run a command, I get a new error message on top of my normal output:

```
 [WARNING] Some commands could not be registered:


In getGosWebSocketServer_WampApplicationService.php line 8:

  Maximum function nesting level of '512' reached, aborting!


In getGosWebSocketServer_WampApplicationService.php line 8:

  Maximum function nesting level of '512' reached, aborting!
```

**Comment by ProPheT777** [comment]
```
WebsocketAppDemo git/master*  
❯ ./app/console gos:websocket:server
17:07:25 INFO      [websocket] Starting web socket [] []
17:07:25 INFO      [websocket] Launching Ratchet on 127.0.0.1:1337 PID: 23297 [] []
^C17:07:39 NOTICE    [websocket] Stopping server ... [] []
17:07:39 NOTICE    [websocket] Server stopped! [] []
```

get it work with minimal configuration, see websocketappDemo

**Comment by ProPheT777** [comment]
1.8.12-rc1 is now available with the support of lazy loaded command console (apply from sf >= 3.4)

**Comment by darthf1** [comment]
RC2 fixes the issue with the warning on other symfony commands!

However, i'm unable to start the server. I get: 

```
λ php bin/console gos:websocket:server
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Maximum function nesting level of '512' reached, aborting! in project\vendor\gos\web-socket-bundle\Server\App\Registry\RpcRegistry.php:17
Stack trace:
#0 project\var\cache\dev\ContainerONWRX5N\getGosWebSocketServer_WampApplicationService.php(15): Gos\Bundle\WebSocketBundle\Server\App\Registry\RpcRegistry->__construct()
#1 project\var\cache\dev\ContainerONWRX5N\srcDevDebugProjectContainer.php(318): require('D:\\www\\coinexch...')
#2 project\var\cache\dev\ContainerONWRX5N\getGosWebSocket_Wamp_TopicManagerService.php(13): ContainerONWRX5N\srcDevDebugProjectContainer->load('D:\\www\\coinexch...')
#3 project\var\cache\dev\ContainerONWRX5N\srcDevDebugProjectContainer.php(318): require('D:\\www\\coinexch...')
#4 project\var\cache\dev\ContainerONWRX5N\getGosWebSocket_Topic_DispatcherService.php(13): ContainerONWRX5N\srcDevDebugProjectContainer->load('D:\\www\\coinexch...')
#5 D:\www\ in project\vendor\gos\web-socket-bundle\Server\App\Registry\RpcRegistry.php on line 17

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Maximum function nesting level of '512' reached, aborting! in project\vendor\gos\web-socket-bundle\Server\App\Registry\RpcRegistry.php on line 17

Symfony\Component\Debug\Exception\FatalThrowableError: Maximum function nesting level of '512' reached, aborting! in project\vendor\gos\web-socket-bundle\Server\App\Registry\RpcRegistry.php on line 17

Call Stack:
    0.1356    3209040   1. Symfony\Component\Debug\ErrorHandler->handleException() project\vendor\symfony\debug\ErrorHandler.php:0
```

My `composer.json`:

```
    "require": {
        "php": "^7.1.3",
        "andreas-glaser/php-helpers": "^1.1",
        "ccxt/ccxt": "^1.10",
        "gos/web-socket-bundle": "v1.8.12-rc2",
        "guzzlehttp/guzzle": "^6.3",
        "ocramius/proxy-manager": "2.1.*",
        "ratchet/pawl": "^0.3.1",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/asset": "^4.0",
        "symfony/console": "^4.0",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "^4.0",
        "symfony/lts": "^4@dev",
        "symfony/maker-bundle": "^1.0",
        "symfony/monolog-bundle": "^3.1",
        "symfony/orm-pack": "^1.0",
        "symfony/security-bundle": "^4.0",
        "symfony/stopwatch": "^4.0",
        "symfony/twig-bundle": "^4.0",
        "symfony/web-server-bundle": "^4.0",
        "symfony/webpack-encore-pack": "^1.0",
        "symfony/yaml": "^4.0",
        "voryx/thruway": "^0.5.1"
    },
    "require-dev": {
        "doctrine/doctrine-fixtures-bundle": "^3.0",
        "symfony/debug-bundle": "^4.0",
        "symfony/dotenv": "^4.0",
        "symfony/profiler-pack": "^1.0"
    },
```

**Comment by ProPheT777** [comment]
@darthf1 are you running with xdebug? it's look like you reach xdebug limit.

http://www.kitpages.fr/fr/cms/154/nesting-level-et-xdebug

It's related to the project.

**Comment by neandher** [comment]
I get:
<pre>
λ php72 bin/console gos:websocket:server
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in C:\docker\sf4\var\cache\dev\ContainerLddrsdN\srcDevDebugProjectContainer.php on line 256

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in C:\docker\sf4\var\cache\dev\ContainerLddrsdN\srcDevDebugProjectContainer.php on line 256
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0
</pre>

memory_limit=1024M

**Comment by ProPheT777** [comment]
if you downgrade to stable version, do you also get this issue ?

**Comment by neandher** [comment]
@ProPheT777 In Symfony 3.4 with stable version 1.8.11 and php 7.0 or php 7.2 works fine. The issue happens only in Symfony 4 with ^1.8.12

**Comment by ProPheT777** [comment]
new rc tagged ! Anyone have the same issue as @neandher ?

**Comment by rogierkn** [comment]
Tried it yesterday with latest rc and also had the error neandher received

**Comment by tkuska** [comment]
got the same.
^1.8.12 works fine with symfony 3.4 but crashes with 4.0

**Comment by ProPheT777** [comment]
We have to figured out where come from the leak, it's annoying, and I dont have time those days ...

**Comment by tkuska** [comment]
It looks like the reason for this is circural dependencies mentioned in #292.
I will handle this tomorrow.

**Comment by tkuska** [comment]
added quick fix in #296

**Comment by ProPheT777** [comment]
thanks very much @tkuska i have merged and released it as new RC

**Comment by ProPheT777** [comment]
@neandher @rogierkn do you still have memory leak issue with latest rc ?

**Comment by ProPheT777** [comment]
any news with about memory leak and last rc ? If it's fix, we are ready to tag a new version and be compatible with symfony 4 ! :pray:

**Comment by rogierkn** [comment]
@ProPheT777 I will check it in a few hours and let you know

**Comment by rogierkn** [comment]
@ProPheT777 Created a new S4 project. Works like a charm!

**Comment by ProPheT777** [comment]
nice to hear

**Comment by mohamedyasser** [comment]
@rogierkn @ProPheT777 
S$ ERROR in session.subscribe after connect to ws server 
console log 
Disconnected for Connection was closed properly [WS-1007: ] with code 0

**Comment by itscaro** [comment]
Please support yaml extension as well

https://github.com/GeniusesOfSymfony/PubSubRouterBundle/pull/18

Thank you

**Comment by Kronhyx** [comment]
¿¿can close this issue??
