### ISSUE TITLE
Running the WebSocket server on production

### ISSUE THREAD

**Issue by BraveFart** [GeniusesOfSymfony/WebSocketBundle#278]
Hello all,

I have a very simple Symfony application that uses WebSocletBundle, It currently resides on a Linux server working under Apache2, When I connect to the server using PuTTY and run the WebSocket server with:
 `php console gos:websocket:server --env=prod`
the server starts and everything work perfectly, My problem now is that I don't know how to make the server run continuously even when I close PuTTY or drop the connection.
I looked around and couldn't find any pointers on how to do that for Apache and Linux!

**Comment by ProPheT777** [comment]
You can use following application to achieve that : `screen` `supervisord` or `systemd` if you have a recent distribution

**Comment by BraveFart** [comment]
@ProPheT777 Thank you! `screen` did the job!

**Comment by qlerebours** [comment]
Note that you could also use `nohup` and `&` to make it work in backgroud:
`nohup php console gos:websocket:server --env=prod &`

https://linux.101hacks.com/unix/nohup-command/
