### ISSUE TITLE
The profiler template "GosWebSocketBundle:Collector:websocket.html.twig" for data collector "websocket" does not exist.

### ISSUE THREAD

**Issue by nusje2000** [GeniusesOfSymfony/WebSocketBundle#282]
I just started using this package but after installing I encountered this error when loading the symfony profiler, any suggestions ?

**Comment by Kronhyx** [comment]
when pre-release are fully released the bug will be fixed, im using *"gos/web-socket-bundle": "@dev",*
in my composer.json
(sorry for my bad english)

**Comment by nusje2000** [comment]
Ow, no problem. May I know what causes the bug to happen ?

**Comment by Kronhyx** [comment]
### Resources/config/services/services.yml
gos_web_socket.data_collector:
`//................`
        tags:
            - { name: data_collector, template: **'@ GosWebSocket/Collector/websocket.html.twig'**, id: 'websocket' }
            - { name: data_collector, template: **'GosWebSocketBundle:Collector:websocket.html.twig'**, id: 'websocket' }

**Comment by nusje2000** [comment]
Ahh

**Comment by Kronhyx** [comment]
@nusje2000 , please, close this issue!
