### ISSUE TITLE
Php 7.2.2 Fatal error TopicDisapacher.php

### ISSUE THREAD

**Issue by Vlad-Iliescu** [GeniusesOfSymfony/WebSocketBundle#289]
#### Error Message:
`PHP Fatal error:  Declaration of GosBundleWebSocketBundleServerAppDispatcherTopicDispatcher_000000004f5815740000000021642ffeadbc69972899ba3cc1aebb9d3961fbd7::dispatch($calledMethod, Ratchet\ConnectionInterface $conn, Ratchet\Wamp\Topic $topic, Gos\Bundle\WebSocketBundle\Router\WampRequest $request, $payload = NULL, $exclude = NULL, $eligible = NULL, $provider = NULL) must be compatible with Gos\Bundle\WebSocketBundle\Server\App\Dispatcher\TopicDispatcher::dispatch($calledMethod, ?Ratchet\ConnectionInterface $conn, Ratchet\Wamp\Topic $topic, Gos\Bundle\WebSocketBundle\Router\WampRequest $request, $payload = NULL, $exclude = NULL, $eligible = NULL, $provider = NULL) in [...]/var/cache/dev/appDevDebugProjectContainer.php on line 7494`

#### Environment:
* `gos/web-socket-bundle` v1.8.11
* `symfony/symfony` v3.2.4
* Ubuntu 16.04
* PHP 7.2.2

#### Some Debugging:
1. In the [TopicDispatcherInterface.php](https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/a26b71e9014a73b95ddbb02a813157563a296a48/Server/App/Dispatcher/TopicDispatcherInterface.php#L53) the `dispatch` method is defined as `public function dispatch($calledMethod, ConnectionInterface $conn, Topic $topic, WampRequest $request, $payload = null, $exclude = null, $eligible = null);`
2. However in the [TopicDispatcher.php](https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/a26b71e9014a73b95ddbb02a813157563a296a48/Server/App/Dispatcher/TopicDispatcher.php#L130) is implemented as such `public function dispatch($calledMethod, ConnectionInterface $conn = null, Topic $topic, WampRequest $request, $payload = null, $exclude = null, $eligible = null, $provider = null)` with **`ConnectionInterface $conn = null`**
3. When Symofny creates `[...]/var/cache/dev/appDevDebugProjectContainer.php` it defines the method as `public function dispatch($calledMethod, \Ratchet\ConnectionInterface $conn, \Ratchet\Wamp\Topic $topic, \Gos\Bundle\WebSocketBundle\Router\WampRequest $request, $payload = null, $exclude = null, $eligible = null, $provider = null)` this time respecting the interface `TopicDispatcherInterface` but not the class `TopicDispatcher`. (notice the **?** in the Error message)

IMHO the problem here is that the `TopicDispatcher` does not respect the interface `TopicDispatcherInterface` and can be fixed by removing the default `null` from the declaration of `dispatch`. 
Will this removal cause any issue down the line?

**Comment by semin-lev** [comment]
The same with v1.8.12, working only with 1.8.12-rc5

**Comment by Gerben321** [comment]
Still not working in 1.8.13.

**Comment by ProPheT777** [comment]
Can you try with : 1.9.0-rc2 I just released it, it should be fixed

**Comment by vigen-baghdasaryan-im** [comment]
1.9.0-rc2 works for me

**Comment by adrianrosalesc** [comment]
1.9.0-rc2 is working fine for this particular issue but this version still has the problem with "Fix Notice on windows that prevent start of service @sadortun", this is fixed on 1.9.0-rc3, but this rc3 has the same issue was fixed in rc2...In TopicDispatcher
some advices?
