### ISSUE TITLE
Session Sharing Broken in 1.8.12

### ISSUE THREAD

**Issue by mbabker** [GeniusesOfSymfony/WebSocketBundle#297]
Unless I've missed something obvious, the shared session setup as described in https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/SessionSetup.md does not work on the 1.8.12 RC.  For this functionality to work, it seems to rely on being able to set the hostname as the websocket system's host, but https://github.com/reactphp/socket/pull/66 changed the underlying library to enforce an IP address.

**Comment by tkuska** [comment]
it works :)
i had the same problem, it forces to use IP in PHP config, but session depends on  cookies used by javascript client in twig template.
This example https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/ClientSetup.md#step-2-gos_web_socket_clientjs uses IP address but you should use your domain there to make it work.
`var websocket = WS.connect("ws://your.domain:8080");` or just use IP in web browser :)

**Comment by mbabker** [comment]
Well, that breaks the Twig globals exposed through the shared config option then (because you basically have to use IP for server config and hostname for the client).  Either way I can make this work now.

**Comment by tkuska** [comment]
true :)
