### ISSUE TITLE
Publish in other topic

### ISSUE THREAD

**Issue by ewertoncode** [GeniusesOfSymfony/WebSocketBundle#30]
Hi!

I'm subscribed in a topic (chat/channel/room1, for exemple), is possible publish in other topic (chat/xpto) from inside this topic?

Thanks!!

**Comment by ProPheT777** [comment]
Yes you can, 

you will need WampRouter service to achieve that (@gos_web_socket.router.wamp)

```php
    /**
     * @param WampRouter                 $wampRouter
     */
    public function __construct(WampRouter $wampRouter)
    {
        $this->wampRouter = $wampRouter;
    }
```

Choose on wich event you want do that :

```php
$connection->event($this->wampRouter->generate('target_topic_route_name'), 'message'');
```

**Comment by ewertoncode** [comment]
Sorry, but I don't understand very well...

I should to do: 
``` php
public function onPublish(ConnectionInterface $connection, Topic $topic, WampRequest $request, $event, array $exclude, array $eligible)
    {
...
//My condition for it ...
$connection->send($this->wampRouter->generate('chat_topic', ['room' => 'all']), ['msg' => 'notification']); 

//Send the message for all subscribers this private topic
$topic->broadcast(
            [
                'msg' => "<b>".$this->getCurrentUser($connection)->getUsername()."</b>: ".$event,
            ]
        );
...

```
My problem is: I have a chat private, I would like, if one of the participants from chat is not present, notify it.

Thanks!
Sorry to bother @ProPheT777 ...

**Comment by ProPheT777** [comment]
You don't need that so, they are on the same topic right ? If yes

You can simply send notification message type when unsubscribe is called. From $connection of unsubscribe you can get the user and then generate your notification. Add just an entry "type" in your response to deal in your front end. 

```php
'type' => 'notification', 'msg' => "<b>".$this->getCurrentUser($connection)->getUsername()."</b>: ".$event,
```

You should also look at the lastest version, Auth user have been improved and `getCurrentUser` is deprecated. Look #28 

Other thing in the lastest version, when connection is closed by client it automatically call unsubscribe of each subsribed topic #31

**Comment by ewertoncode** [comment]
They are not on the same topic.

I have a general chat (chat/chanel/all) and individual chat (chat/chanel/10x13: indicating that the conversation is between userId 10 e 13). When a user starts the chat, I would like to notify you (until he subscribe this private chat), that there is someone talking to him.

I did the update to the new version, the $this->clientManipulator->getClient ($connection), worked fine.

Thank you again!!! :D

**Comment by ProPheT777** [comment]
Actually you can't but with ZMQ (#36) we can a way to achieve that ;)

**Comment by ProPheT777** [comment]
I'm on it :)

**Comment by ProPheT777** [comment]
Take a look at #38
