### ISSUE TITLE
Send parameters or args on subscribe, connect or publish

### ISSUE THREAD

**Issue by azuniaga** [GeniusesOfSymfony/WebSocketBundle#303]
Hi  there! 
My problem is that I need to send some parameters when subscribe clients or when publish, and receive this parameters in the WampRequest or something to make some validations. When I print my wampp request , I'm getting this:
object(Gos\Bundle\WebSocketBundle\Router\WampRequest)#913 (4) {
  ["attributes":protected]=>
  object(Symfony\Component\HttpFoundation\ParameterBag)#916 (1) {
    ["parameters":protected]=>
    array(0) {
    }
  }
  ["route":protected]=>
  object(Gos\Bundle\PubSubRouterBundle\Router\Route)#138 (5) {
    ["pattern":protected]=>
    string(31) "app/chat/{channel_slug}"
    ["callback":protected]=>
    string(18) "chat.channel.topic"
    ["args":protected]=>
    array(0) {
    }
    ["requirements":protected]=>
    array(0) {
    }
    ["name":protected]=>
    string(19) ".chat_cahnnel_topic"
  }
  ["routeName":protected]=>
  string(19) ".chat_cahnnel_topic"
  ["matched":protected]=>
  string(12) "app/chat/1"
}
so I'd like to know how can I send this "args" from client side with js??

 
Thanks! :)

**Comment by fnash** [comment]
@azuniaga did you find a solution?
In the WampRequest, I have the route name, the matched route, but the $attributes field is empty :(
