### ISSUE TITLE
CLI command blocking / not starting in background

### ISSUE THREAD

**Issue by darovic** [GeniusesOfSymfony/WebSocketBundle#310]
Hi folks, when running ``php bin/console gos:websocket:server`` the command never returns and blocks the terminal. From the documentation it appears that this should not happen, which is why I am raising the issue.

It is running using php 7.2 on ubuntu 16.04 on WSL (Windows 10 1709 build 16299.371). 

To confirm, the server does run - windows indicates a listener on the configured IP and port via netstat while the command is active, and none when it is not. I've rotated this through ports 7000, 7100, and 8080. Running on port 80 returns an error because Apache is listening on it, as it should.

I can't seem to find any logs or errors. It's a minor issue happening on my dev environment, a second terminal or a screen works around it.

I spent a good few hours before thinking to check if anything was listening via the windows command prompt so, hopefully this helps.

**Comment by ProPheT777** [comment]
Hey

> From the documentation it appears that this should not happen, which is why I am raising the issue.

Where ? it's not, you should use supervisord or something like that, there is no daemonize built in
