### ISSUE TITLE
New docs

### ISSUE THREAD

**Issue by mldevIT** [GeniusesOfSymfony/WebSocketBundle#312]
Please update your docs and add step by step install instruction.
I lose many time for seting my configs.
Please add more comments to your code in config file.

**Comment by ProPheT777** [comment]
You can submit PR with additions where you got pain points, for me it's crystal clear as creator, only community is able to add things that are harder for her. 

If you loose time, i'm sorry, contribute back and improve documentations about your experience to improve your next peers :)
