### ISSUE TITLE
iOS - Swift client library

### ISSUE THREAD

**Issue by arkader** [GeniusesOfSymfony/WebSocketBundle#313]
Hello everyone, 

I'm a Swift iOS Developer, and I don't know anything about Symfony. (I'm sorry)
I'm having a hard time to connect to a remote server which uses WebSocketBundle.

By any chance, do you know which Swift client library support WebSocketBundle API?
Or could you ask your mobile developers, please?

Thank you for your help

**Comment by arkader** [comment]
Hi @bertrandserres 
My php developer is using https://github.com/ratchetphp/Ratchet instead.
This works great with Starscream (iOS)

**Comment by CoalaJoe** [comment]
@arkader This bundle is based on that library, so i'd guess the Starscream library will work with this bundle too.
