### ISSUE TITLE
Where to use {{ ws_client() }}

### ISSUE THREAD

**Issue by devkbsc** [GeniusesOfSymfony/WebSocketBundle#317]
Hello,
I am new developer for symfony and this bundle! 
I am trying to add the client interface for my chat application after i have successfully installed the server part!
I could lanch my server from windows cmd.

But i am lost of following the documentation. Where  i need to implement this function call? 

`{{ ws_client() }}`

**Comment by BunnyHolder** [comment]
It's a twig template function call. Add it to any template and checkout what it outputs.
