### ISSUE TITLE
WS Server - Error 426

### ISSUE THREAD

**Issue by devkbsc** [GeniusesOfSymfony/WebSocketBundle#318]
Hello,
I am using web socket bundle in my project. I have an error in launching the server. I couldn't open the client console for chatting.

- Version symfony : 3.4.11

I have installed , started server in cmd! 

> C:\>cd xampp\htdocs\hexagone
> 
> C:\xampp\htdocs\hexagone>php bin/console gos:websocket:server
> 10:53:09 INFO      [websocket] Starting web socket [] []
> 10:53:09 INFO      [websocket] Launching Ratchet on 127.0.0.1:8080 PID: 11904 [] []

And i opened this link on my browser

> http://127.0.0.1:8080/

And i have got this on browser

> Cette page ne fonctionne pas
> Si le problème persiste, contactez le propriétaire du site.
> HTTP ERROR 426

Le code source
View : 

```
<script src="{{ asset('GosWebSocketBundle/Resources/public/js/vendor/autobahn.min.js') }}"></script>
<script src="{{ asset('GosWebSocketBundle/Resources/public/js/gos_web_socket_client.js') }}"></script>

<script>
   var websocket = WS.connect("ws://127.0.0.1:8080"); 
   
   webSocket.on("socket/connect", function(session){
    //session is an Autobahn JS WAMP session.

    console.log("Successfully Connected!");
});

webSocket.on("socket/disconnect", function(error){
    //error provides us with some insight into the disconnection: error.reason and error.code

    console.log("Disconnected for " + error.reason + " with code " + error.code);
});
</script>
{{ ws_client() }}
```

**Comment by devkbsc** [comment]
Problem fixed! I have found the copy of the files in my web/ because i am using symfony 3.4

**Comment by Gradius30** [comment]
Hello. Im currently solving same issue. Would you mind explaining a little bit further what was the cause? Im trying to start WS server on VPS hosting - www.address.com:8080, that gives me the error 426.

**Comment by devkbsc** [comment]
@ahmedazizfr Hi, I havn't mentioned correct file path of gos_web_socket.js

Finally i have found it in my web folder! There is a copy done when installed the bundle! 

And i didn't mention the correct function name " ws_client()" previously!

**Comment by ahmedazizfr** [comment]
where are you write this code ?on ressources/views you create a twig file?
