### ISSUE TITLE
WampPusher response inside RPC call?

### ISSUE THREAD

**Issue by Gradius30** [GeniusesOfSymfony/WebSocketBundle#321]
Hello guys. So Ive come across this standard behavior where it is not possible to push to channel when processing RPC call.

Lets say I have RPC call that processes data and dispatches event. Listener on that event should create and push wamp channel response. However it seems that push is not formatted properly for response inside RPC call. 

Timeout after 60 seconds altho WampPusher->push() is called properly.
![image](https://user-images.githubusercontent.com/36446808/41203004-c33139ea-6cd1-11e8-98bb-b6da261492e8.png)

When calling push from **controller** like so everything works fine and it appears in subscriber.

```
public function abc( WampPusher $pusher){
        $user = $userManager->getUserBy([
            'urlId' => $urlId
        ]);

        $pusher->push([
            'hello' => 'new day'
        ], 'app.user_chat_group_handler.topic', [
            'user' => $user->getId()
        ]);
        die();
}
```

When calling the same from inside **RPC call**, it fails heavily..

```
public function getGroup(ConnectionInterface $connection, WampRequest $request, $params){
       $user = $this->getUser($connection);
        
       $this->pusher->push([
                        'hello' => 'new day'
                    ], 'app.user_chat_group_handler.topic', [
                        'user' => $user->getId()
                    ]);

//      return ['1'];
}
```

So im assuming this behavior is not supported and full-duplex websocket connection is impossible. Or am I missing something?

**Comment by ProPheT777** [comment]
hmm, from websocket server side, you don't need to push, you can directly respond to clients throught $connection

The time out come from the event loop, by call pusher you are blocking the loop when it's wait for the response, and it's this same loop that handle connection. So you are trying to make a new request on the server while you are blocking it.

**Comment by Gradius30** [comment]
That would be perfect solution but response doesnt go only to user that is calling via RPC. There are more users subscribed that need to receive response.

Its a primitive chat app:
- User1 sends msg via SendRPC
- User1,User2,User3 are waiting on ReceiveChannel to get response ASAP

I cant think of solution but duplicating the client connection somehow. Or can you?

**Comment by ProPheT777** [comment]
I think you are going into the wrong way, RPC are not intented to "publish" message, simply use pub/sub interface like described at the bottom of this page : https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/ClientSetup.md

```
webSocket.on("socket/connect", function(session){

    //the callback function in "subscribe" is called everytime an event is published in that channel.
    session.subscribe("acme/channel", function(uri, payload){
        console.log("Received message", payload.msg);
    });

    session.publish("acme/channel", "This is a message!");
})
```

**Comment by Gradius30** [comment]
Oh god. Youre right. All these codes messed up my head already... :D

**Comment by ProPheT777** [comment]
:D no problem
