### ISSUE TITLE
When will WebSocketBundle be available for Symfony 4?

### ISSUE THREAD

**Issue by JackFy** [GeniusesOfSymfony/WebSocketBundle#328]
I thought it would already be possible to use WebSocketBundle with Symfony 4 ...
When will this be possible?
Or what am I doing wrong, if it is already possible?

**Comment by vlachmilan** [comment]
I am running this bundle on Symfony 4.1 with no problems at all. What are your issues exactly?

**Comment by ghostika** [comment]
I suppose he meant that there is no recipe and if you want to install it with `composer require` it will fail.
@JackFy before you try to install, create a new config file in the `/config/packages/dev/web-socket.yaml` and place the default config into it.
Then do a `composer require` and it will be installed.

**Comment by vlachmilan** [comment]
@JackFy Did the solution proposed by @ghostika take an effect? Can we close this issue?

**Comment by klodoma** [comment]
@vlachmilan 

Hi, which version you use for Symfony 4.1? I can set it up, but it doesn't work. The client gets always disconnected. See #351

**Comment by ProPheT777** [comment]
As @mbabker answer in the related issue, you have a message that said your firewall is not configured on gos config.

I continue the topic on dedicated thread, I clode this one to avoid multi discussion. See you there
