### ISSUE TITLE
Server does not run with Symfony 4.1

### ISSUE THREAD

**Issue by murtho** [GeniusesOfSymfony/WebSocketBundle#333]
I'm want to run the server in a Symfony4 application.

Launching the server does not work.
I wonder if other people are running into the same issues?

This is the source code of my project: https://github.com/murtho/SuperSocket

**Comment by vlachmilan** [comment]
I am running this bundle under Symfony 4.1 more less without major issues. What do you mean by "launching the server"? Could you share your output while trying to start the WebSocket server?

**Comment by murtho** [comment]
When I run the command `php bin/console gos:websocket:server` from my terminal nothing happens. there is no output at all

I need to push Ctrl + C to exit the command.

**Comment by vlachmilan** [comment]
@murtho Hmm... that's strange. That suggests something might be wrong with the configuration. I'll clone your repo and look at it further when I'll be available.

**Comment by murtho** [comment]
In order to get output in your terminal, the monolog logger needs to be installed. I also managed to find out that in a virtual machine with vagrant/puphpet you'll need to configure your firewall to open the port you're listening to and the IP-address in the configuration needs to match the IP-address on the javascript library
