### ISSUE TITLE
Broken push since 1.9.0-rc2

### ISSUE THREAD

**Issue by alexismarquis** [GeniusesOfSymfony/WebSocketBundle#343]
It appears that #331 broke the push mecanism, since it calls the `dispatch` method with `null` as value for `$conn` argument.

See:
https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/f2787f3ad911a8c7b9aa820b97de8e4cc1ed4d33/Server/App/Dispatcher/TopicDispatcher.php#L91-L94

This causes the following error when trying to push:

> Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 2 passed to Gos\Bundle\WebSocketBundle\Server\App\Dispatcher\TopicDispatcher::dispatch() must be an instance of Ratchet\ConnectionInterface, null given, called in /var/www/html/vendor/gos/web-socket-bundle/Server/App/Dispatcher/TopicDispatcher.php on line 94 in /var/www/html/vendor/gos/web-socket-bundle/Server/App/Dispatcher/TopicDispatcher.php:135

I can see multiple ways to fix this, but if we want to keep php 5.6 comptatibilty we can either remove the type hinting or rearange the arguments.

I can make a pull request for this, which way is the best for you @ProPheT777 ?

**Comment by ProPheT777** [comment]
Hey!

Sorry for the delay, 5aa644c24167d42319b5b9cb8b23dc7eeae0b4f0 should fix it. Will be ship in 1.9.0-rc3.

It also drop support of php5, which EOL
