### ISSUE TITLE
Launch WebSocket Server in production without SSH Terminal command

### ISSUE THREAD

**Issue by zenstok** [GeniusesOfSymfony/WebSocketBundle#352]
Hi,

My server host can't maintain a ssh session with the server run command:
`php bin/console gos:websocket:server`
So i need to be able to run the websocket server in production without introducing anything.
I managed to do this with the [Symfony Process Component](https://symfony.com/doc/3.4/components/process.html)

`$process = new Process("php bin/console gos:websocket:server");`
`$process->setTimeout(3600);`
`$process->start();`

But the thing is, i've put this into a Controller which seems bad and i want this process to run only when the server is started/rebooted but i don't know where is that.

I've also read about Supervisor but the config file probably should be put by server host and also i don't know what command to execute in the following [template ](http://socketo.me/docs/deploy)considering Gos Bundle:

`[program:ratchet]`
**command                 = bash -c "ulimit -n 10000; exec /usr/bin/php ./bin/tutorial-terminal-chat.php"**
`process_name            = Ratchet`
`numprocs                = 1`
`autostart               = true`
`autorestart             = true`
`user                    = root`
`stdout_logfile          = ./logs/info.log`
`stdout_logfile_maxbytes = 1MB`
`stderr_logfile          = ./logs/error.log`
`stderr_logfile_maxbytes = 1MB`

**Comment by ProPheT777** [comment]
Take a look at this : https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/ShipInProduction.md

You need to proxy the process, it add overhead for nothing, plus you set $process->setTimeout(3600); on a long live process which result to kill it every one minute. 

Use supervisord or systemd to ensure that your process is alive and keep it alive. You can start many websocket server with different port and use nginx as reverse proxy to load balance across your websocket pool to ensure your service is still reachable even when a websocket process is restarted.

But please, don't use this : exec /usr/bin/php ./bin/tutorial-terminal-chat.php, use the command line given in the prod shipping docs ;)
