### ISSUE TITLE
SSL configuration problem

### ISSUE THREAD

**Issue by zenstok** [GeniusesOfSymfony/WebSocketBundle#356]
Hello,

I have a problem for the SSL configuration. I did it with stunnel using these settings:

`socket = l:TCP_NODELAY=1`
`socket = r:TCP_NODELAY=1`

`chroot = /var/run/stunnel4/`
`pid = /stunnel.pid`

`local = logbox.ro`

`[websockets]`
`accept = 8443`
`connect = logbox.ro:8080`

I didn't post the cert and key because my host configured them and i can't see the file.
The problem is that i don't receive any error message when connecting to wss://logbox.ro:8443 on the browser. I tried testing it using this website: https://www.websocket.org/echo.html and it did connect.

Any help will be appreciated.

**Comment by ProPheT777** [comment]
hello, 

I dont know if you post your full config, but it seems key and cert attribute are missing : 

```
# Certificate
cert = /my/way/to/ssl.crt
key = /my/way/to/not_crypted.key
```

You can take a look at this : https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/Ssl.md for more details. I hope it work :)

**Comment by zenstok** [comment]
Yes, i didn't post the full config because i told the server host to configure the paths for the cert and key as i don't know them. So they exist in the config file. The problem is i don't receive any error in browser's console  , even after waiting a long time and it doesn't connect, but it looks like if i use a third party like the website in the OP it says this:

'CONNECTED'
'RECEIVED: [0,"15980784235c1a5cb7c8fa3604598436",1,"Ratchet\/0.3.3"]'

**Comment by jimiero** [comment]
@zenstok have you ever managed to sort this, I have a similar issue.
