### ISSUE TITLE
How can I share events between my application and the running server?

### ISSUE THREAD

**Issue by parhamdoustdar** [GeniusesOfSymfony/WebSocketBundle#36]
Currently, I can't share event handlers between my Symfony application and the server I launch using `gos:websocket`. I'm guessing something needs to sit between the two apps, probably something like ZMQ (look at the approach given in [this tutorial](http://socketo.me/docs/push)).

However, as you are instantiating the server, I can't put in the React ZMQ bindings.

Is there a way to use ZMQ or something similar with your bundle?

**Comment by ProPheT777** [comment]
Currently this feature is missing, i will look to implement this ! :)

**Comment by parhamdoustdar** [comment]
I can try and implement it and send you a pull request if you'd like. I would need more details on how it's going to work, though.

Possibilities could be a configuration value called `zmq_host` and `zmq_port`, and when these are required, the command creates a `React\ZMQ` instance and passes that to the server. On the other end, you'd need to have `TopicWithMessageInterface` that also has an `onMessage()` function added to those defined by `TopicInterface`.

There could then be a `zmq_client` service defined in the dependency injection container that is the result of calling `getSocket()` with `ZMQ::SOCKET_PUSH` which users can then use to push messages onto the queue.

All of this will make your library dependent on `ext_zmq`, though.

**Comment by ProPheT777** [comment]
I appreciate thank you ;)

Keep in your head that feature must be togglable in order to run this bundle when ZMQ  is not installed and not needed. Like ratchet approach no composer require just a good docs about to explain how implements push integration

**Comment by parhamdoustdar** [comment]
Hi,

Here is what I and my colleague have come up with. I'm double-checking with you to make sure it's what you want:

1. We will add a `zmq_server` key to the configuration. It will have `host` and `port` options only, and the values can also be overridden through parameters, just like `host` and `port` for the `server` key.
2. We will add a second server called `ZMQServer` which implements the `Gos\Bundle\WebSocketBundle\Server\Type\ServerInterface`. Since we are not going to have origin checking, this service would accept `LoopInterface`, `EventDispatcherInterface`, `WampApplicationInterface`, and `LoggerInterface`.
3. In the `launch` function, we build the stack, adding the ZMQ server to it, without periodic and origin checking.
4. We add a new command, `gos:zmq:server`, which gets this new server as its `entryPoint` and calls `launch()` on it.

Is this okay?

**Comment by ProPheT777** [comment]
Globally, yes.

Forget ZMQ when you code, use PUSH because ZMQ is only ONE technology to transport like AMQP/STOMP, websocket client, redis PUB/SUB for example.

* `zmq_server` become `push_server`
* `ZMQServer` become `PushServer`
* `gos:zmq:server` become `gos:push:server`

## 1
> We will add a zmq_server key to the configuration. It will have host and port options only, and the values can also be overridden through parameters, just like host and port for the server key.

Add also a type to have :

```yml
push_server:
    host: 12.0.0.1
    port: 3349
    type: zero_mq
```

## 2 

Like I said before,

ZMQServer -> PushServer 
ZMQ implementation -> ZmqTransport with common interface to have something like :

```php
class PushServer
{
    public function __construct(TransportInterface $transport)
    {
          //transport (zmq, websocket client etc we dont care of what is behind, that transport
transport)
    }
}
```

## 4

> We add a new command, gos:zmq:server, which gets this new server as its entryPoint and calls launch() on it.

Don't forget to allow to run command process with optional ip / port in order to load balance ;) (like websocket do today) and your static ip / port in config file point on load balancer.

What do you think about that ?

**Comment by parhamdoustdar** [comment]
I think I get most of what you mean. However, is there somewhere we can chat about this? I'd like to iron out some details?

**Comment by ProPheT777** [comment]
yes here : https://gitter.im/GeniusesOfSymfony/WebSocketBundle

**Comment by parhamdoustdar** [comment]
All right, I've joined.

**Comment by ProPheT777** [comment]
ref #39

**Comment by ProPheT777** [comment]
:tada:
