### ISSUE TITLE
Composer installs error in symfony 4.2+

### ISSUE THREAD

**Issue by xavierkaitha94** [GeniusesOfSymfony/WebSocketBundle#365]
While installing composer it returns error in symfony 4.2 +,
Following is error, please have a look,

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In GosWebSocketExtension.php line 210:
!!                                     
!!    Notice: Undefined index: server  
!!

**Comment by mbabker** [comment]
Duplicate of #358
