### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by xavierkaitha94** [GeniusesOfSymfony/WebSocketBundle#366]
The file "aliases.yml" does not exist (in: /var/www/html/TravelAgency/vendor/gos/web-socket-bundle/DependencyInjection/../Resources/config/services).

**Comment by mbabker** [comment]
Can't reproduce.  The [demo app](https://github.com/GeniusesOfSymfony/WebsocketAppDemo) is updated to the latest commits for both "main" branches on the repo and doesn't have this issue when compiling the container.
