### ISSUE TITLE
clearPeriodicTimer called before removing subscribers

### ISSUE THREAD

**Issue by JJCella** [GeniusesOfSymfony/WebSocketBundle#369]
Hello everyone,

I am using PeriodicTimer in my Topic and I noticed that they are still active even if there is no more subscribers.

I found that clearPeriodicTimer() is called before the cleanTopic() function. As we check if there is no more subscribers before removing the last one, clearPeriodicTimer() is never called.

We must also replace clearPeriodicTimer() with cancelPeriodicTimer()

https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/e2f61a50aa59733eedcfa7dbda87295c616f673d/Server/App/Dispatcher/TopicDispatcher.php#L199-L202

`  0 === count($topic)`  => **count($topic) cannot be 0 here**

https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/ffcb476aaff2290fbafa878215717ccf438ef650/Topic/TopicManager.php#L135-L146

I did not read the full bundle so maybe I am wrong.

Thank you in advance for your help :)

(Tested on 1.8.13)

**Comment by mbabker** [comment]
Fixed in 1.10.3 for 1.x and released, will be fixed in 2.5.0 when next 2.x tag comes around.
