### ISSUE TITLE
AMQP-RabbitMQ integration

### ISSUE THREAD

**Issue by cristhianfernandez01** [GeniusesOfSymfony/WebSocketBundle#37]
Hello again !! Currently I'm trying also to implement functionality PeriodicTopic (which I find very interesting) I'm trying to integrate the functionality of this bundle with a consumer process using amqp-lib and RabbitMQ. This is to receive information from an AMQP queue and then send this information to a particular client using a TopicPeriodic (new functionality) so that client can see the queue information in real time. Is this possible ?. I would like to contribute to this effort. Thank you very much and greetings.

**Comment by ProPheT777** [comment]
Is it something like that : http://www.rabbitmq.com/web-stomp.html that you want ?

**Comment by cristhianfernandez01** [comment]
My idea is similar to using STOMP (but with AMQP), although to be honest I'm using RabbitMQBundle. Technically, there is no support for plugins Websockets and AMQP, so I doubt that even the best implementation for my case. :(

**Comment by ProPheT777** [comment]
Can you describe with a flow chart what do you attempt because it's a bit confused to me in wich direction you want do this. 

Thank you

**Comment by ProPheT777** [comment]
What is the special need that amqp give you and stomp not provide you ? 

Le 7 juil. 2015 03:06, Cristhian Fernandez <notifications@github.com> a écrit :My idea is similar to using STOMP (but with AMQP), although to be honest I'm using RabbitMQBundle. Technically, there is no support for plugins Websockets and AMQP, so I doubt that even the best implementation for my case. :(

**Comment by cristhianfernandez01** [comment]
Hello !!! This would be the flowchart of my application. Amqp have preference because implementing RabbitMQBundle consumers are in my opinion more understandable and more manageable (to receive messages) that STOMP implementations for PHP that I could see so far. Give me your opinion because it might be better used directly regardless of RabbitMQBundle STOMP. Greetings and thanks for your help.

![myapp](https://cloud.githubusercontent.com/assets/8696742/8550705/950859dc-24a8-11e5-871c-d676d4820922.png)

**Comment by ProPheT777** [comment]
STOMP is more lightweight and faster than AMQP and support all feature that websocket give you (publish / subscribe)

Currently you can do that with https://github.com/GeniusesOfSymfony/WebSocketPhpClient 

You can create a worker for your rabbitmq wich save in database and push on websocket  via the websocket client.

here a concrete usage : https://github.com/GeniusesOfSymfony/NotificationBundle/blob/master/Pusher/WebsocketPusher.php#L90

**Comment by cristhianfernandez01** [comment]
Thank you very much for the solution you propose. I find it very useful to use the **WebSocketPhpClient** to interact with the WebSocket server from consumer of *RabbitMQBundle*. I will implement it and I will comment on how to solve achievement. :+1:

**Comment by ProPheT777** [comment]
Just take care to have a persistent connection instead of connect and disconnect 
each time you publishing because the connection have a cost. 
You can look at gos yolo library to implement a retry with ping until the service is available.

**Comment by cristhianfernandez01** [comment]
Okay, thank you. My idea would be to use a persistent connection to send messages from the consumer (within the would have an instance of WebsocketPhpClient) to the WebSocket server. The problem would arise only when the consumer process RabbitMQ fall for some reason. I will use the Yolo library, but I have a question: for example, my client websocket would use a call like this using Yolo?
`````````````````````````````````php
use Gos\Component\WebSocketClient\Wamp\Client;
use Gos\Component\Yolo\Yolo;

$client = new Client('http://localhost:8080');
$yoloConnect = new Yolo(array($client, 'connect'));
$yoloConnect->tryUntil($client);
``````````````````````````````````````

Regards.

**Comment by cristhianfernandez01** [comment]
I would like if you could help also in the implementation of RabbitMQ to the idea formulated in [#36](https://github.com/GeniusesOfSymfony/WebSocketBundle/issues/36).

**Comment by ProPheT777** [comment]
you can join the gitter at this address : https://gitter.im/GeniusesOfSymfony/WebSocketBundle 

For yolo you must use PingBack callback https://github.com/GeniusesOfSymfony/Yolo#ping-back

```php
$client = new Client('localhost', 8080);
$yoloConnect = new Yolo(array($client, 'connect'));
$yoloConnect->tryUntil(new PingBack('localhost', 8080);
```

I just have updated the docs about websocket client, the docs was wrong about intanciation of client.

**Comment by cristhianfernandez01** [comment]
Thank you very much. And I was reading some of the conversation on ZMQ in Gitter, but I have to think like that to RabbitMQ adapted.

**Comment by ProPheT777** [comment]
Yep, I think I will create base foundation of transport layer with global architecture and interface then we will start to create implementation (rabbit, zmq, redis)

**Comment by ProPheT777** [comment]
ref #39

**Comment by ProPheT777** [comment]
:tada:
