### ISSUE TITLE
forget a "use" statement for "PhpAmqpLib\Connection\AMQPConnection"? 

### ISSUE THREAD

**Issue by entekhabgroup** [GeniusesOfSymfony/WebSocketBundle#373]
in windows 10, rabbitmq and amqp installed and work successfully. but when run `php bin/console gos:websocket:server` get these error:

```
Attempted to load class "AMQPConnection" from the global namespace.           
Did you forget a "use" statement for "PhpAmqpLib\Connection\AMQPConnection"? 
```

windows 10
symfony 4.2
php 7.3
amqp 1.9.4 (compatible with php 7.3)

whats wrong?

**Comment by mbabker** [comment]
It looks like you might have https://github.com/php-amqplib/php-amqplib installed and the PHP amqp extension might not be enabled.

**Comment by entekhabgroup** [comment]
how can i enable it in windows?

**Comment by mbabker** [comment]
Check your PHP config file and make sure there's something like `extension=amqp.dll` in it (off hand I don't know the exact requirements for Windows PHP builds, but that should be close).  If you run `php -m` or the equivalent to a Linux `php -i | grep amqp` from a terminal window you should see the extension in those lists.

**Comment by entekhabgroup** [comment]
thx mbabker for your response. this line is existet in my php.ini
