### ISSUE TITLE
Publish message to all users except sender

### ISSUE THREAD

**Issue by kirannuclear** [GeniusesOfSymfony/WebSocketBundle#382]
Hi, I'm using GosWebSocketBundle to send notifications/messages. I have referred the documentation and done with broadcasting message to all the subscribers of the common channel. But I don't want the sender to receive it's own message. Please help me.

```php
public function onSubscribe(ConnectionInterface $connection, Topic $topic, WampRequest $request)
    {
        //this will broadcast the message to ALL subscribers of this topic.
        $topic->broadcast(['msg' => $connection->resourceId . " has joined " . $topic->getId()]);
    }

public function onPublish(ConnectionInterface $connection, Topic $topic, WampRequest $request, $event, array $exclude, array $eligible)
    {
          $topic->broadcast(['msg' => $event]);
    }
```

**Comment by mbabker** [comment]
Try this:

```php
public function onSubscribe(ConnectionInterface $connection, Topic $topic, WampRequest $request)
{
        // This will broadcast the message to ALL subscribers of this topic except the person who just subscribed.
        $topic->broadcast(
            ['msg' => $connection->resourceId . " has joined " . $topic->getId()],
            [$connection->WAMP->sessionId]
        );
}
```

The second and third parameters of [`Topic::broadcast()`](https://github.com/ratchetphp/Ratchet/blob/b85c2a1f189e43f7f0861daf7ff81d016c5d6403/src/Ratchet/Wamp/Topic.php#L32-L39) let you specify a list of session IDs to exclude and a list of session IDs to broadcast to.  So if you want to send a message to everyone but the sender, you'd add their session ID to the exclude list and that'll take care of it.

**Comment by kirannuclear** [comment]
@mbabker Is there anyway I can send this to specific users in my database who are connected to the channel.. Can I somehow link users in my database to the session IDs and send only to session IDs of specific users?

**Comment by murtho** [comment]
https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/SessionSetup.md#send-a-message-to-a-specific-user

**Comment by kirannuclear** [comment]
@murtho yeah, but I want to send to specific user_ids'(that are stored in my database) sessionIDs. I dont know how to find the sessionID of a specific user_id

**Comment by kirannuclear** [comment]
@mbabker  @murtho  please tell me if it is possible to do it
