### ISSUE TITLE
not work in server anyway but ok in localhost

### ISSUE THREAD

**Issue by thehatami** [GeniusesOfSymfony/WebSocketBundle#387]
i implement the gos websocket in my localhost by symfony 4 and everything is ok. but when ship in product connection not stablished.
i check many answer and suggestion but nothing work. like this. [[1](https://github.com/GeniusesOfSymfony/WebSocketBundle/issues/251)] or [[2](https://stackoverflow.com/questions/54566493/gos-web-socket-bundle-is-not-working-with-symfony-4-2)] or [[3]](https://stackoverflow.com/questions/45474041/websocket-doesnt-work-in-server-127-0-0-18000).

i run my server with
```
php bin/console gos:websocket:server --profile --env=prod
```
with no error.

but in both http and https connection not established. i also try stunnel and nginx in https configuration. [as [here](https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/Ssl.md)]

here is my configuration:
```
gos_web_socket:
  server:
    host: 127.0.0.1   #test with 0.0.0.0 | [local-ip] [valid-ip]
    port: 8080        #opened in firewall
    router:
      resources:
        - '../src/rimo/routing.yaml'
  client:
    session_handler:        '@session.handler.pdo'
    firewall:               main
    storage:
      driver:               '@gos_web_socket.client_storage.driver.redis'
      ttl:                  28800
      prefix:               'client'
      decorator:            '@gos_web_socket.client_storage.doctrine.decorator'
  shared_config: true
  pushers:
    amqp:
      default:              true
      host:                 127.0.0.1
      port:                 5672
      login:                "%env(AMQP_USR)%"
      password:             "%env(AMQP_PWD)%"
      vhost:                "%env(AMQP_VHOST)%"
      queue_name:           gos_websocket
      exchange_name:        gos_websocket_exchange
    wamp:
      host:                 127.0.0.1
      port:                 8080
      ssl:                  false
      origin:               null
```
and my script

```
var _WS_URI = "ws://{{ gos_web_socket_server_host }}:{{ gos_web_socket_server_port }}"; #try wss
        var webSocket = WS.connect(_WS_URI);
```

whats my wrong?

**Comment by CoalaJoe** [comment]
Use HTTPS and prefix the _WSI_URI with `wss://` and not `ws://`
