### ISSUE TITLE
WebSocket connection to 'wss://mydomain:8443/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by ankit-iod** [GeniusesOfSymfony/WebSocketBundle#396]
Getting error :
WebSocket connection to 'wss://mydomain:8443/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

configure letsenctypt ssl :
Open port : 8888 , 8443 

I'm using apache2 and i get configuration for ngix not for apache2 if any have this answer please provide.

**Comment by mbabker** [comment]
Make sure you've got something dealing with proxying set up.  [The wiki](https://github.com/GeniusesOfSymfony/WebSocketBundle/wiki) here has a couple of examples of ways to set up for secure connections.

**Comment by ankit-iod** [comment]
Really helpful buddy ...
i was using stunnel but when you have apache2 there is no need of use stunnel and using proxy i can achieve that one.
https://github.com/GeniusesOfSymfony/WebSocketBundle/wiki/Ssl-proxy-on-apache-2.4-to-ratchet-symfony-2.8-on-Ubuntu-16.4
Thanks @mbabker
