### ISSUE TITLE
Symfony 5 compatibility

### ISSUE THREAD

**Issue by iaejean** [GeniusesOfSymfony/WebSocketBundle#402]
Why the event-dispatcher dons't allow Symfony version 5?

```json
"require": {
        "php": "^7.2",
        "cboden/ratchet": "^0.4.1",
        "gos/pubsub-router-bundle": "^1.0 || ^2.0",
        "gos/websocket-client": "^0.3",
        "ocramius/proxy-manager": "~0.4 || ^1.0 || ^2.0",
        "psr/log": "^1.1",
        "react/event-loop": "^1.0",
        "symfony/config": "^3.4 || ^4.4 || ^5.0",
        "symfony/console": "^3.4 || ^4.4 || ^5.0",
        "symfony/dependency-injection": "^3.4 || ^4.4 || ^5.0",
        "symfony/event-dispatcher": "^3.4 || ^4.4",
        "symfony/http-foundation": "^3.4 || ^4.4 || ^5.0",
        "symfony/http-kernel": "^3.4 || ^4.4 || ^5.0",
        "symfony/security-core": "^3.4 || ^4.4 || ^5.0",
        "symfony/serializer": "^3.4 || ^4.4 || ^5.0"
 },
```

**Comment by mbabker** [comment]
See https://github.com/GeniusesOfSymfony/WebSocketBundle/pull/398, basically I tried doing a compatibility layer so that 3.4, 4.4, and 5.0 would be fully supported but it wasn't working right and I haven't found time to come back around to it and see if there's a way to pull it off.

FWIW with Ratchet not yet updated to support Symfony 5 the HttpFoundation component is also blocked from actually being installed at 5.0 right now.

**Comment by mbabker** [comment]
What I'm probably going to do here is tag a 3.0 beta in the next couple of weeks that drops Symfony 3.4 support (and has some other bundle adjustments, see https://github.com/GeniusesOfSymfony/WebSocketBundle/compare/master for the full diff which is mostly dropping compatibility code and using PHP 7.4 features), that'll be the version to use for Symfony Flex based applications on Symfony 5.  I just don't think I can come up with a sane compatibility layer for the event dispatcher changes, so this is going to be the easiest thing I can come up with.  It'll then basically be use the 2.x branch with Symfony 3.4 and 4.4 (and if you're not using Flex to lock versions down then most components will work with Symfony 5), and use the 3.x branch with Symfony 4.4 and 5.

**Comment by mbabker** [comment]
Release candidate for 3.0 [is tagged](https://github.com/GeniusesOfSymfony/WebSocketBundle/releases/tag/v3.0.0-rc).  Stable will follow in the next couple of weeks.  Closing this out.

(For the record, I mainly run the master branch of this repo on one of my client sites as a basis for validating changes when deployed at scale, so the RC should be safe to use now but I'd rather also give an opportunity for extra testing from anyone who might upgrade onto beta or RC releases)
