### ISSUE TITLE
Twig global gos_web_socket_server_port not added because twig is not registered yet

### ISSUE THREAD

**Issue by StephenBeirlaen** [GeniusesOfSymfony/WebSocketBundle#407]
Hi all, I am upgrading from version v1.9.0-rc2 to v2.3.0.

In the past I have been using the Twig global `{{ gos_web_socket_server_port }}` in my templates to connect to the websocket server. This global is not available right now, throwing me an exception `Variable "gos_web_socket_server_port" does not exist.`

I have traced the issue down to [DependencyInjection/GosWebSocketExtension.php:171](https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/2.x/DependencyInjection/GosWebSocketExtension.php#L171). It appears that Twig is not registered here yet (on my system), so the condition does not fulfill to add these globals. When I view the contents of the container at this point, only GOS websocket definitions are registered, nothing else:
```
^ "service_container"
^ "gos_web_socket.client.authentication.websocket_provider"
^ "gos_web_socket.client.driver.doctrine_cache"
^ "gos_web_socket.client.driver.symfony_cache"
^ "gos_web_socket.client.driver.in_memory"
^ "gos_web_socket.client.manipulator"
^ "gos_web_socket.client.storage"
^ "gos_web_socket.command.websocket_server"
^ "gos_web_socket.data_collector.websocket"
^ "gos_web_socket.dispatcher.rpc"
^ "gos_web_socket.dispatcher.topic"
^ "gos_web_socket.event_listener.client"
^ "gos_web_socket.event_listener.kernel_terminate"
^ "gos_web_socket.event_listener.register_periodic_memory_timer"
^ "gos_web_socket.event_listener.register_periodic_timers"
^ "gos_web_socket.event_listener.register_push_handlers"
^ "gos_web_socket.event_listener.start_server"
^ "gos_web_socket.periodic_ping.doctrine"
^ "gos_web_socket.periodic_ping.pdo"
^ "gos_web_socket.periodic_ping.memory_usage"
^ "gos_web_socket.pusher.amqp"
^ "gos_web_socket.pusher.amqp.push_handler"
^ "gos_web_socket.pusher.wamp"
^ "gos_web_socket.registry.periodic"
^ "gos_web_socket.registry.origins"
^ "gos_web_socket.registry.pusher"
^ "gos_web_socket.registry.rpc"
^ "gos_web_socket.registry.server"
^ "gos_web_socket.registry.server_push_handler"
^ "gos_web_socket.registry.topic"
^ "gos_web_socket.router.wamp"
^ "gos_web_socket.server.application.wamp"
^ "gos_web_socket.server.builder"
^ "gos_web_socket.server.entry_point"
^ "gos_web_socket.server.event_loop"
^ "gos_web_socket.server.websocket"
^ "gos_web_socket.topic.periodic_timer"
^ "gos_web_socket.wamp.topic_manager"
```

Twig is installed successfully and working.

I suspect this is because of the PrependExtensionInterface, that the bundle gets loaded before all others?

**Comment by mbabker** [comment]
> I suspect this is because of the PrependExtensionInterface, that the bundle gets loaded before all others?

Not exactly.  Extensions that implement the PrependExtensionInterface have their `prepend()` methods called in a build step before the normal `load()` method, generally so they can do something with another extension's configuration (and in this case that is setting some extra configuration to other bundles).

What order are your bundles being loaded in?  If you're using Flex, please paste the contents of your `config/bundles.php` file in.  If you're using the older Symfony Standard, please paste the contents of the `registerBundles()` method from your kernel.  What I suspect is happening is this bundle is being loaded before the TwigBundle and that's causing your issue.

**Comment by StephenBeirlaen** [comment]
I am indeed using Symfony Flex. These are the contents of my `config/bundles.php` file:
```
<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Sonata\CoreBundle\SonataCoreBundle::class => ['all' => true],
    Sonata\BlockBundle\SonataBlockBundle::class => ['all' => true],
    Knp\Bundle\MenuBundle\KnpMenuBundle::class => ['all' => true],
    Sonata\AdminBundle\SonataAdminBundle::class => ['all' => true],
    Sonata\DoctrineORMAdminBundle\SonataDoctrineORMAdminBundle::class => ['all' => true],
    Sonata\TranslationBundle\SonataTranslationBundle::class => ['all' => true],
    Sonata\Exporter\Bridge\Symfony\Bundle\SonataExporterBundle::class => ['all' => true],
    Sonata\EasyExtendsBundle\SonataEasyExtendsBundle::class => ['all' => true],
    FOS\UserBundle\FOSUserBundle::class => ['all' => true],
    Sonata\UserBundle\SonataUserBundle::class => ['all' => true],
    Sonata\DatagridBundle\SonataDatagridBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    A2lix\AutoFormBundle\A2lixAutoFormBundle::class => ['all' => true],
    A2lix\TranslationFormBundle\A2lixTranslationFormBundle::class => ['all' => true],
    JMS\TranslationBundle\JMSTranslationBundle::class => ['all' => true],
    Lexik\Bundle\TranslationBundle\LexikTranslationBundle::class => ['all' => true],
    Bugsnag\BugsnagBundle\BugsnagBundle::class => ['all' => true],
    FOS\CKEditorBundle\FOSCKEditorBundle::class => ['all' => true],
    FOS\JsRoutingBundle\FOSJsRoutingBundle::class => ['all' => true],
    Knp\DoctrineBehaviors\Bundle\DoctrineBehaviorsBundle::class => ['all' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
    Gos\Bundle\PubSubRouterBundle\GosPubSubRouterBundle::class => ['all' => true],
    Gos\Bundle\WebSocketBundle\GosWebSocketBundle::class => ['all' => true],
    League\Tactician\Bundle\TacticianBundle::class => ['all' => true],
    OldSound\RabbitMqBundle\OldSoundRabbitMqBundle::class => ['all' => true],
    JMS\SerializerBundle\JMSSerializerBundle::class => ['all' => true],
    Bazinga\Bundle\JsTranslationBundle\BazingaJsTranslationBundle::class => ['all' => true],
    Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class => ['all' => true],
];
```

GosWebSocketBundle is being loaded almost at the end.

**Comment by mbabker** [comment]
Huh, I'm seeing it in the demo app too.  Guess it's time to dig in and see what's going wrong here...

![Screen Shot 2020-03-16 at 10 47 34 AM](https://user-images.githubusercontent.com/368545/76775638-a4159800-6773-11ea-90ea-e48270a83294.png)

**Comment by StephenBeirlaen** [comment]
I have done some digging in the history, I saw that the if condition was changed in this commit:
https://github.com/GeniusesOfSymfony/WebSocketBundle/commit/bbabaed868d9eee572b0db815432e47e24735dfe
The old way `isset($bundles['TwigBundle'])` would behave as desired, but I am not sure what the reasoning behind this change was :)

**Comment by mbabker** [comment]
I purposefully moved the extra configuration out of the prepend step and into the load step.  You shouldn't need to directly mess with the TwigBundle configuration to add global values, you should be able to do it by adding a method call in the service definition.  So while reverting that might work, I don't think it's necessarily the right approach.

(Note with the other two bundles, it's more optimal to prepend extra data to the configuration than it is to try and repeat the things those extension classes would be doing)

**Comment by mbabker** [comment]
`*sigh*` The compiler pass loading extensions pushes in a temp container that basically only has that extension's resources available to it.  So, I guess that is the right way.

**Comment by mbabker** [comment]
Fixed in [2.3.2](https://github.com/GeniusesOfSymfony/WebSocketBundle/releases/tag/v2.3.2)

**Comment by mbabker** [comment]
(I also changed the demo to [use the Twig globals](https://github.com/GeniusesOfSymfony/WebsocketAppDemo/commit/9b9d9cc08ac05d3aa4d6e61b95289310a4c91970) so it should be a little easier to track this working right in the future)

**Comment by StephenBeirlaen** [comment]
Fantastic, thanks a lot for helping out! :racehorse:
