### ISSUE TITLE
Deployment requirements

### ISSUE THREAD

**Issue by tejadong** [GeniusesOfSymfony/WebSocketBundle#409]
Hello, can someone give me a manual on how to deploy on normal hosting with apache2? Is this possible or do I need AWS compulsorily? I have been seeing the issue #7  but it is not very clear to me if I need console access to the hosting or not ... can someone help me?

**Comment by mbabker** [comment]
Define "normal hosting" please?

I've run an application with this bundle on WHM/cPanel based hosting and in environments where I have tools like supervisord available to me.  The key thing is you need something that can keep the websocket server command running in the background so it properly handles requests, that's not as easy to do in a WHM/cPanel environment but there are tricks to do it (I used the `screen` command to essentially make a background shell, which works, but doesn't support automatically restarting the process if it fails like supervisord would, it also made our deployments a little more tricky).

No matter how you host, you will need some form of CLI access to be able to run the socket server command (and in general use Symfony's console).

**Comment by tejadong** [comment]
When I say normal hosting I mean a shared hosting php / mysql ...

So, using some of the packages from problem #7 and having access to cli, what will be enough to be able to run the project and be able to manage the failures and auto-starts of the command that starts the websocket server? Do you recommend some personally?

**Comment by mbabker** [comment]
It all depends what's available to you and what you're comfortable with.  The info posted in that old issue is still just as relevant today as it was when originally posted, so you can use that as a guideline.

I don't know what kind of shared hosting you're using, but usually the end user accounts in those environments don't have access to supervisord.  So just keep that in mind.
