### ISSUE TITLE
How to disconnect an existing connection in the client

### ISSUE THREAD

**Issue by klodoma** [GeniusesOfSymfony/WebSocketBundle#416]
I have a  hybrid app and I need to close the websocket connection from the frontend (javascripts) side. 

This is how I connect:
```
let websocket = WS.connect(me.getUrl());
```

I couldn't find any "disconnect" or "close" method in GosSocket or it's autobahn reference. 

Please advise.

**Comment by mbabker** [comment]
```javascript
websocket.session.close();
```

The only publicly accessible close/disconnect method is part of the `ab.Session` object, which is available through the `GosSocket` object's `session` getter.
