### ISSUE TITLE
WampPusher deprecation

### ISSUE THREAD

**Issue by klodoma** [GeniusesOfSymfony/WebSocketBundle#417]
```
trigger_deprecation('gos/web-socket-bundle', '3.1', 'The "%s" class is deprecated and will be removed in 4.0, use the symfony/messenger component instead.', WampPusher::class);
```

Hi, 

I understand this will be deprecated. I couldn't find any example or reference on how to use `symfony/messenger` instead. 
I use wamp to push messages to the clients from the backend. 

Can you provide an example? 

Thank you

**Comment by mbabker** [comment]
You'd basically need to copy the internals of `Gos\Bundle\WebSocketBundle\Pusher\Wamp\WampPusher::doPush()` into where you need it in your application.  Where you handle that is up to you (in one application I have this logic as an event listener for a couple of actions in the app and a couple of places where the WAMP publish is inside of a messenger handler).
