### ISSUE TITLE
Server doesn't start

### ISSUE THREAD

**Issue by LacErnest** [GeniusesOfSymfony/WebSocketBundle#419]
Hello,

im following the steps to run this websocket server.

on php bin/console gos:websocket:server nothing happens no error...nothing

here's my config/packages/gos_web_socket.yaml:
gos_web_socket:
    server:
        port: 1337        # The port the socket server will listen on
        host: 127.0.0.1   # The host ip to bind to

I'm currently on symfony 4.4 and using php 7.3
How can i resolve this issue ?

**Comment by mbabker** [comment]
Run the command with extra verbosity so it will show all messages:

```sh
php bin/console gos:websocket:server -vvv
```

Check your Symfony app logs for any relevant messages

Check to ensure the port is open and able to accept connections

**Comment by ma-gu-16** [comment]
same for me. no response. i have still an symfony 2.2 project and the command /start server works well. 

but with symfony 4.4. and php 7.4 no output from server. 

cant find any logs. 

`INFO      [websocket] Starting web socket
INFO      [websocket] Launching Ratchet on 127.0.0.1:8080 PID: 12345`

never shows up. i tried to debug. 

php .7.2 andy symfony 3.4  works well. 

seems like this bundle is not working anmore. the documentation is not up2date :(

**Comment by mbabker** [comment]
> seems like this bundle is not working anmore. the documentation is not up2date :(

It's working fine, I'm running it in production daily.

I can't explain why you are having issues with getting the server to run.  Generally though, there should be some form of error message and the Symfony Console app would exit if there were an error causing the server to not be launchable.

Once you're run the command, you're stepping through these classes until you reach the upstream code this bundle builds on:

- https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/3.x/src/Command/WebsocketServerCommand.php - The actual console command being triggered
- https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/3.x/src/Server/EntryPoint.php - The class that resolves the options from the command and gets the server instance to be executed
- https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/3.x/src/Server/Type/WebSocketServer.php - Unless you've really gone crazy with customizations, this is the server class that is in charge of booting up the server; once you get to `$app->run();` in this file then it's all upstream code from here

If you aren't reaching `$app->run()`, then generally there's an error in front of it and there should be something pretty clearly noted either in the console output or the Symfony logs.  There isn't anything that is silently absorbing errors in the bundle code, and there isn't anything that I'm aware of in the bundle code that would create some kind of loop where it would get stuck in the bootup sequence (those three files).  Even the "Launching Ratchet on..." message should get logged before getting into the "real" server code.  So I'm inclined to think there is some kind of local environment issue that is keeping you from being able to launch the server, but I don't have the details to work that out.

**Comment by ma-gu-16** [comment]
> > seems like this bundle is not working anmore. the documentation is not up2date :(
> 
> It's working fine, I'm running it in production daily.
> 
> I can't explain why you are having issues with getting the server to run. Generally though, there should be some form of error message and the Symfony Console app would exit if there were an error causing the server to not be launchable.
> 
> Once you're run the command, you're stepping through these classes until you reach the upstream code this bundle builds on:
> 
> * https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/3.x/src/Command/WebsocketServerCommand.php - The actual console command being triggered
> * https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/3.x/src/Server/EntryPoint.php - The class that resolves the options from the command and gets the server instance to be executed
> * https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/3.x/src/Server/Type/WebSocketServer.php - Unless you've really gone crazy with customizations, this is the server class that is in charge of booting up the server; once you get to `$app->run();` in this file then it's all upstream code from here
> 
> If you aren't reaching `$app->run()`, then generally there's an error in front of it and there should be something pretty clearly noted either in the console output or the Symfony logs. There isn't anything that is silently absorbing errors in the bundle code, and there isn't anything that I'm aware of in the bundle code that would create some kind of loop where it would get stuck in the bootup sequence (those three files). Even the "Launching Ratchet on..." message should get logged before getting into the "real" server code. So I'm inclined to think there is some kind of local environment issue that is keeping you from being able to launch the server, but I don't have the details to work that out.

Hi thanks for helping. 

i try to provide some more information. 

Local Windows 10 enviroment with Apache
PHP 7.4.5
Symfony 4.4 
GosBundle 3.4

as is said the same bundle just lower version works well with symfony 2.3 

so there shouldnt any restrictions with port or ip. 

i can dump something at  line 63 in src\Server\Type\WebSocketServer.php
as you said. eveything before just works fine. no errors, no log.

its just       $app->run();    after that i have no output in console, the cursor is just blinking. 
usually i saw somethign like this: 
15:42:29 INFO      [websocket] Starting web socket
15:42:29 INFO      [websocket] Launching Ratchet on 127.0.0.1:1337 PID: 3748

if i debug the logger: Its this correct nullhandler? 
`
Symfony\Bridge\Monolog\Logger {#200
  #name: "websocket"
  #handlers: array:1 [
    0 => Monolog\Handler\NullHandler {#201
      #level: 100
      #bubble: false

#formatter: null
      #processors: []
    }
  ]
  #processors: []
  #microsecondTimestamps: true
  #exceptionHandler: null
}


`



further more is there any example of send push. i used before 

`
        /** @var PusherInterface $pusher */
        $pusher = $this->get('gos_web_socket.pusher.wamp');`

but looks like this is deprecated and no longer supported, ca you provide an functional example how to push ? 

thank you

**Comment by mbabker** [comment]
#405 has an example of how I replaced the pusher.

Do you have MonologBundle installed?  A configured logger should definitely be injected in, I can't think of a reason off hand why a NullLogger instance would be injected though.  If you debug your container, is it only the websocket logger that's a NullLogger or are other loggers nulled as well?  That would explain the lack of output though.

I haven't done any PHP dev on Windows in 6 or 7 years, so I don't have any good feedback here on debugging if the server actually isn't running.  For now though I'd say find whatever is messing with the logging configuration and fix that as it's going to help in the long run.  Then, if things really aren't running still, check the Ratchet and ReactPHP docs for any pointers they may have (for ReactPHP especially their Socket package as that's ultimately where the server class that actually opens the socket connection for PHP to listen on is coming from).

**Comment by ma-gu-16** [comment]
Ok seems like it worked all the time. just no output atleast not on INFO LVL.  i receive INFO log in other bundles. 

after starting the server i receive error messages: 
13:37:33 ERROR     [websocket] Unable to find route for myapp/user/1


routing.yaml

```
myapp_topic:
  channel: myapp/user/{user_id}
  handler: 'myapp.topic'
  requirements:
    user_id: '\d+'
```

gos_websocket.yaml

```
gos_web_socket:
  client:
    firewall: main
    session_handler: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
  server:
    port: '%env(int:GOS_WEB_SOCKET_SERVER_PORT)%' # The port the socket server will listen on
    host: '%env(GOS_WEB_SOCKET_SERVER_IP)%'       # The host ip to bind to
    router:
      resources:
        - '%kernel.project_dir%/config/pubsub/routing.yaml'
```



i tried already to create the gos_pubsub conf

```
gos_pubsub_router:
  routers:
    websocket: #available from container through gos_pubsub_router.websocket
      resources:
        - '%kernel.project_dir%/config/pubsub/routing.yaml'
```


what is wrong ? thank you 



router debug
```

C:\>php bin/console gos:prouter:debug -r websocket
+-----------------+--------------------------+----------------------------+
| Name            | Pattern                  | Callback                   |
+-----------------+--------------------------+----------------------------+
| myapp_topic | myapp/user/{user_id} | App\Websocket\TopicHandler |
+-----------------+--------------------------+----------------------------+



```

**Comment by mbabker** [comment]
You shouldn't need to specify anything for the `gos_pubsub_router` config, the `gos_web_socket.server.router` config node automatically merges over to the PubSubRouter config.

Make sure that what you have for a route's `handler` matches up with your class' `getName()` method.  The `myapp_topic` name is similar to a HTTP controller's name.  The `myapp.topic` that you have for the handler right now should be what your `TopicHandler::getName()` method returns, since that's how the dispatcher is going to load your class out of the registry that it uses.

**Comment by ma-gu-16** [comment]
> You shouldn't need to specify anything for the `gos_pubsub_router` config, the `gos_web_socket.server.router` config node automatically merges over to the PubSubRouter config.
> 
> Make sure that what you have for a route's `handler` matches up with your class' `getName()` method. The `myapp_topic` name is similar to a HTTP controller's name. The `myapp.topic` that you have for the handler right now should be what your `TopicHandler::getName()` method returns, since that's how the dispatcher is going to load your class out of the registry that it uses.

yep thats exactly what i have. the app worked very well with symfony 3.4 after upgrade to 4.4.  i have this problems

**Comment by mbabker** [comment]
Can you share the code of your `TopicHandler` class?

Also, try running `bin/console debug:container --tag=gos_web_socket.topic`, this should show all the services that have the right tag, and these all should be injected into the `gos_web_socket.registry.topic` service (if you run `bin/console debug:container gos_web_socket.registry.topic` there should be the same number of `addTopic` calls as there are tagged services).

It may very well be either your topic class is missing the required interface or if you don't have service autowiring enabled then your class' service definition is missing the container tag.

**Comment by ma-gu-16** [comment]
Okay excatly, i ve copied the example of your documentation. i have now 2 topic handlers and two "addTopic" .

looks like it works. since i removed the service conf, because i have autowire and seems its works without any config by myself.

just one bad thing, that i have no response in my console. 
just debug notes in dev.log file. i miss the console output. do you have any ideas ? 

```

    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: '!php'
```

dev/monolog.log
```

monolog:
    handlers:
        console:
            type:   console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!myapp']

```

**Comment by mbabker** [comment]
You might have your Monolog configuration wrong, specifically the `monolog.handlers.main.channels` node; that should be an array instead of a string IIRC (so use `channels: ['!php']`).

**Comment by ma-gu-16** [comment]
> You might have your Monolog configuration wrong, specifically the `monolog.handlers.main.channels` node; that should be an array instead of a string IIRC (so use `channels: ['!php']`).

nope, still same, no output :-(

**Comment by mbabker** [comment]
Not sure where to point you then.  The logger's basically autowired by the MonologBundle, so based on your config it should be printing to console.

The only thing I can think to try is to find the `monolog.logger.websocket` service in your compiled container (`var/cache/dev`) and make sure there's a `pushHandler` call with the `monolog.handler.console` service on the logger.  Otherwise, something's gone awry with the logger setup and that's outside of this bundle's control (older 1.x and 2.x versions did some explicit config on that logger, but the newer versions are all using the MonologBundle's autowiring logic).

**Comment by ma-gu-16** [comment]
> Not sure where to point you then. The logger's basically autowired by the MonologBundle, so based on your config it should be printing to console.
> 
> The only thing I can think to try is to find the `monolog.logger.websocket` service in your compiled container (`var/cache/dev`) and make sure there's a `pushHandler` call with the `monolog.handler.console` service on the logger. Otherwise, something's gone awry with the logger setup and that's outside of this bundle's control (older 1.x and 2.x versions did some explicit config on that logger, but the newer versions are all using the MonologBundle's autowiring logic).
```

    <service id="monolog.logger.websocket" class="Symfony\Bridge\Monolog\Logger">
      <argument>websocket</argument>
      <call method="pushProcessor">
        <argument type="service" id="debug.log_processor"/>
      </call>
      <call method="pushHandler">
        <argument type="service" id="monolog.handler.console"/>
      </call>
      <call method="pushHandler">
        <argument type="service" id="monolog.handler.main"/>
      </call>
      <configurator class="Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\AddDebugLogProcessorPass" method="configureLogger"/>
    </service>
```

should be right ?

**Comment by mbabker** [comment]
Yeah that looks right.  Strange that that logger doesn't print to console though.

**Comment by ma-gu-16** [comment]
> Yeah that looks right. Strange that that logger doesn't print to console though.

yea especially because the console output works with symfyony 2.3 in same enviroment/phpstorm. and its only the gos bundle. console output in general works well. 

dont know. 
but i guess we can close this issue. thank you for your support.
