### ISSUE TITLE
php version requirements

### ISSUE THREAD

**Issue by gaelb80** [GeniusesOfSymfony/WebSocketBundle#423]
Hello,

I tried to install the bundle on a fresh sf5.2 project but it triggers that php requirements is bumped to 7.4.

Is there a reason for it ?

Symfony having 7.3 requirements it will be great to keep it in the projet too !

Thanks for your reply

**Comment by mbabker** [comment]
There wasn't any real need for 7.4, but at the time I decided to go with the newest PHP version only just to clean things up a bit.  I generally don't raise PHP minimums during a major version series of my OSS packages, so 3.x will always be compatible with PHP 7.4.

At this point, to me, it isn't worth the effort to downgrade the code to support PHP 7.3 as it has already entered its security-only support phase.

**Comment by gaelb80** [comment]
Thanks for your reply !
It seems to be the property typing in class that make it incompatible with php 7.3.
I decided to upgrade my php version so fill free to close this issue !
