### ISSUE TITLE
Suggestion: Native TLS support

### ISSUE THREAD

**Issue by AndreRudolph** [GeniusesOfSymfony/WebSocketBundle#453]
I am wondering why there is no native TLS support integrated in this bundle. Wouldn't it be better than using stunnel? The class React\Socket\SecureServer actually provides a php based implementation to support a WSS connection.

I just cloned the class Gos\Bundle\WebSocketBundle\Server\Type\WebSocketServer and decorated the SecureServer object by the IoSever object like this and it works fine to establish a WSS connection:

  ```
          $tlsOptions = []; // see https://www.php.net/manual/en/context.ssl.php for available options
          $socketServer = new SocketServer("$host:$port", [], $this->loop);
          $server = new SecureServer($socketServer, $this->loop, $tlsOptions);

        $app = new IoServer(
            $this->serverBuilder->buildMessageStack(),
            $server,
            $this->loop
        );
```

Or maybe you could at least remove the final keyword and move the creation of the SocketServer to a protected method so that it can be replaced by inheritance logic?

**Comment by mbabker** [comment]
> I am wondering why there is no native TLS support integrated in this bundle. Wouldn't it be better than using stunnel? The class React\Socket\SecureServer actually provides a php based implementation to support a WSS connection.

Honestly?  I never realized it was there.  Pull requests supporting it would definitely be welcome.

> Or maybe you could at least remove the final keyword and move the creation of the SocketServer to a protected method so that it can be replaced by inheritance logic?

There's no need for this.  You can make your own class implementing `Gos\Bundle\WebSocketBundle\Server\Type\ServerInterface`, which automatically will be added to the server registry thanks to autowiring (but if it isn't for some reason, the class needs the `gos_web_socket.server` container tag), then you pass whatever name you use in that class' `getName()` method through as an argument to the server command and it'll use your custom class (i.e. `bin/console gos:websocket:server custom-server`).  The default `Gos\Bundle\WebSocketBundle\Server\Type\WebSocketServer` is lightweight enough that I don't think it needs to be open for extension as you'd essentially be re-implementing the interface in any subclass.

**Comment by AndreRudolph** [comment]
Thanks for your explanation. Well, I just created my own class implementing that interface but I needed to copy all of the code of the Gos\Bundle\WebSocketBundle\Server\Type\WebSocketServer class in order to have the state as it is plus the secured socket connection. That's why I was thinking about to extend that class to not copy all of its code.

However, I can create a Pull request in near future. I would suggest to also introduce a new bundle config parameter TLS options so that all context options of https://www.php.net/manual/en/context.ssl.php can be applied and passed automatically to that constructor.

**Comment by AndreRudolph** [comment]
From which branch I should branch off?

**Comment by AndreRudolph** [comment]
I think I have finished the code changes in my fork. How can I test it apart from just unit tests? Is there any process how I can replace your bundle inside my application with my forked bundle?

**Comment by mbabker** [comment]
3.x branch

You can use Composer’s repositories config to point to your fork in place of the main repo.  https://matthewsetter.com/series/tooling/composer/forked-repositories/ covers that well.

**Comment by AndreRudolph** [comment]
Thanks, I already did that and it works fine. I will create a pull request then.
