### ISSUE TITLE
ClientManipulatorInterface

### ISSUE THREAD

**Issue by rtoledof** [GeniusesOfSymfony/WebSocketBundle#46]
Hello I'm trying to integrate the bundle in my project to use the real time notification. I need to get logged user to get information related to this user. I followed step by step the all configuration in the bundle but when I try to  get the user using $user = $this->clientManipulator->getClient($connection) every time the function get me the anonymous user. 

Here is my configuration.

GOS Configuration:
gos_web_socket:
    server:
        port: "%clank_port%"   #The port the socket server will listen on
        host: "%clank_host%"   #The host ip to bind to
        router:
          resources:
            - @SomeBundle/Resources/config/pubsub/routing.yml

    shared_config: false

    topics:
      - @some.topic_test_service

    client:
      firewall: backend_secure_area
      session_handler: @session.handler.pdo
      storage:
        driver: @gos_web_socket.client_storage.driver.redis
        decorator: @gos_web_socket.client_storage.doctrine.decorator

SNC Redis configuration

snc_redis:
  clients:
    ws_client:
      type: predis
      alias: client_storage.driver #snc_redis.client_storage.driver
      dsn: redis://127.0.0.1/2
      logging: %kernel.debug%
   options:
     profile: 2.2
     connection_timeout: 10
     read_write_timeout: 30

Doctrine Cache Configuration

doctrine_cache:
    providers:
        redis_cache:
            redis:
                host: 127.0.0.1
                port: 6379
                database: 3
        websocket_cache_client:
            type: redis
            alias: gos_web_socket.client_storage.driver.redis

Session Handler configuration

    pdo:
      class: PDO
      arguments:
          dsn: mysql:host=%database_host2%;dbname=%database_name2%
          user: %database_user2%
          password: %database_password2%
      calls:
          - [ setAttribute, [3, 2] ] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

  session.handler.pdo:
      class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
      arguments: [@pdo, {lock_mode: 0}]

GOS client Store driver configuration
gos_web_scocket.client_storage.driver.predis:
    class: Gos\Bundle\WebSocketBundle\Client\Driver\PredisDriver
    arguments:
        - @snc_redis.client_storage.driver_client

My service

some.topic_test_service:
    class: Backend\SomeBundle\Topic\SomTopic
    arguments: [ @gos_web_socket.websocket.client_manipulator, @some.service]

Routing Channel configuration
some_topic:
  channel: some/channel
  handler:
    callback: 'backend.some'

Topic class with periodic call
class SomeTopic implements TopicInterface, TopicPeriodicTimerInterface
{

    /**
     * @var TopicPeriodicTimer
     */
    protected $periodicTimer;
    /**
     * @var ClientManipulatorInterface
     */
    protected $clientManipulator;

    /**
     * @var SomeService
     */
    protected $SomeService;
    private $i;

    /**
     *
     * param [ mixed $args [, $... ]]
     * @param ClientManipulatorInterface $clientManipulatorInterface
     * @param SomeService $transactionService
     * @param ContainerInterface $container
     * @internal param TokenStorageInterface $token
     * @link http://php.net/manual/en/language.oop5.decon.php
     */
    function __construct(ClientManipulatorInterface $clientManipulatorInterface,
                         SomeService $someService)
    {
        $this->clientManipulator = $clientManipulatorInterface;
        $this->someService = $someService;
        $this->i = 0;
    }

    /**
     * @param  ConnectionInterface $connection
     * @param  Topic $topic
     * @param WampRequest $request
     */
    public function onSubscribe(ConnectionInterface $connection, Topic $topic, WampRequest $request)
    {
        
        $user = $this->clientManipulator->getClient($connection);
        $topic->broadcast("Hello World ".$user);
    }

    /**
     * @param  ConnectionInterface $connection
     * @param  Topic $topic
     * @param WampRequest $request
     */
    public function onUnSubscribe(ConnectionInterface $connection, Topic $topic, WampRequest $request)
    {
        //this will broadcast the message to ALL subscribers of this topic.
        $topic->broadcast(['msg' => $connection->resourceId . " has left " . $topic->getId()]);
    }

    /**
     * @param  ConnectionInterface $connection
     * @param  Topic $topic
     * @param WampRequest $request
     * @param $event
     * @param  array $exclude
     * @param  array $eligible
     */
    public function onPublish(ConnectionInterface $connection, Topic $topic, WampRequest $request, $event, array $exclude, array $eligible)
    {
        /*
            $topic->getId() will contain the FULL requested uri, so you can proceed based on that

            if ($topic->getId() == "acme/channel/shout")
               //shout something to all subs.
        */
        $topic->broadcast([
            'msg' => $event
        ]);
    }

    /**
     * @return string
     */
    public function getName()
    {
        return "backend.some";
    }

    /**
     * @param Topic $topic
     *
     * @return mixed
     */
    public function registerPeriodicTimer(Topic $topic)
    {
        $this->periodicTimer->addPeriodicTimer($this, 'some', 10, function() use ($topic){           
            $topic->broadcast("Hello World ".$this->i++);
        });

        //exist
        $this->periodicTimer->isPeriodicTimerActive($this, 'some'); // true or false

        //remove
        $this->periodicTimer->cancelPeriodicTimer($this, 'some');
    }

    /**
     * @param TopicPeriodicTimer $periodicTimer
     */
    public function setPeriodicTimer(TopicPeriodicTimer $periodicTimer)
    {
        $this->periodicTimer = $periodicTimer;
    }
}

When the websocket send the information about the user all time the user is anon-210954636255afb7a3535fe598094366 and I'm logged with other user.

Any idea??

**Comment by ProPheT777** [comment]
Yes I have an idea, what is domain name of your web application, and the domain inside %clank_host% ?

They should be the same e.g : app domain / app websocket -> dev.com / dev.com:1337 will work whereas dev.com / 127.0.0.1:1337 will not.

**Comment by ProPheT777** [comment]
I dont think it'll change something, we use cookie to auth user. So we need to have the same domain name in order to share the cookie. 
Le 22 juil. 2015 18:18, Rolando <notifications@github.com> a écrit :Right now the domain is 0.0.0.0:8800

**Comment by rtoledof** [comment]
Can I shared the cookies using a private address IP for example 192.168.90.100:8800 ??? or need use a domain name only??? I think is the same user 0.0.0.0:8800 or dev.com:8800 for my is the same address only using 0.0.0.0:8800 the other clients can connect using the server IP address

**Comment by ProPheT777** [comment]
You can use private IP of course, but you must use it for both side (application and websocket) 

192.168.90.100:8800 (web) ---> 192.168.90.100:1337 (websocket)

and that will work.

If you want have different domain between web app and web socket you'll have to configure proxy_pass of your http server to share cookie accross your domain.

**Comment by rtoledof** [comment]
Right know I connect to client at the server and I have the same problem. When the user login and connect to the websocket $this->clientManipulator->getClient($connection); get the user anonymous onli change the second part at the user information but it is the anonymous user. In the socket connection when client connect the socket said 

INSERT CLIENT 2717 {"user":"s:35:\"anon-2054947255b2043995149411394812\";"} 

and I don't why if I'm logged with a user I think the socket should be store the logged user but doesn't do that. Do you know what is the probably reason??

**Comment by ProPheT777** [comment]
Which firewall your client is connected to ? Because you must specify firewall in order to retrieve the right user through firewall. 
Check the security config if the firewall name is the same as you fill in gos websocket config 
Le 24 juil. 2015 09:32, Rolando <notifications@github.com> a écrit :Right know I connect to client at the server and I have the same problem. When the user login and connect to the websocket $this->clientManipulator->getClient($connection); get the user anonymous onli change the second part at the user information but it is the anonymous user. In the socket connection when client connect the socket said 

INSERT CLIENT 2717 {"user":"s:35:\"anon-2054947255b2043995149411394812\";"} 

and I don't why if I'm logged with a user I think the socket should be store the logged user but doesn't do that. Do you know what is the probably reason??

**Comment by rtoledof** [comment]
Where is my security.yml

security:
  providers:
    chain_provider:
      chain:
        providers: [api_key_user_provider, database_users]

    database_users:
      entity: { class: BackendSecurityBundle:User, property: username, manager_name: security }

    api_key_user_provider:
      id: api_key_user_provider

  encoders:
    Backend\SecurityBundle\Entity\User: bcrypt

  role_hierarchy:
    ROLE_MERCHANT:        ROLE_USER
    ROLE_RISK:            ROLE_USER
    ROLE_TECSUPPORT:      [ROLE_MERCHANT,ROLE_USER]
    ROLE_PERMISSIONS:     ROLE_USER
    ROLE_SEO:             [ROLE_MERCHANT,ROLE_RISK,ROLE_TECSUPPORT]
    ROLE_ADMIN:           [ROLE_PERMISSIONS, ROLE_SEO]
    ROLE_SUPERADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt|error)|css|images|js)/
      security: false

    backend_secure_area:
      pattern: ^/
      anonymous: ~
      provider: api_key_user_provider
      simple_preauth:
        authenticator: apikey_authenticator
      form_login:
        check_path: security_login_check
        login_path: security_login_form
        use_referer: true
        csrf_provider: security.csrf.token_manager
        default_target_path: main_homepage

      logout:
        path: security_logout
        target: main_homepage

  acl:
    connection: security

  access_decision_manager:
    strategy: affirmative

  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: [ROLE_ADMIN,ROLE_USER] }

And here is my gos-web_socket settings

gos_web_socket:
    server:
        port: "%clank_port%"   #The port the socket server will listen on
        host: "%clank_host%"   #The host ip to bind to
        router:
          resources:
            - @SomeBundle/Resources/config/pubsub/routing.yml

    shared_config: false

    topics:
      - @transaction.topic_test_service

    client:
      firewall: backend_secure_area
      session_handler: @session.handler.pdo
      storage:
        driver: @gos_web_socket.client_storage.driver.redis
        decorator: @gos_web_socket.client_storage.doctrine.decorator

**Comment by ProPheT777** [comment]
can you paste your parameters.yml and the framework configuration (in config.yml) please ?

**Comment by rtoledof** [comment]
There is my parameters.yml

# This file is a "template" of what your parameters.yml file should look like
# Set parameters here that may be different on each deployment target of the app, e.g. development, staging, production.
# http://symfony.com/doc/current/best_practices/configuration.html#infrastructure-related-configuration
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: dev
    database_user: root
    database_password:

    database_driver2: pdo_mysql
    database_host2: 127.0.0.1
    database_port2: null
    database_name2: user_security
    database_user2: root
    database_password2:

    per_page: 200

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password:

    clank_host: 0.0.0.0
    clank_port: 8800
    secret: ca8a5c8c3b06ba0d4cd1a802b90054d4b21e0a1d


And there is my confid.yml

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  session.handler.pdo
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

    globals:
        clank_host:    "%clank_host%"
        clank_port:    "%clank_port%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        []
    java: /usr/bin/java
    filters:
        cssrewrite: ~
#        closure:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8

            security:
                driver:   "%database_driver2%"
                host:     "%database_host2%"
                port:     "%database_port2%"
                dbname:   "%database_name2%"
                user:     "%database_user2%"
                password: "%database_password2%"
                charset:  UTF8

        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"



    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    MainBundle:  ~
            security:
                connection: security
                mappings:
                    BackendSecurityBundle: ~
                    NomenclatorBundle: ~
#        auto_generate_proxy_classes: "%kernel.debug%"
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

white_october_breadcrumbs:
    separator: ''
    viewTemplate: "MainBundle:Default:breadcrumb.html.twig"

maxmind_geoip:
  data_file_path: "%kernel.root_dir%/../web/GeoIP/GeoLiteCity.dat"

snc_redis:
    clients:
        ws_client:
            type: predis
            alias: client_storage.driver #snc_redis.client_storage.driver
            dsn: redis://127.0.0.1/2
            logging: %kernel.debug%
            options:
                profile: 2.2
                connection_timeout: 10
                read_write_timeout: 30

doctrine_cache:
    providers:
        redis_cache:
            redis:
                host: 127.0.0.1
                port: 6379
                database: 3
        websocket_cache_client:
            type: redis
            alias: gos_web_socket.client_storage.driver.redis

gos_web_socket:
    server:
        port: "%clank_port%"   #The port the socket server will listen on
        host: "%clank_host%"   #The host ip to bind to
        router:
          resources:
            - @SomeBundle/Resources/config/pubsub/routing.yml

    shared_config: false

    topics:
      - @transaction.topic_test_service

    client:
      firewall: backend_secure_area
      session_handler: @session.handler.pdo
      storage:
        driver: @gos_web_socket.client_storage.driver.redis
        decorator: @gos_web_socket.client_storage.doctrine.decorator

**Comment by ProPheT777** [comment]
Change this :     `clank_host: 0.0.0.0` by your application URL that you hit when you navigate with your browser.

**Comment by rtoledof** [comment]
I change it for My IP address and it doesn't work.

I'm using nginx and I've a virtual host name someweb.local. In my local machine I change the hosts file and declare the 127.0.0.1 is someweb.local. In other machine I changed the hosts file and indicate my IP is someweb.local for access using the domain name in the other machine. I opened the url in both machines and both are connected to the websocket but the ClientManipulator gave me the anon user in both clients. The socket send the information for both browsers but in both case the user is anonymous even if in both clients are login with the different users.

I think the clank_host is not the problem.

Debugging the application I showed the client manipulator class is initialize in three times and in the firth he have the logged user but in the others the user disappear and I only require the service a time. That may be the problem? If it is the problem How can I initialize only one time or the bundle initialize more times the ClientManipulator??

**Comment by hermandinho** [comment]
any solution for this issue?

**Comment by some** [comment]
--------------------------------------------
On Sat, 4/16/16, Demsong Tsamo Herman <notifications@github.com> wrote:

 Subject: Re: [GeniusesOfSymfony/WebSocketBundle] ClientManipulatorInterface (#46)
 To: "GeniusesOfSymfony/WebSocketBundle" <WebSocketBundle@noreply.github.com>
 Cc: "some" <some_777@yahoo.com>
 Date: Saturday, April 16, 2016, 8:29 AM
 
 any solution for this issue?
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly or view
 it on GitHub
