### ISSUE TITLE
Multiple applications on the same server - single websocket server?

### ISSUE THREAD

**Issue by MuddyPaw** [GeniusesOfSymfony/WebSocketBundle#47]
Hi, I have a multiple applications that would run pretty much the same code base on the same server. Is there a way to avoid launching a websocket server for each one? Having them on separate channels would not be a solution since the server would not be able to match the other routes.

**Comment by ProPheT777** [comment]
Actualy there is no router to dispatch application, this will be implemented on the next version :)

**Comment by ProPheT777** [comment]
After deep look into this feature, I will not do it because that break all side feature and imply a lot of overhead to restore them. Sorry :(
