### ISSUE TITLE
Update to support modern Autobahn version.

### ISSUE THREAD

**Issue by Maclay74** [GeniusesOfSymfony/WebSocketBundle#470]
Hey, the client library is based on 0.8.2 version of Autobahn, which is very old one. (Current is 20.9.2).
For example, it's not possible to make it work with React Native.

I see that client isn't that complicated, but I can't meet some points there. 

I added browser version of autobahn and 
```js
import * as Autobahn from 'autobahn-browser/autobahn';
```
I changed connection method
```js
static connect(uri, sessionConfig = null) {
    if (typeof Autobahn === 'undefined') {
      throw new Error('GosSocket requires AutobahnJS to be loaded.');
    }

    return new GosSocket(Autobahn, uri, sessionConfig);
  }
```

But I can't figure our how to handle connection
```js
this._autobahn.connect(
      uri,
      session => {
        this._session = session;

        this._fire('socket/connect', session);
      },
      (code, reason, detail) => {
        this._session = null;

        this._fire('socket/disconnect', {code: code, reason: reason});
      },
      sessionConfig,
    );
```

According to documentation, it should look kinda like that
```js
    this._session = new Autobahn.Connection({
      uri,
    });
```
So we don't have session nor disconnection callback anymore.

I'll try to figure it out myself, but if anybody could help a little or done it before, I'd appreciate it.

**Comment by mbabker** [comment]
Updating the JavaScript bundle in and of itself is probably the least effort here.

Autobahn|JS 0.8.2 is the last version to support the WAMPv1 protocol, which is what Ratchet and this bundle are written around.  The WAMPv2 protocol has a number of changes from v1, so being able to use a newer Autobahn|JS version essentially requires a backend server that's WAMPv2 compliant.

**Comment by Maclay74** [comment]
Oh boy, things are much more complicated than I thought :D 

Okay, it this case, do you think it's possible to use it with modern module-based approach? I can't use global scope :c

**Comment by Maclay74** [comment]
Okay, I figured it out myself.

I grabbed source code for 0.8.2 version.
then 
```js
import * as autobahn from './autobahn.min.js';
``` 
in gos js library and fixed global scope usage.

Plus, needed to fix deferred, since whenjs didn't work too:
```js
  //ab.Deferred = when.defer;
  //ab.Deferred = jQuery.Deferred;

  ab.Deferred = () => {
    const deferred = {};
    const promise = new Promise(function (resolve, reject) {
      deferred.resolve = resolve;
      deferred.reject = reject;
    });
    deferred.promise = promise;
    return deferred;
  };
```

**Comment by mbabker** [comment]
I ended up forking and stripping down Autobahn in a client project.  In truth, there isn't much special about Autobahn|JS unless you're using their features (especially the authentication stuff, which is functionality specific to their build and not part of the WAMPv1 spec); for a lot of cases, the functionality you'll need is in the core browser `WebSocket` object or is easily re-created with modern JavaScript constructs (i.e. our Deferred replacement is a 41-line TypeScript file, including whitespace); what Autobahn|JS excels at is wiring up the browser `WebSocket` object with the right config and pretty strong event listeners for the core events, then exposing a bunch of hook points throughout the process with all the callbacks you can provide.  The JavaScript client in this bundle simplifies that down even further by giving default callbacks to the `ab.connect()` function's `onconnect` and `onhangup` parameters and emitting events at those hook points.

**Comment by helveden** [comment]
Hello, is it possible to connect without Autobahn with a websocket configuration like below?

```
// Create WebSocket connection.
const socket = new WebSocket('ws://localhost:8080');

// Connection opened
socket.addEventListener('open', (event) => {
     socket. send('Hello Server!');
});

// Listen for messages
socket. addEventListener('message', (event) => {
     console.log('Message from server', event.data);
});
```

Because I'm improving in JS.

I'm using React-native and figured out a bad practice (document.write) to add the autobahn file with no success.

**Comment by mbabker** [comment]
Yes, you can.  The main thing Autobahn does is add handling for WebSocket messages based on the WAMP specification (v1 for 0.8.2 and earlier, v2 for 0.9 to present).  By design, WAMP is a standardized message structure that can be transmitted across supported transports, primarily through a WebSocket connection.

You can dig through https://github.com/crossbario/autobahn-js/blob/v0.8.2/autobahn/autobahn.js to see how it works under the hood and work out how to move forward in your own app (just be respectful of their MIT licensed code).

**Comment by Maclay74** [comment]
@mbabker I see that 4.x version is in active development, do you have plans about moving to WAMP v2 or it's going to keep it as it is?

And, in general, starting a new application right now, is it better to wait for stable 4.x or migration from 3.x to 4.x won't be painful? 

Thanks.

**Comment by mbabker** [comment]
It's staying on WAMPv1 because the amount of changes in the spec would be better suited for a new bundle.  There's Thruway which handles the v2 stuff more efficiently but admittedly it doesn't seem as actively developed on.

Stick with the 3.x branch here.  It's plenty stable (even if based on a long deprecated version of the spec).
