### ISSUE TITLE
New authentication flow using JWT

### ISSUE THREAD

**Issue by Maclay74** [GeniusesOfSymfony/WebSocketBundle#471]
We have a nice example of JWT token authentication for the legacy auth system, but I'm struggling with doing so with the new one.

I created a factory to register a new provider
```php
class AuthProviderFactory implements AuthenticationProviderFactoryInterface
{

    public function createAuthenticationProvider(ContainerBuilder $container, array $config): string
    {
        $providerId = 'gos_web_socket.authentication.provider.jwt';
        $container->register($providerId, AuthProvider::class);

        return $providerId;
    }

    public function getKey(): string
    {
        return "jwt";
    }

    public function addConfiguration(NodeDefinition $builder): void
    {

    }
}
```
Enabled new authentication and added it
```yaml
gos_web_socket:
    authentication:
        enable_authenticator: true
        providers:
            jwt: true
```

I also implemented `AuthenticationProviderInterface` but I'm not sure I understand the way it supposed to work

```php
class AuthProvider implements AuthenticationProviderInterface, LoggerAwareInterface {

    use LoggerAwareTrait;

    private TokenStorageInterface $tokenStorage;

    /**
     * @var JWTTokenManagerInterface
     */
    private JWTTokenManagerInterface $jwtManager;

    /**
     * @var JWSProviderInterface
     */
    private JWSProviderInterface $JWSProvider;

    /**
     * @var JWTUserProvider|UserProviderInterface
     */
    private UserProviderInterface|JWTUserProvider $jwtUserProvider;


    public function __construct(UserProviderInterface $JWTUserProvider, JWTTokenManagerInterface $jwtManager, JWSProviderInterface $JWSProvider)
    {
        $this->jwtUserProvider = $JWTUserProvider;
        $this->JWSProvider = $JWSProvider;
        $this->jwtManager = $jwtManager;
    }

    public function supports(ConnectionInterface $connection): bool
    {
        return isset($connection->Jwt) && is_string($connection->Jwt);
    }

    public function authenticate(ConnectionInterface $connection): TokenInterface
    {
        return $this->getToken($connection);
    }

    private function getToken(ConnectionInterface $connection): TokenInterface
    {

        /** @var RequestInterface $req */
        $req = $connection->httpRequest; // do we have request there? IDE says we don't 

        $bearer = $req->getHeader('Authorization')[0]; // Get jwt from the request

        $jws = $this->JWSProvider->load($bearer); // decode token

        $user = $this->jwtUserProvider->loadUserByIdentifier($jws->getPayload()['email']); // find user

        return new JWTUserToken(
            user: $user,
            rawToken: $bearer
        );

    }
}
```

Please, tell me two things:
How do I pass JWT from the client when connect? I didn't find any example of it in documentation or issues :c 
What's wrong with my implementation? I'll figure `authenticate` out myself, but not sure I configured everything correctly :с

Thanks a lot.

**Comment by mbabker** [comment]
In your supports method, check to make sure the httpRequest is present (the Ratchet stack has a lot of dynamic properties, it should be there but doesn't hurt to verify) and the request has the header with the info you need.  Your authenticate method looks fine.

Also make sure you're registering the authenticator factory to this bundle's container extension (see the Bundle class' build method for an example, not by a computer right now so it's a little harder to check other stuff).

**Comment by Maclay74** [comment]
Thanks! I'll do additional checks right away

> make sure you're registering the authenticator factory

Sure, I added it to the Kernel, forgot to mention
```php
class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    protected function build(ContainerBuilder $container): void
    {
        /** @var GosWebSocketExtension $extension */
        $extension = $container->getExtension('gos_web_socket');
        $extension->addAuthenticationProviderFactory(new AuthProviderFactory());
    }
}
```

Could you please explain, how to send token from the client and when? I don't understand the order of actions. 

We have `GosSocket.connect` method, that accepts a url. 

I assume it doesn't do any authorization at this moment and always connects user wherever it came from.

But when we `call` methods it does authorization, so I should pass my JWT token there? But I try to retrieve it from `httpRequest` which doesn't make sense in websockets context.

I'm little confused here.

**Comment by mbabker** [comment]
The token should be part of the HTTP request that goes to the server to initiate the websocket connection (which, TBH, I have no idea if you have any control over that through the provided JavaScript resources; it's not something I've ever really looked at).  The idea is that the user is authenticated after the higher level Ratchet components parse and validate the HTTP request as allowed for the websocket server, and then the user is authenticated for the lifetime of that connection with whatever authentication you're using

**Comment by Maclay74** [comment]
Got it, thanks! Will try to implement it.

**Comment by Maclay74** [comment]
It works, thanks.

**Comment by stevro** [comment]
@Maclay74 , cand you post your sample on how you have sent the JWT from the client to the server?

**Comment by Maclay74** [comment]
Hey, I made a few adjustment to autobahn and websockets, not sure there are all of them, but kinda like that
```js
// app level
GosSocket.connect(uri, {token}); // Pass token here

// autobahn.js - change constructor
ab._construct = function (url, protocols, token) {
    return new WebSocket(url, protocols, {headers: {Authorization: token}});
  };

// ab.Session 
if (self._options && self._options.skipSubprotocolAnnounce) {
   self._websocket = ab._construct(self._wsuri, null, options.token);
  } else {
   self._websocket = ab._construct(self._wsuri, [ab._subprotocol], options.token);
}

```

**Comment by stevro** [comment]
Do you maybe can share the full autobahn.js file? If I download the one from https://github.com/crossbario/autobahn-js/tree/v0.8.2 it gives an error in Gos saying autobahn is not found, and in this repo I only see the minified version.

I ended up using a query parameter for my token, but your solution seems more elegant.

One extra question, I don't see a third argument to the WebSocket constructor...I wonder if this still works today... https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket

**Comment by Maclay74** [comment]
Sure, here it is.

https://gist.github.com/Maclay74/e1f946724a8b1776f8d558e3bd130e4b
