### ISSUE TITLE
Subscribe to topic on server

### ISSUE THREAD

**Issue by Maclay74** [GeniusesOfSymfony/WebSocketBundle#472]
Hey, I'm working on an application with multiple chats and I treat them as topics. 
The thing is, I'd like to subscribe user to chats they participate in on connection. 

So I added an event listener
```php
public function onClientConnect(ClientConnectedEvent $event) {
    $conn = $event->getConnection();

    /** @var User $user */
    $user = $this->connectionRepository->getUser($conn);

    /** @var Chat $chat */
    foreach ($user->getChats() as $chat) {
        $topic = $this->topicManager->getTopic("chat/" . $chat->getId());

        if (!$topic->has($conn))
            $topic->add($conn);
    }
}
 ```       

The problem is, I don't understand how do I catch such messages on frontend. According to the documentation, I pass a callback on subcribe
```js
// The callback function in "subscribe" is called every time an event is published in that channel.
session.subscribe('acme/channel', function (uri, payload) {
    console.log('Received message', payload);
});
```

But since I subscribe on backend, how do I do this?.. 
Thanks a lot!

**Comment by mbabker** [comment]
You have to subscribe client side.  The Autobahn library makes its own checks when the client receives a message to decide if a callback function should be called, so if that's not tracking all of the subscriptions then things won't work right.

**Comment by Maclay74** [comment]
Got it, thanks!
