### ISSUE TITLE
Does this bundle support SSL (wss)

### ISSUE THREAD

**Issue by amigian74** [GeniusesOfSymfony/WebSocketBundle#49]
Since Ratchet doen't support SSL (wss) - does this bundle support SSL?

Thx in advance

**Comment by ProPheT777** [comment]
Yes it is !

**Comment by amigian74** [comment]
Thx for the quick answer, but I tried to run the example with wss://127.0.0.1 or wss://127.0.0.1:8443 but no connection could be established - did I miss something?

**Comment by ProPheT777** [comment]
I will test this week end

**Comment by ProPheT777** [comment]
After deep looking, wss is supported but need server config.

You can look at https://github.com/ratchetphp/Ratchet/issues/161
