### ISSUE TITLE
Origin checker

### ISSUE THREAD

**Issue by ProPheT777** [GeniusesOfSymfony/WebSocketBundle#5]
Hi @gittix09, have you plan to use the origin checker feature ? If yes i'm interested to have your feedback about it ! 

Thank you very much !

**Comment by gittix09** [comment]
Hello!!
What is the origin checker feature? Can you link me the reference in the documentation?

**Comment by ProPheT777** [comment]
Here the doc : https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/OriginCheck.md

This feature is to secure your application against external connection to your websocket

**Comment by gittix09** [comment]
Sure, I will test it as soon as possible on XAMPP and let you know. 
Testing it outside XAMPP will require a little more time.

**Comment by ProPheT777** [comment]
Great news, thank you very much.
