### ISSUE TITLE
Websocket server crashes if user roles are stored in database

### ISSUE THREAD

**Issue by AchilleAsh** [GeniusesOfSymfony/WebSocketBundle#51]
I'm facing an issue with the server when user roles are stored in a database : 

> PHP Fatal error:  Call to a member function toArray() on a non-object
> in [...]/Entity/Users.php on line 308 [2015-08-15 23:44:39]
> php.CRITICAL: Fatal Error: Call to a member function toArray() on a
> non-object
> {"type":1,"file":"[..]/Entity/Users.php","line":308,"level":-1,"stack":[]}
> 
> 
> 
>   [Symfony\Component\Debug\Exception\FatalErrorException]        Error:
> **Call to a member function toArray() on a non-object**

So I have digged into the code and the error is here :
**File [Client\Auth\WebsocketAuthenticationProvider.php] : 119**

> $user instanceof UserInterface ? implode(', ', **$user->getRoles()**) : array()

If roles are set in a database (as explained in the Symfony doc), Symfony will fail to fetch the roles with $user->getRoles(); if roles are added to the user serialize, it will fail due to a bug apparently introduced in serialize() in PHP 5.4, and I didn't manage to get around it using json_encode / decode trick.
However, it is possible to easily retrieve the user roles from the token :
> $roles = **$token->getRoles()**
 
A simple fix could be to remove the user roles display, but I don't know if roles are used elsewhere

Otherwise great bundle, thank you :+1:

**Comment by ProPheT777** [comment]
Thank's for your feedback, it's fixed.

Thank you @AchilleAsh
