### ISSUE TITLE
Unrecognized options "channel, handler" under acme_topic

### ISSUE THREAD

**Issue by NicolasFacciolo** [GeniusesOfSymfony/WebSocketBundle#55]
Hello, 

I am at Step 4 : Link channel & topic with pubsub router of the description installation of the WebSocketBundle and I get this error: Unrecognized options "channel, handler" under acme_topic. 

I think it's a problem with pubsub, i created  AcmeBundle/Resources/config/pubsub/routing.yml but what did you mean when you said register it in the websocket bundle configuration?

**Comment by NicolasFacciolo** [comment]
I compared to your demoBundle and I did exactly the same things except that my bundle is not directly in src, it's in Acme/AppBundle and not directly in AppBundle. Do you think that the problem is here? 

Sorry for my bad english :)

**Comment by NicolasFacciolo** [comment]
Ok I found out the solution, I put the router config in the yml file... -.-' and not in the pubsub router... 

Bye!

**Comment by ProPheT777** [comment]
no problem ;)
