### ISSUE TITLE
Duplicated packages

### ISSUE THREAD

**Issue by youbs** [GeniusesOfSymfony/WebSocketBundle#58]
Hi guys,

This bundle depends on `gos/ratchet` and `gos/ratchet-stack`, but `gos/ratchet-stack` depends on `cboden/ratchet`, so both of them are downloaded and autoloaded by composer, which results in conflicts.

What would be the way to fix this? Maybe replace completely `cboden/ratchet` by `gos/ratchet`?

I opened this issue here but it may be more appropriate in the ratchet-stack repository?

PS: Thank you for all your work, the improvements you made are awesome!

**Comment by ProPheT777** [comment]
> I opened this issue here but it may be more appropriate in the ratchet-stack repository? 

Nope that's good.

This is blocking you ? Because I think I think I will suggest a pull request of my changes instead of have a "private fork". 

And I want keep `gos/ratchet-stack` available for ratchet.

**Comment by benr77** [comment]
I think my issue is related. If I use any version above 1.3.2 then I get the following exception:

`[Symfony\Component\Debug\Exception\ContextErrorException]                                                         
  Catchable Fatal Error: Argument 1 passed to Ratchet\Wamp\TopicManager::__construct() must implement interface Ra  
  tchet\Wamp\WampServerInterface, none given, called in app/cache/dev/appDevDebugProjectContainer.php on line 5181 and defined`

**Comment by ProPheT777** [comment]
Yes I think it's because you have not clear your vendor. Have another package who depend of ratchet ?

**Comment by youbs** [comment]
Hi,

That's actually the problem I described, I think a solution would be to offer the possibility to replace cboden/ratchet with gos/ratchet (if you maintain BC) so for now I forked gos/ratchet and added a composer `replace` setting (see https://github.com/youbs/Ratchet/blob/master/composer.json#L32-L39). It seems to work for me. What do you think?
