### ISSUE TITLE
Personalized Methods for ClientManipulator

### ISSUE THREAD

**Issue by cristhianfernandez01** [GeniusesOfSymfony/WebSocketBundle#62]
Hello, I have a question concerning of client manipulation. I use Symfony users (which implements the Symfony\Component\Security\Core\User\UserInterface interface), which works perfectly  to obtain the user through the firewall. For obtain these users use the ClientManipulator that is defined in the bundle. But I need to find users using a different method to findByUsername or findByRoles (I wish I could do looking through another own attribute of the User class). How can I do?

**Comment by ProPheT777** [comment]
You can create your own implementation. 

Just implement `ClientManipulatorInterface` or extend from `ClientManipulator` expose function that you want and add logic. Then declare the service in DI  and inject it like you currently did :)

**Comment by ProPheT777** [comment]
Hi, 

You can do it by creating you own client manipulator implementation by implementing `ClientManipulatorInterface` or by extending `ClientManipulator` then just register your service in the DI like any other services and inject it like you did with ClientManipulator

**Comment by cristhianfernandez01** [comment]
Thank you!!! I will make the implementation of ```ClientManipulatorInterface``` interface in my own Class ```AppClientManipulator```. Regards
