### ISSUE TITLE
get users from ConnectionInterface object

### ISSUE THREAD

**Issue by NicolasFacciolo** [GeniusesOfSymfony/WebSocketBundle#63]
Hey

I would like get the currently user from the connection object in the onSubscribe method of ChatTopic.

Plz can you say me where onSuscribe method is called and where is implemented your personnal connexionInterface object? :)

**Comment by NicolasFacciolo** [comment]
I found out this solution: $connection->Session->all()["_security_main"] and then I retrieve the current user with the user manager. Do you have a more lightweight solution? 

By the way, I don't use no sql, it's why I can't implement your solution.

**Comment by ProPheT777** [comment]
You don't need to do that to retrieve the current user. 

Look at this docs : https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/SessionSetup.md 

:)

**Comment by NicolasFacciolo** [comment]
I already tryed it, I get just the string username by it. I would like have all the user object. :)

**Comment by NicolasFacciolo** [comment]
In fact, I have access to the method of my user entity but some are null

**Comment by NicolasFacciolo** [comment]
ok my solution is to get the user from the user_manager with the user id which is get by the user manipulator
