### ISSUE TITLE
Ssl server configuration

### ISSUE THREAD

**Issue by NicolasFacciolo** [GeniusesOfSymfony/WebSocketBundle#64]
Hello, 

Where can I config the server with ssl ? I saw that link: https://github.com/ratchetphp/Ratchet/issues/161 
but i don't know where are the files which I have to modifie.

**Comment by ProPheT777** [comment]
You can use SSL, but you will need to archieve it on server side (nginx) via stunnel.

By nature php is too slow to decode ssl payload on the fly and have a huge performance impact.

Stunnel -> https://www.stunnel.org/index.html

configuration : 

```ini
[websockets]
accept = 8443
connect = 8888
```

**Comment by NicolasFacciolo** [comment]
# That works very well: install stunnel for linux: 
        apt-get install stunnel
        nano /etc/stunnel/myconf.conf

# put in the file all the following line until the next ########

##############################################################
##############################################################

# Sample stunnel configuration file for websockets

# Provide the full path to your certificate-key pair file
cert = /my/way/to/ssl.crt
key = /my/way/to/not_crypted.key

# lock the process into a chroot jail
chroot = /var/run/stunnel4/
# and create the PID file in this jail
pid = /stunnel.pid

# change the UID and GID of the process for security reasons
setuid = nobody
#setgid = nobody

# Configure our secured websocket service

[websockets]
accept = 8443   #acceptport 
connect = 8888 #connectport

###################################################
###################################################

        launch your websocket server in the connectport
        connect in the client view on wss://mysite:acceptport

hooowwww that works!! :) 

If you think there is a better conf, feel free to tell me! 
for exemple the setgid = nobody doest work for me :)

**Comment by ProPheT777** [comment]
Thank's for the feedback, I'll update the docs with your explaination or feel free to open on PR and add SSL support section

**Comment by NicolasFacciolo** [comment]
I would like do it with pleasure but I'm too busy :)

**Comment by ProPheT777** [comment]
done
