### ISSUE TITLE
more then one ws server possible?

### ISSUE THREAD

**Issue by Venzon** [GeniusesOfSymfony/WebSocketBundle#66]
Is there a way to configure and start more then one ws server - each running on different port?

Regards

**Comment by ProPheT777** [comment]
Yes absolutely,

According to Command file : 

https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Command/WebsocketServerCommand.php#L64

You can add `-p 1337` or `--port 1337`

**Comment by Venzon** [comment]
@ProPheT777 thanks for your answer - it solved my issue partialy
Is there a way to configure in config.yml more then one server and define different services on each one?
Runnig same configuration on different ports will make all services available on every ws sever...
Regards

**Comment by ProPheT777** [comment]
Yes this is the limitation actually you just can define different port in order to load balance but you can't configure multiple ws server in the same application.

**Comment by Venzon** [comment]
@ProPheT777 ok thank you - grats for great bundle - for sure will use it instead of clankbundle
