### ISSUE TITLE
SecurityContextInterface is deprecated since Symfony 2.6

### ISSUE THREAD

**Issue by kachkaev** [GeniusesOfSymfony/WebSocketBundle#67]
This issue is a reminder to replace SecurityContextInterface with corresponding alternatives in the following two classes:
 ```Gos\Bundle\WebSocketBundle\Client\Auth\WebsocketAuthenticationProvider```
 ```Gos\Bundle\WebSocketBundle\Event\ClientEventListener```

Security context is deprecated since 2.6:
http://symfony.com/blog/new-in-symfony-2-6-security-component-improvements

Meanwhile, the use of the bundle causes two warnings in the profiler:
![screen shot 2015-10-09 at 20 25 25](https://cloud.githubusercontent.com/assets/608862/10403477/c307b778-6ec3-11e5-8a6a-2adb8b649a55.png)

**Comment by ProPheT777** [comment]
yes thx
