### ISSUE TITLE
The parameter "gos_pubsub_registered_routers" must be defined.

### ISSUE THREAD

**Issue by julienfroidefond** [GeniusesOfSymfony/WebSocketBundle#68]
Hi,

When I try to launch the server in prod mode : 

> php app/console gos:websocket:server --env=prod

I get this error : 

> [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
> The parameter "gos_pubsub_registered_routers" must be defined.

The same error when I try a 
> php app/console cache:clear --env=prod. 

All is good for the dev environment.

Thx

**Comment by ProPheT777** [comment]
hi, 

have you try to clear by the hand cache directory (with rm) ? 
what is the version of bundle you are currently using ?

**Comment by julienfroidefond** [comment]
Hi, 

I just found that deleting the cache sent me another error. (something with debug.stopwatch is not a known service). I think my dependencies aren't well done. (I'm in symfony 2.4.x-dev and the  	setDecoratedService() doesn't exists; when i go to 2.5, I have the stopwatch problem.)
The solution I found is to work with the 1.4.2 release. In that version everything seems to be ok.
Thx for your answer.

**Comment by ProPheT777** [comment]
I think you can upgrade to 1.5.2 without problem.

**Comment by julienfroidefond** [comment]
It works ! Thx !

**Comment by eduinredes** [comment]
Hi, 
i'm having the same problem with launch  and cache clear in --env=prod, i'm in symfony 2.8.*-dev and gos/web-socket-bundle 1.6, How i can help you to solve this problem?

**Comment by ProPheT777** [comment]
You have problem with the stopwatch component? or just no router is registered?

Anyway if you can paste your websocket_bundle configuration in config.yml I'll be able to help you ;)

**Comment by eduinredes** [comment]
this is the configuration that i'm using
`gos_web_socket:
    server:
        port: 8080        #The port the socket server will listen on
        host: 127.0.0.1   #The host ip to bind to
        router:
            resources:
                - @EduinMGSVCMBundle/Resources/config/pubsub/routing.yml`

i dont know nothing about stopwatch component.
This are the error that I get:
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]  
  The parameter "gos_pubsub_registered_routers" must be defined.

**Comment by BallisticPain** [comment]
Is there any resolution here?! :( We are having the `The parameter "gos_pubsub_registered_routers" must be defined.`

**Comment by BallisticPain** [comment]
Manual deleting of the cache worked for us.
