### ISSUE TITLE
Call to undefined function Gos\Bundle\PubSubRouterBundle\Matcher\dump()

### ISSUE THREAD

**Issue by Don87** [GeniusesOfSymfony/WebSocketBundle#69]
First off, a fantastic and very interesting bundle.

I have been struggling with this issue for the past 12 hours now, could it be a bug. The server starts well and everything seems to work until I (re)load a page which has the {{ ws_client }} then my logs spit out.

php.CRITICAL: Fatal Error: Call to undefined function Gos\Bundle\PubSubRouterBundle\Matcher\dump()

#Config.yml
framework:
...
    session: 
        handler_id: snc_redis.session.handler
...

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: %redis_server%
        sessions:
            type: predis
            alias: sessions
            dsn: %redis_server%
            logging: false
......
    session:
        client: sessions
        prefix: sess
        use_as_default: true
.....

# Web Socket Configuration
gos_web_socket:
    client:
        session_handler: @snc_redis.session.handler
        firewall: main
        storage:
            driver: @gos_web_socket.sessions.predis
            decorator: ~
    shared_config: true
    assetic: true 
    server:
        port: 1337
        host: localhost
        origin_check: false
        router:
            resources:
                - @WebSocketsBundle/Resources/config/pubsub/routing.yml
........

#services.yml
services:
    gos_web_socket.sessions.predis:
        class: Gos\Bundle\WebSocketBundle\Client\Driver\PredisDriver
        arguments:
            - @snc_redis.cache
            - %web_socket_server.client_storage.prefix%

**Comment by ProPheT777** [comment]
Solved in last released of PubSubRouter. Just make a `composer update` to get the latest version :)

Thank you very much @Don87 :)

**Comment by Don87** [comment]
@ProPheT777 
Thank you for the speedy response! I just installed this bundle yesterday so this fix must have happened sometime today? I have done a composer update gos/web-socket-bundle but it says nothing to install or update.

**Comment by Don87** [comment]
@ProPheT777 
Sorry, should have done a complete composer update, the new version has come now. Thanks again for the lovely bundle(s) and support!
