### ISSUE TITLE
IIS throws a 403 error

### ISSUE THREAD

**Issue by legarasu** [GeniusesOfSymfony/WebSocketBundle#74]
I am trying to use WebSocketBundle with IIS, i use the address ws://my.domain.com, it works fine with built-in server (Ratchet) in Ubuntu but IIS throws me a 403  (Forbidden) error, i supouse due to invalid URL, but i have tried a lot of possible ws:// URLs without not sucess.

Thanks,

**Comment by ProPheT777** [comment]
Can you past the configuration of the bundle that you are using ?

**Comment by legarasu** [comment]
In resources/config/config.yml

gos_web_socket:
    server:
         port: %web_socket_server_port%   #The port the socket server will listen on
         host: %web_socket_server_host%   #The host ip to bind to
         router:
              resources:
                   - @SensorBundle/Resources/config/topic.yml
    pushers:
         wamp:
              host: %web_socket_server_host%       
              port: %web_socket_server_port%
    topics:
         - @forua_api.topic.event

In SensorBundle/Resources/config/topic.yml

forua_topic_event:
    channel: forua/event
    handler:
        callback: 'forua_api.topic.event' #related to the getName() of your topic

I have a service with (XML format):
<services>
...
<service id="forua_api.topic.event" class="%forua_api.topic.event.class%" />
...
</services>


Thanks,

**Comment by ProPheT777** [comment]
Hey, 

You topic.yml is wrong, please look at this docs : https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/TopicSetup.md#step-2-register-your-service-with-symfony

I recommend you to use the tag way instead of registering the service in the config.yml

**Comment by legarasu** [comment]
Sorry, i have tried your suggest but still it does not work, is possible that you provide me an example? Thanks

**Comment by Joursain** [comment]
Sorry but this bug stills remains, this library does not work on IIS

**Comment by ProPheT777** [comment]
Have you debug step by step to spot which part of code throw that forbidden exception
