### ISSUE TITLE
Get username in client side

### ISSUE THREAD

**Issue by rahit** [GeniusesOfSymfony/WebSocketBundle#76]
Logged in user is connected with WS without problem. But now I want to get username in client side. But if I publish using js, I only get the message. How can I get the username and other related information. I have tried to modify MyTopic class. But it seems topic method(onPublish) does not work in case I send message through js. Also, if I want to add some other information with message how can I do that?

Here is the code for client side:
```
        var _WS_URI = "ws://{{ websocket_host }}:{{ websocket_port }}/";
        var webSocket = WS.connect(_WS_URI);
        webSocket.on("socket/connect", function(session){
            session.subscribe("app/notification", function(uri, payload){
                console.log("Received message ", uri, payload); 
            });
            session.publish("app/notification", "I want to send more info including username with this message");

        });
```

**Comment by rahit** [comment]
Never mind. solved.

**Comment by shairyar** [comment]
I am looking for the solution to this, can you please explain how did you solve it?
