### ISSUE TITLE
Can't install on Symfony2.3 with PHP 5.4

### ISSUE THREAD

**Issue by rajkaran** [GeniusesOfSymfony/WebSocketBundle#78]
Hi there,

Is there any possibility of installing this bundle on with Symfony2.3, PHP 5.4. Getting an error saying bundle requires PHP 5.5. 

Does this bundle has fallback support for IE-9 as IE-9 doesn't have inbuilt Websocket support.

**Comment by ProPheT777** [comment]
Hi, 

Problem solved, I downgrade framework bundle inside GeniusesOfSymfony/PubSubRouterBundle to require ~2.3 at least.

> Does this bundle has fallback support for IE-9 as IE-9 doesn't have inbuilt Websocket support.

Currently not, but I can solve this problem. I need to provide a websocket polyfill in client side and enable FlashPolicy on server side. According to : http://socketo.me/docs/flash

**Comment by rajkaran** [comment]
That will be a great addition....

**Comment by ProPheT777** [comment]
Yeah i have realized after that my vm was under 5.5 i'm sorry ... I going to check under 5.4 
Le 2 nov. 2015 22:54, Raj karan <notifications@github.com> a écrit :That will be a great addition....

**Comment by rajkaran** [comment]
Did you got chance to test it on PHP 5.4 environment?

If yes, I still can't install it. getting below error.

```
Using version ^1.6 for gos/web-socket-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install gos/web-socket-bundle v1.6.1
    - Conclusion: don't install gos/ratchet-stack v0.1.0|remove cboden/ratchet v0.2.8|install gos/web-socket-bundle v1.6.1
    - gos/web-socket-bundle v1.6.0 requires gos/ratchet-stack ~0.1 -> satisfiable by gos/ratchet-stack[v0.1.0].
    - Installation request for gos/web-socket-bundle ^1.6 -> satisfiable by gos/web-socket-bundle[v1.6.0, v1.6.1].
    - Conclusion: don't install cboden/ratchet v0.2.8
    - gos/ratchet-stack v0.1.0 requires cboden/ratchet ~0.3.0 -> satisfiable by cboden/ratchet[v0.3.0, v0.3.1, v0.3.2, v0.3.3], gos/web-socket-bundle[v1.6.1].
    - Can only install one of: cboden/ratchet[v0.3.0, v0.2.8].
    - Can only install one of: cboden/ratchet[v0.3.1, v0.2.8].
    - Can only install one of: cboden/ratchet[v0.3.2, v0.2.8].
    - Can only install one of: cboden/ratchet[v0.3.3, v0.2.8].
    - Installation request for cboden/ratchet == 0.2.8.0 -> satisfiable by cboden/ratchet[v0.2.8].
```

**Comment by videni** [comment]
@rajkaran , have you solved the problem yet? I got the same problem, have no way to fix it.

**Comment by rajkaran** [comment]
@videni no I didn't found any solution so i went back to Ajax.
