### ISSUE TITLE
Example Request : Send message from any controller

### ISSUE THREAD

**Issue by The-Don-Himself** [GeniusesOfSymfony/WebSocketBundle#79]
A lot of relatively new concepts here, sockets, AMQP, etc which I think will help us build real time apps using our favorite framework - Symfony!

Now, using Symfony controllers are the main thing  - controlling our logic. My question may seem simple but I wouldn't be surprised if it's answer is a bit complex. Is there a (simple) way to send messages from any controller to a websocket channel.

Example : 
All non-logged in users are subscribed to a channel say acme/notifications I would like to entice them to register and be part of the community by sending them updates on things happening on the site by registered users. Is there a way like say

Blog Post Controller
-------------------------
$em->persist($new_post);
$em->flush();

$gos_socket = $this->get('gos_socket_something');
$gos_socket->setChannel('acme/notifications');
$gos_socket->setMessage('new post - name - id -other info - could be array as well');
$gos_socket->('publish');

Blog Comment Controller
-------------------------
$em->persist($new_comment);
$em->flush();

$gos_socket = $this->get('gos_socket_something');
$gos_socket->setChannel('acme/notifications');
$gos_socket->setMessage('new comment - username - userid - other info - could be array as well');
$gos_socket->('publish');

I installed this bundle a few days ago and love the promise of using websockets with Symfony but so far quite a lot seems Greek to me.

**Comment by hidabe** [comment]
I have same problem :(

**Comment by hidabe** [comment]
I am trying:
        $topic = new Topic("acme/channel");
        $topic->broadcast([
            'msg' => "hola mundo"
        ]);

And it not is working

**Comment by ProPheT777** [comment]
hello, 

In fact it's simple. You can use 3 ways to push from a controller to your server.

- Via php websocket client
- Via AMQP
- Via ZMQ (the most faster)

Here full example https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/Pusher.md

Have you already try them ?

**Comment by hidabe** [comment]
i was just trying it... i know, websocket need "live" connection, i need send "with" socket, so, i need any like: https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/Pusher.md ok, i am trying it now, thanks and regards!

**Comment by hidabe** [comment]
shit again :-1: i am trying "slow" configuration, via php websocket client, but it not is working for me, "Could not open socket. Reason: Connection refused" error,

need i any service here?
port: 1337

Thanks!

**Comment by ProPheT777** [comment]
Can yu show me you connection of server and client (replace your %parameter% by real value) ?

**Comment by hidabe** [comment]
Uhm, what parameter? :S

**Comment by ProPheT777** [comment]
Sorry I wrote that so fast, I've forgot letter haha, Anyway, your configuration of client and server with real parameter value instead of %my_parameter% for example (only if you use parameters)

**Comment by hidabe** [comment]
this is my configuration:
```yml```
# Web Socket Configuration
gos_web_socket:
    server:
        port: 8080        #The port the socket server will listen on
        host: 127.0.0.1   #The host ip to bind to
        router:
            resources:
                - @AppBundle/Resources/config/pubsub/routing.yml
    pushers:
        wamp:
            host: 127.0.0.1
            port: 1337

server is working perfectly, but pusher is not working :(

**Comment by hidabe** [comment]
Sorry, it is working now, port for pusher should be same that server:
```yml```
gos_web_socket:
    server:
        port: 8080        #The port the socket server will listen on
        host: 127.0.0.1   #The host ip to bind to
        router:
            resources:
                - @AppBundle/Resources/config/pubsub/routing.yml
    pushers:
        wamp:
            host: 127.0.0.1
            port: 8080

**Comment by ProPheT777** [comment]
Indeed, only when you use WAMP pusher ;) because it connect directly to it. But I discourage to use this pusher in production, he is very slow.

**Comment by hidabe** [comment]
yes, i know, thanks!

**Comment by The-Don-Himself** [comment]
Sorry for being late to the discussion, I have worked on this most of the weekend and will provide many parts of my code for those interested in seeing this in a real production environment. Reading through this thread, indeed, pusher is what I was looking for, using WAMP on development but plan to switch to ZMQ for production.

Thanks for the awesome bundle and support eager to help out any way I can!
