### ISSUE TITLE
Is it possible to refresh session?

### ISSUE THREAD

**Issue by Venzon** [GeniusesOfSymfony/WebSocketBundle#81]
HI

Is it possible to refresh/reload session when user connected to ws and authorized thru firewall will logout?
I think about periodically refreshing session of every connected user which is recognized as fully authorized to see if connected user is still logged in to backoffice cms.
Now authorized session remains on ws when user logouts from firewall.

Regards

**Comment by ProPheT777** [comment]
No but he can be it implemented, if you are running into this issue feel free to open a PR :)

**Comment by Venzon** [comment]
@ProPheT777 thx for replay
Do you have any tips what will be best way to implement such feature?

**Comment by ProPheT777** [comment]
To be honest I have no idea :D Just try and will see how we can find the best way. 

May be expose a refresh API from connection

**Comment by novacp** [comment]
How to refresh the session? Im running in the same problem. I don't need periodical refresh, just a refresh during a remote call procedure, because the session on websocket is not up to date, just loaded once when connecting to the websocket..?

**Comment by Venzon** [comment]
@novacp I still did not figure this out

**Comment by novacp** [comment]
Hey Luke,
Look at my Post / question. I answered myself :) it should be one of the
latest
Am 09.05.2016 6:10 nachm. schrieb "Luke" <notifications@github.com>:

**Comment by Venzon** [comment]
@novacp you mean this post https://github.com/GeniusesOfSymfony/WebSocketBundle/issues/147 ?
