### ISSUE TITLE
Use external socket.io Client ?

### ISSUE THREAD

**Issue by grimabe** [GeniusesOfSymfony/WebSocketBundle#83]
Does this bundle works with standard socket.io external client like this one : https://github.com/socketio/socket.io-client-swift

or is it only working with the  provided web/js client ?

Just in case : I am adding a Chat feature to a symfony backend so I am looking to every solutions able to do that. 

Thank you

**Comment by ProPheT777** [comment]
Hey, 

I don't think that you can have socket.io client and websocket server because they provide both part, and they have a like WAMP protocol but not the same. But may be you can check if WAMP client implementation exist for Swift.

**Comment by grimabe** [comment]
Hi,

Thank you !

Indeed there is one for objective-c so I'm gonna checkout this https://github.com/mogui/MDWamp

**Comment by fdydk** [comment]
hey grimabe, did the mogui/mdwamp library work for you, we are trying it but it just crashes on connect
