### ISSUE TITLE
Questions - Authentificated User and storage id

### ISSUE THREAD

**Issue by Coyzz** [GeniusesOfSymfony/WebSocketBundle#93]
First off all, thanks for your work on this bundle !

My project is to implement Symfony as BackEnd  and AngularJS as FrontEnd service. I consume data with APIRest.

I implement LexikJWTAuthenticationBundle for providing security exchange to FE and BE.

For the standard implementation, the websocketbundle work great !!

My problem is that i don't use Cookie and Session to retrieve the authentificated user.

I tried to share the session (PDO Handler with Symfony and WebSocketBundle), but as is expected, ClientManipulator can't identify the connected user.

I have an idea to identifying the connected user. When  user publish to friends channels, i send the user id with the data (it may be a track..).

But the issue is not in the Topic. I would like also to implement Redis server as you recommand. The configuration work good. But know i want to identify the ClientStorage by his id, in order to retrieve a list that contain all sending message for the user ...!

As i show, this class is construct when the connection to WS occured. So it's not yet possible for the retrieve the user ID. 
Questions : 

1 ) When the ws.on() occured, can i try to catch the URL Object  : https://github.com/ratchetphp/Ratchet/pull/143. The idea is when i connect to ws://127.0.0.1/user_id, i can get onConnect the user_id.

2) i Use Bundle Inheritance to try to override the ClientStorage. But as expected, it is a little bit complicated, because some others class needed CLientStorage and ClientStorageInterface (like AuthProvider, ClientManipulator, WampApplication....). The Bundle Inheritance seem to be not working and I don't want to modify one line off your bundle.

3) Is there a way to associate LexikJWTAuthenticationBundle  and WebSocketBundle to retrieve users ? Actually i have created a topic like /channel/login_check, responsive to check in the user in database if exist and connected. If it pass, the user has the  authorization in angular to connect to friends channels.

Have you any suggestion/recommendation ?  I can be on the wrong path  do not hesitate :)

Thank you for your time

**Comment by ProPheT777** [comment]
Sorry for the delay :s

Yes today the only way to deal with authentication is via cookie ... 

Have try with sticky session ? 

On my side i'm using JSON websocket with this bundle so ... but if you provide an acme app with your example I can support JSON token with lexik bundle as well. 

Currently we are not using the "official" ratchet, she is replace by this one https://github.com/GeniusesOfSymfony/Ratchet so we are not blocked to add the feature. 

If you want implement this feature or provide acme app, or nothing, it's as you wich!

**Comment by Coyzz** [comment]
Hello,

Thank for your answer and the proposal!

I will found out about the sticky session and try that!

I expect to have a step back on the best solution for my project as soon as it becomes clear coming back to you.

Thanks
