### ISSUE TITLE
Unknown "javascripts" tag in GosWebSocketBundle::client.html.twig at line 1.

### ISSUE THREAD

**Issue by anboo** [GeniusesOfSymfony/WebSocketBundle#95]
Symfony 2.8

My template - http://pastebin.com/MsZRK70k
After ```{{ ws_client() }}``` print this error:
Unknown "javascripts" tag in GosWebSocketBundle::client.html.twig at line 1.

```at Twig_Environment ->compileSource ('{% javascripts '@GosWebSocketBundle/Resources/public/js/vendor/autobahn.min.js' '@GosWebSocketBundle/Resources/public/js/gos_web_socket_client.js' %} <script type="text/javascript" src="{{ asset_url }}"></script> {% endjavascripts %} ', 'GosWebSocketBundle::client.html.twig') ```

**Comment by anboo** [comment]
And after ``` php app/console assetic:dump --env=prod --no-debug ```
Printed me error:
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]  
  The parameter "gos_pubsub_registered_routers" must be defined.

**Comment by ProPheT777** [comment]
Yes since symfony2.8 assetic bundle is removed. You can add it manualy if you want continue to use it or refer to this to do it by yourself : https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/ClientSetup.md

**Comment by anboo** [comment]
I just run ```php app/console assets:install --env=prod```
End after include js depends:
```html
<script type="text/javascript" src="{{ asset('bundles/goswebsocket/js/gos_web_socket_client.js') }}"></script>
<script type="text/javascript" src="{{ asset('bundles/goswebsocket/js/vendor/autobahn.min.js') }}"></script>
```
