### ISSUE TITLE
Configuration SSL

### ISSUE THREAD

**Issue by medooch** [GeniusesOfSymfony/WebSocketBundle#97]
Hi all, 
I need to configure my project with ssl.

So, i have Mamp Pro, and i have created a new Generated SSL certificate.
My server is running via Https,

Right now, i cant connect to server via Javascripts client : 
After 10 sec, this is the javascripts error that ive got : 

WebSocket connection to 'wss://127.0.0.1:4000/' failed: Error in connection establishment: net::ERR_TIMED_OUT
(index):111 Disconnected for Connection could not be established. with code 3

and this is my configuration : 

gos_web_socket:
    pushers:
        wamp:
            host: 127.0.0.1
            port: 4000
    server:
        port: 4000        #The port the socket server will listen on
        host: 127.0.0.1   #The host ip to bind to
        router:
            resources:
                - @AppBundle/Resources/config/pubsub/routing.yml

This is the javascripts code : 
var websocket = WS.connect("wss://127.0.0.1:4000");

        websocket.on("socket/connect", function(session)

Any help please ?

**Comment by ProPheT777** [comment]
Hello, 

Have try to use stunnel like in the documentation ? https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/Ssl.md

**Comment by ProPheT777** [comment]
Solved : http://stackoverflow.com/questions/34699217/symfony2-geniusesofsymfony-websocketbundle-ssl-error-connection
