### ISSUE TITLE
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead

### ISSUE THREAD

**Issue by AITG** [GeniusesOfSymfony/WebSocketBundle#98]
I've just installed gos/web-socket-bundle into Symfony 2.7 via composer and received the messages below. Not sure if this is a new issue or not, but couldn't see it mentioned.

Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.

**Comment by ProPheT777** [comment]
Hey,

Yeah it's a well know issue but it's not related to websocket bundle
directly. Ratchet is requiring these old packages. It's not a real problem,
and that will be fix in the next release of ratchet.
